### ISSUE TITLE
some left out logging in the production library

### ISSUE THREAD

**Issue by omerkirk** [go-goracle/goracle#1]
I am using Cursor's NewVar for passing in is parameters to an oracle procedure. I saw some unintended log messages and it seems like these are produced by the goracle library. Is it possible to connect logging to some setting.

**Comment by tgulacsi** [comment]
Try 47a9515, hope that's better.
Sorry for the inconvenience.

**Comment by omerkirk** [comment]
Thanks for the quick fix. 

I will be using this library quite heavily in a very high traffic adserver project. If you need any help on the project, I would be glad to contribute to it.
