### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by hanzhenbjm** [go-goracle/goracle#102]
func Callpro(id string){
	var res interface{}
	qry := `BEGIN SP_DEAL_GETLINESBYITEMID(:id,:order_id); END;`

	if _, err := Db.Exec(qry,id,sql.Out{Dest:&res});err!=nil{
		Log.Debug("exec err is %s",err)
	}
	rest := res.(driver.Rows)
	value := make([]driver.Value,len(rest.Columns()))
	for {
		if err := rest.Next(value);err != nil{
			if err == io.EOF{
				Log.Debug("err is %v",err)
				break
			}
			Log.Debug("value is %v",value)
		}
	}
}

SP_DEAL_GETLINESBYITEMID Out parameters TYPE is CURSOR

Report errors： dpiStmt_execute(mode=32 arrLen=-1)  
                          Parameter number or type error

**Comment by tgulacsi** [comment]
qry := `BEGIN SP_DEAL_GETLINESBYITEMID(:1, :2); END;`

Is this a procedure, with the second argument being  the OUT REF CURSOR ?

**Comment by hanzhenbjm** [comment]
The stored procedure is implemented ：Get order_id through ID，
CREATE OR REPLACE PROCEDURE SP_DEAL_GETLINESBYITEMID(ORDERITEMID VARCHAR2,
                                                               REF_CURSOR  OUT SYS_REFCURSOR)
if _, err := Db.Exec(qry,id,sql.Out{Dest:&res});err!=nil{
	Log.Debug("exec err is %s",err)

this is the err 
exec err is dpiStmt_execute(mode=32 arrLen=-1): ORA-06550: First rows, seventh columns
PLS-00306: call 'SP_DEAL_GETLINESBYITEMID'Parameter quantity or type error
PL/SQL: Statement ignored

**Comment by cjbj** [comment]
@hanzhenbjm you would really help @tgulacsi if you gave a runnable .SQL script that created the tables, data and procedure, and a **runnable** Go file that showed the problem.

**Comment by tgulacsi** [comment]
@hanzhenbjm why have you closed this issue? What was the solution?

**Comment by hanzhenbjm** [comment]
var res interface{}  before
var res driver.Rows  after 
already success
thank you
