### ISSUE TITLE
How to convert goracle.Number to int64 to int32

### ISSUE THREAD

**Issue by margem** [go-goracle/goracle#103]
I'm trying convert a goracle.Number to int64 but return this message: **interface conversion: driver.Value is goracle.Number, not int64**

**Comment by cemremengu** [comment]
You need to use `.Value()` before converting

**Comment by margem** [comment]
@cemremengu do you have any exemples? I did not understand 

       	v, s := values[0].Value().(int32)
       	log.Println(v)
       	log.Println(s)

**Comment by cemremengu** [comment]
My bad can you try

`strconv.ParseInt(values[0], 10, 64)`

**Comment by margem** [comment]
@cemremengu 
The code returned this: 
**cannot use values[0] (type driver.Value) as type string in argument to strconv.ParseInt: need type assertion**

**Comment by cemremengu** [comment]
`strconv.ParseInt(values[0].(goracle.Number), 10, 64)` :)

**Comment by tgulacsi** [comment]
You can use goracle.WrapRows (experimental) to turn the driver.Rows into an
sql.Rows and have its nise Scan functionality.

Margem <notifications@github.com> ezt írta (időpont: 2018. szept. 26., Sze
22:02):

**Comment by margem** [comment]
@cemremengu and @tgulacsi 

I have an code, but It return a erro: **cannot use g (type goracle.Number) as type string in argument to strconv.ParseInt**

  		g, _ := values[0].(goracle.Number)
  		c, _ := strconv.ParseInt(g, 10, 64)

I don't know to use goracle.WrapRows

**Comment by tgulacsi** [comment]
```
strconv.ParseInt(string(values[0].(goracle.Number)), 10, 64)
```

or

```
  var rsetI interface{}
  db.Exec(qry, ..., sql.Out{Dest:&rsetI})
  rows, err := goracle.WrapRows(db, rsetI.(driver.Rows))
  for rows.Next() {
    if err = rows.Scan(...)  // just as with a regular sql.Rows after a db.Query
  }
```

**Comment by margem** [comment]
Thanks Guys...
