### ISSUE TITLE
how to storing driver.Value type *goracle.Lob into type *string

### ISSUE THREAD

**Issue by aiderzcx** [go-goracle/goracle#105]
i'am  query  a system view  "v$sql_plan", and scan  OtherXml; 
scan fail :
    Scan error on column index 38: unsupported Scan, storing driver.Value type *goracle.Lob into type *string"

the scan data_type is sql.NullString

part code: 
rows, err := c.db.Query(c.sqlPlanStatusCmd(), notExist[i].SqlId, hash)
for rows.Next() {
    planstats := new(moudle.PlanStatusST)

    err = rows.Scan(
	&planstats.HashValue,         //HASH_VALUE,
	......,
	&planstats.OtherXml,          //OTHER_XML,   OtherXml is sql.NullString
	&planstats.ConId,             //CON_ID
)

Scan error on column index 38: unsupported Scan, storing driver.Value type *goracle.Lob into type *string"

**Comment by tgulacsi** [comment]
Either use an `interface{}` and cast it to `*goracle.Lob` and `Read` from it, or add the `goracle.ClobAsString()` option as argument to the query, which will read the CLOB into memory and provide it as string.
