### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by hanzhenbjm** [go-goracle/goracle#107]
how too reallize goracle Connection pool
db.SetMaxOpenConns(50)
db.SetMaxIdleConns(1)
This is goracle  Connection pool?

**Comment by tgulacsi** [comment]
No, that's database/sql 's connection pool.
As https://godoc.org/gopkg.in/goracle.v2 says, the default is poolMinSessions=1,  poolMaxSessions=1000 and poolIncrement=1.

**Comment by hanzhenbjm** [comment]
gorcle and go-commons-pool  need to work together ?
what is the better way ?

**Comment by tgulacsi** [comment]
What is go-commons-pool? 
If you mean https://github.com/jolestar/go-commons-pool then yes, go-commons-pool MUST call the Close() method on the db (pool) object on eviction!

But why would you use a double pool (pools in pool)???

The database/sql 's DB object is already a pool, no need to wrap it in another pool.

Oracle DB sessions are cached in a default pool, but with maxSessions=1000, so you'd have to touch in only in extreme cases. That pool is only to cache sessions, and only for performance reasons.

When you call db.Query(), database/sql will get a connection from its pool, or create a new one.
When creating a new one, it will ask the goracle driver to do it, so goracle will use Oracle 's session cache to reuse/create one.
When you release (with Close) the sql.Rows returned by that Query call, then that connection goes back to the db pool.
When that db pool evicts that connection, only then it goes back to the goracle driver, which will give it back to the Oracle session pool.

As you see, multi-level caching is complex. This is unfortunate, but each party here adheres to its pool, so we're stuck here :)

**Comment by hanzhenbjm** [comment]
thank you

**Comment by ankushgupta84** [comment]
Is it possible that in certain circumstances, when one sets the db.SetMaxOpenConns(50) in database/SQL layer, there could be actually more than 50 sessions on database end since the goracle allows upto 1000 max sessions as default.

**Comment by tgulacsi** [comment]
If you use only database/sql, and don't create a connection with the goracle driver directly, then no.




On Wed, Sep 11, 2019 at 5:23 AM +0200, "Ankush Gupta" <notifications@github.com> wrote:












Is it possible that in certain circumstances, when one sets the db.SetMaxOpenConns(50) in database/SQL layer, there could be actually more than 50 sessions on database end since the goracle allows upto 1000 max sessions as default.
