### ISSUE TITLE
SDO_GEOMETRY scanning appears broken

### ISSUE THREAD

**Issue by andygarfield** [go-goracle/goracle#108]
I'm trying to get data from an `SDO_GEOMETRY` column, but the scanning seemingly doesn't work. This program just prints 5 blank rows:

```golang
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/go-goracle/goracle"
)

func main() {
	db, err := sql.Open("goracle", "user/pass@db")
	if err != nil {
		panic(err)
	}

	rows, err := db.Query(`
		SELECT SDO_GEOMETRY('POINT(1 0)', 4326) SHAPE FROM DUAL UNION ALL
		SELECT SDO_GEOMETRY('POINT(0 1)', 4326) SHAPE FROM DUAL UNION ALL
		SELECT SDO_GEOMETRY('POINT(-1 4)', 4326) SHAPE FROM DUAL UNION ALL
		SELECT SDO_GEOMETRY('POINT(2 -6)', 4326) SHAPE FROM DUAL UNION ALL
		SELECT SDO_GEOMETRY('POINT(-2 7)', 4326) SHAPE FROM DUAL`,
	)
	if err != nil {
		fmt.Println(err)
	}

	for i := 0; i < 5; i++ {
		rows.Next()
		b := sql.RawBytes{}

		rows.Scan(&b)

		fmt.Printf("% x\n", b)
	}
}
```

**Comment by tgulacsi** [comment]
What is the error?
What is a CREATE for tbl?

**Comment by andygarfield** [comment]
I modified the example above, hopefully that is more helpful. The output is five blank rows.

Thanks for the help!

**Comment by tgulacsi** [comment]
Please try the SDO branch - still does not work, it seems that the objects I got back from ODPI-C are empty.

**Comment by anthony-tuininga** [comment]
It looks to me like the object type associated with the object is being created without having the init() called which populates the various properties of that object type! You'll probably need another constructor type function in obj.go.

**Comment by tgulacsi** [comment]
Thanks, @anthony-tuininga , that init() was the missing potion!

@andygarfield please try the SDO branch (03e789f) !
Scan into `interface{}` and cast it to *goracle.Object, than inspect the Attributes.

**Comment by andygarfield** [comment]
I was able to navigate the object, but I could not get at the scalar data. Am I missing something?
```golang
package main

import (
	"database/sql"
	"fmt"
	"github.com/go-goracle/goracle"
	_ "github.com/go-goracle/goracle"
)

func main() {
	db, err := sql.Open("goracle", "user/pass@db")
	if err != nil {
		panic(err)
	}

	rows, err := db.Query(`
		SELECT SDO_GEOMETRY('POINT(-2 7)', 4326) SHAPE FROM DUAL`,
	)
	if err != nil {
		fmt.Printf("error %v", err)
	}

	rows.Next()

	var data interface{}
	rows.Scan(&data)

	obj := data.(*goracle.Object)

	for _, a := range obj.ObjectType.Attributes {
		if a.Name == "SDO_POINT" {
			for _, val := range a.ObjectType.Attributes {
				fmt.Printf("%v\n", val.Name)
			}
		}
	}
}
```

Output:
```
X
Y
Z
```

**Comment by tgulacsi** [comment]
e4ef005 is better (the API is  weird: you have to use ObjectType.Attributes, but GetAttribute on the object itself...), but now I get ```0. "X": {3009 0x7f748805ea40} (ORA--12153: driver: bad connection)``` errors.

I'm attaching the log with `DPI_DEBUG_LEVEL=3` ([sdo.log](https://github.com/go-goracle/goracle/files/2440881/sdo.log)), @anthony-tuininga  can you help?
(This DB I've tested against does not have SDO_POINT, so I've created a test version of it according to SDO_POINT's documentation).

**Comment by tgulacsi** [comment]
Here is the log with `DPI_DEBUG_LEVEL=999`: [sdo.log](https://github.com/go-goracle/goracle/files/2440891/sdo.log)

**Comment by tgulacsi** [comment]
Forget it. It's on my side.
d6e3238 is better, but not perfect yet.

**Comment by anthony-tuininga** [comment]
Taking a quick peek at the code I am wondering why you don't store a map by name of the various attributes internally and then have this method instead?

func (O *Object) GetAttribute(name string, dest interface{}) error

Then, internally you can look up the attribute by name (which is probably more useful to your end users than an integer index!) and you scan do the same thing as Scan itself does for queries. This would allow you to use it as follows:

var gtype int
err := obj.GetAttribute("SDO_GTYPE", &gtype)

I'm not a Go expert, though, so maybe I'm missing something. :-)

**Comment by tgulacsi** [comment]
Ok, 592f801 works, as long as I tested!

**Comment by andygarfield** [comment]
Here is an example of a real feature.
```sql
SELECT MDSYS.SDO_GEOMETRY(
	3001,
	NULL,
	NULL,
	MDSYS.SDO_ELEM_INFO_ARRAY(
		1,1,1,4,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
	),
	MDSYS.SDO_ORDINATE_ARRAY(
		480736.567,10853969.692,0,0.998807402795312,-0.0488238888381834,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	) SHAPE FROM DUAL
```
I got my previous simple case to work, but shouldn't there be a method on `*goracle.Data` that can access the array inside the object? I get `<null>` back when I try to access `SDO_ORDINATE_ARRAY` with `Data.GetObject()`.

**Comment by andygarfield** [comment]
`Object.Get(name) (interface{}, error)` seems like it would be a good option, in my opinion.
