### ISSUE TITLE
Reading NVARCHAR2 columns seems to produce ??????? 

### ISSUE THREAD

**Issue by omerkirk** [go-goracle/goracle#11]
Hi 

I am trying to read columns that have type NVARCHAR2 on our oracle DB and I am getting ????.

However when I tried a method you suggested in one of the oci-8 issues
https://github.com/mattn/go-oci8/issues/10 
mainly selecting HEX from the DB and converting it back to string on the app things work ok.

I was just wondering is there any other way to do this, since it seems kind of a hacky way to do it. 

I am porting one of our services to go, and I am not having this issue on .NET side for example. Maybe I am missing some extra configuration on the go side. 

Any help would be appreciated.

**Comment by tgulacsi** [comment]
Hi!

1. Please try gopkg.in/rana/ora.v3, that's maybe better.
2. I'm not really met with NVARCHAR2 yet. What is the DB's NLS_CHARACTERSET and NLS_NCHAR_CHARACTERSET? Can you answer the questions in https://github.com/mattn/go-oci8/issues/10#issuecomment-46218828 ?

**Comment by omerkirk** [comment]
Thanks I will checkout rana. In one of the goracle issues somebody mentioned that rana has a slower select row/s rate than goracle, that is why I didn't want to try it since I am doing just basic SELECT, INSERT. I am frequently selecting over 5M rows from DB so if it is actually slower than goracle it wouldn't work for me. 

I will check the character sets of the db and let you know. But from what I understood from the discussions in the oci-8 issue, if there was a problem with the character sets then the hex conversion trick wouldn't work either.

**Comment by tgulacsi** [comment]
The hex conversion trick works, 'cause it sidesteps the charset conversion problem.

Speed: I'd like to see some benchmarks, I'm sure we can enhance rana/ora.

**Comment by omerkirk** [comment]
Ok good to know it is a very good trick :)

I will create some benchmarks of rana and goracle when I got some time.

**Comment by kokteyldev** [comment]
Hi, 

I have also tested reading NVARCHAR2 columns using rana, however I get the same result.
I've created a test table and basic insert for this case. I've tried looking into cx_oracle and ocilib documentations to be able to understand better where the problem might be, however it is just too complex to learn sifting through documentation. I have no idea what I am doing :) 
```
CREATE TABLE TEST_NVAR
(
  TN_NAME  NVARCHAR2(1500)
);

INSERT INTO TEST_NVAR (TN_NAME) 
VALUES (COMPOSE(UNISTR('\0625\064a\0646\062f\0647\0648\0641\0646')));

SELECT * FROM TEST_NVAR;
```

If you try this from goracle it will return ?????.  
http://docs.oracle.com/cd/B19306_01/server.102/b14220/datatype.htm#i3253
NVARCHAR2 is a column type that can only contain unicode strings so there should be a way to use that restriction to convert the read data. I couldn't find it in the code though. If you can point me to the right direction I will be glad to work on a fork and create a pull request.

**Comment by omerkirk** [comment]
Hi, 

I have also tested reading NVARCHAR2 columns using rana, however I get the same result.
I've created a test table and basic insert for this case. I've tried looking into cx_oracle and ocilib documentations to be able to understand better where the problem might be, however it is just too complex to learn sifting through documentation. I have no idea what I am doing :) 
```
CREATE TABLE TEST_NVAR
(
  TN_NAME  NVARCHAR2(1500)
);

INSERT INTO TEST_NVAR (TN_NAME) 
VALUES (COMPOSE(UNISTR('\0625\064a\0646\062f\0647\0648\0641\0646')));

SELECT * FROM TEST_NVAR;
```

If you try this from goracle it will return ?????.  It should return إيندهوفن
http://docs.oracle.com/cd/B19306_01/server.102/b14220/datatype.htm#i3253
NVARCHAR2 is a column type that can only contain unicode strings so there should be a way to use that restriction to convert the read data. I couldn't find it in the code though. If you can point me to the right direction I will be glad to work on a fork and create a pull request.

**Comment by tgulacsi** [comment]
INSERT INTO test_nvarchar (nvc) VALUES (UNISTR('\00625\0064a\00646\0062f\00647\00648\00641\00646'));

SELECT DUMP(nvc) FROM test_nvarchar;
Typ=1 Len=32: 0,98,0,53,0,100,0,97,0,100,0,54,0,98,0,102,0,100,0,55,0,100,0,56,0,100,0,49,0,100,0,54

SELECT nvc FROM test_nvarchar;
b5dad6bfd7d8d1d6

???

What is the relation between \x0625 and \x00\x98\x00\x53 ?

**Comment by omerkirk** [comment]
When you drop the initial 0 in unicode it works. You don't need compose as in my example. But unicode characters should be 4 Hex characters.

```
INSERT INTO test_nvarchar (nvc) VALUES (UNISTR('\0625\064a\0646\062f\0647\0648\0641\0646'));
```

**Comment by tgulacsi** [comment]
You're right, "The Unicode encoding value has the form '\xxxx' where 'xxxx' is the hexadecimal value of a character in UCS-2 encoding format." from http://docs.oracle.com/cd/B19306_01/server.102/b14200/functions204.htm

I've thought it needs some other char ('0') after the backslash, and the backslash in itself is not enough.

**Comment by tgulacsi** [comment]
Please try 43e46ae AND gopkg.in/rana/ora.v3 at 80b0498.
