### ISSUE TITLE
Working CLOB and BLOB

### ISSUE THREAD

**Issue by margem** [go-goracle/goracle#111]
Hi people, 
I have a situation, there is a field I my resultSet that is a CLOB but i need to convert to string, how I make this?

**Comment by margem** [comment]
> column

**Comment by tgulacsi** [comment]
Add `goracle.ClobAsString()` argument to the `QueryContext`.
See https://godoc.org/pkg/gopkg.in/goracle.v2/#ClobAsString

**Comment by tgulacsi** [comment]
So, this is a subquery?
What version are you using? Is it at least (v2.7.1 (90dbebaa2f84da439deecf24a2fe01a6e9fcbae6)) ?
This functionality has been added there, so quite new, and maybe not perfect...

**Comment by margem** [comment]
Thanks @tgulacsi
