### ISSUE TITLE
error calling MarshalJSON for type *goracle.Number: unexpected end of JSON input 

### ISSUE THREAD

**Issue by lelvisl** [go-goracle/goracle#112]
Hello!

It is not valid to return simple []byte from Number.String()
```
error calling MarshalJSON for type *goracle.Number: unexpected end of JSON input 
```

If you want to marshal Number as string, you need to add `"` before and after:
```go
return []byte("\""+n.String()+"\""), nil
```
Better solution:
```go
func (n Number) MarshalJSON() ([]byte, error) {
	f, _ := strconv.ParseFloat(n.String(), 64)
	return json.Marshal(f)
}
```

P.S. Thanks for good driver😀

**Comment by tgulacsi** [comment]
`strconv.ParseFloat` is not usable for parsing a Number, as Oracle's NUMBER may hava 38 digits, and a float64 is usable only for 53 bits (64 bits is for 19 digits, so 53 is about 15 digits).

Please help me and give some hint to reproduce your problem - TestMarshalJSON in drv_test.go of f98e180d33c98ce30b4a9e1d56fa6f494ce81a86 does not reproduce...

**Comment by lelvisl** [comment]
```go
func TestMarshalJSON(t *testing.T) {
	type myStruct struct {
		N interface{}
		A int
	}
	n := Number("")
	ttt := myStruct{N: &n, A: 12}
	b, err := json.Marshal(ttt)
	if err != nil {
		t.Fatal(err)
	}
	t.Log(string(b))
}
```
