### ISSUE TITLE
gcc

### ISSUE THREAD

**Issue by sinys15** [go-goracle/goracle#113]
I have tried use your driver and I gor error:
go get gopkg.in/goracle.v2
 gopkg.in/goracle.v2
exec: "gcc": executable file not found in %PATH%

Is it possible avoid to use gcc?

**Comment by tgulacsi** [comment]
Yes, if you set the CC environment variable to another C compiler (clang or
TDM-GCC64 or MINGW64 for example).

As Oracle does not allow access to its proprietary SQL.NET protocol, you
have  to use OCI (or the Oracle-provided binary-only Java JDBC driver).
So no, it's not avidable.

sinys15 <notifications@github.com> ezt írta (időpont: 2018. okt. 18., Cs,
12:52):

**Comment by sinys15** [comment]
Is it possible to have compiled libraries (for all available OS) and just use this library in the driver for Go?
It is just for easy for use the driver (without compilation on C).

**Comment by tgulacsi** [comment]
Maybe. But not easy.

**Comment by CodeReaper28** [comment]
btw I come across same problem but I confused about the explanation I got on my console and I tried the guidance above but sill got this error message
```

ASUS@LAPTOP-MC5PD4IM MINGW64 /d/Eclipse_Workbench/GoWorkbench/AlfaGroup/src/alfatrex-api/alfatrex-cronjobs/cronjob-pod-eod-c (master)
$ GOOS=linux go build main.go
# gopkg.in/goracle.v2
C:\Go\src\gopkg.in\goracle.v2\orahlp.go:65:2: undefined: describeOnly
C:\Go\src\gopkg.in\goracle.v2\orahlp.go:228:26: undefined: PlSQLArrays
C:\Go\src\gopkg.in\goracle.v2\orahlp.go:251:32: undefined: VersionInfo
C:\Go\src\gopkg.in\goracle.v2\orahlp.go:254:10: undefined: VersionInfo
C:\Go\src\gopkg.in\goracle.v2\orahlp.go:260:32: undefined: VersionInfo
C:\Go\src\gopkg.in\goracle.v2\orahlp.go:277:19: undefined: VersionInfo
C:\Go\src\gopkg.in\goracle.v2\orahlp.go:278:30: undefined: ObjectType
C:\Go\src\gopkg.in\goracle.v2\orahlp.go:279:31: undefined: Event
C:\Go\src\gopkg.in\goracle.v2\orahlp.go:279:41: undefined: Subscription
C:\Go\src\gopkg.in\goracle.v2\orahlp.go:289:27: undefined: conn
C:\Go\src\gopkg.in\goracle.v2\orahlp.go:254:10: too many errors
```

and also when I try to blank import the goracle.v2 I get this error message said that I have no gcc executable file on my go folder
```
# gopkg.in/goracle.v2
exec: "gcc": executable file not found in %PATH%

```

**Comment by RudyTjhia28** [comment]
So I tried to download the gcc for windows then weird error appear

```
# gopkg.in/goracle.v2
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

```
and I have tried looking for MinGW 64 but it just the same
