### ISSUE TITLE
error.Wrap's break database/sql logic

### ISSUE THREAD

**Issue by nogoegst** [go-goracle/goracle#114]
E.g. it breaks reconnection logic on `driver.ErrBadConn`.
Many functions return a wrapped error which is not equal to `driver.ErrBadConn` which makes `database/sql` leave connection as usable while it should reconnect.

**Comment by nogoegst** [comment]
I've stumbled upon one in `BeginTx()`:
https://github.com/go-goracle/goracle/blob/master/conn.go#L208
So a connection breakage doesn't kill the connection.

Oh, now I see what `maybeBadConn` does, thanks! As I expected more errors like this I just removed all `Wraps` :)

**Comment by speakeang** [comment]
@tgulacsi sorry, the fix didn't work out as it still wraps `driver.ErrBadConn`. It should return raw `driver.ErrBadConn` error to make sql driver work properly.

**Comment by tgulacsi** [comment]
If I add a check for the cause is already ErrBadConn, does that help?
See 0ad00126223054c168a82e30637e9d8111144086 .

**Comment by speakeang** [comment]
@tgulacsi, it seems so, thanks!

**Comment by nogoegst** [comment]
@tgulacsi thanks for fixing this!

**Comment by tgulacsi** [comment]
Thanks for the help, I'm really glad we could sort it out!
