### ISSUE TITLE
Using an Oracle Function which Returns a Cursor

### ISSUE THREAD

**Issue by webern** [go-goracle/goracle#117]
Goracle is great, I was able to `select 'hello' from dual` in no time. But now I am scouring for an example of how to use a function to get query results.

Before going further, let me say what I am *actually* trying to do by giving a pseudo T-SQL example. In SQL Server we can do this:

```sql
create procedure usp_get_customers
as
select
  customer_id
, name
from customers
```

And this will 'return query results' just like a select statement. (Technically I don't know what I mean, but if I execute the sproc in SQL Server Management Studio I would see the same results as if I had executed the select statement. And if I called that sproc from an application, it would be just like executing the select.)

I am now in a project that requires me to build in Oracle and I am trying to adapt. I would like the interface between my Golang app and the Oracle database to be specified as either Oracle `function` or `procedure` calls (whichever is more appropriate).

In an attempt to simulate my SQL Server example, I created this Oracle function (12c).

```sql
create or replace function mydb.get_customers
return sys_refcursor
is
    my_cursor sys_refcursor;
begin
    open my_cursor for
    select
      customer_id
    , name
    , product
    from mydb.customers c
    ;
    return my_cursor;
end;
/
```

I would like to call the function and access the results from `goracle`.

Is it possible to use this function with `goracle` and access the results set?

Am I trying to do something stupid?
Is this not the Oracle way?
Should I just write select statements in my golang app?

Any help would be greatly appreciated.

Below is what I tried in Golang, but you can basically ignore it because I know it's not close. I was trying to adapt what I saw in issue #91. I'm thinking I need to introduce a bind variable that 'catches' the function's return.

---

```go
db, err := sql.Open("goracle", "mydb/somepassword@localhost:1521/someservicename")

if err != nil {
    logrus.Fatal(err.Error())
}

var refCursor interface{}
statement := `begin :x := mydb.get_customers(); end;`

_, err = db.Exec(statement, sql.Out{Dest: &refCursor})

if err != nil {
    log.Fatal(err, statement)
}

rset := refCursor.(driver.Rows)
values := make([]driver.Value, len(rset.Columns()))
for {
		err = rset.Next(values);
		if err == io.EOF {
			break
		} else if err != nil {
			logrus.Fatal(err)
		} else {
			log.Println(values)
		}
	}
}
```

**Comment by tgulacsi** [comment]
See #101 - what you have written is not bad at all.
What's your errors?

For such a small thing (just a simple SELECT) I wouldn't use stored procedures, but there may be other constraints (policy to have everything in stored procedure, for example - or that your app must be as dumb as possible).

With `goracle.WrapRows` you can get a `database/sql.Rows` with its `Scan` functionality, but at the end, you have to know your columns (bind vars).

This must either be compiled in (you know the columns at compile time - this means the select could be in the app...), or got known dynamically (reflected at runtime).
The latter can be seen in https://github.com/tgulacsi/go/blob/master/dbcsv/csvdump/csvdump.go#L241 - not nice, but works.

Another solution is to generate the code from `user_arguments` - but then you'll need to specify the REF CURSOR's columns on PL/SQL side:

```
TYPE customer_rec_typ IS RECORD (
  customer_id mydb.customers.customer_id%TYPE
  , name mydb.customers.name%TYPE
  , product mydb.customers.product%TYPE  
);
TYPE customer_cur_typ IS REF CURSOR RETURN customer_rec_typ;

create or replace function mydb.get_customers
return customer_cur_typ
...
```

**Comment by cjbj** [comment]
@tgulacsi FWIW the Oracle DB equivalent of the T-SQL code is '[Implicit Results](https://cx-oracle.readthedocs.io/en/latest/cursor.html#Cursor.getimplicitresults)', a feature from 12.1.  See https://github.com/oracle/python-cx_Oracle/blob/master/samples/ImplicitResults.py

**Comment by tgulacsi** [comment]
Thanks for the example  - Go already has Rows.NextResultSet, a perfect fit (godoc.org/pkg/database/sql/#Rows.NextResultSet).
I'll see what can I do to support it.

**Comment by tgulacsi** [comment]
f4994558790e28a252b3a63395260e31415bd63c added support to NextResultSet.
