### ISSUE TITLE
Go application random crash by invoke QueryContext

### ISSUE THREAD

**Issue by eyeits** [go-goracle/goracle#119]
Code:
        execCtx, execCancel := context.WithTimeout(context.Background(),time.Duration(timeout)*time.Second)
	defer execCancel()
	rows, err := this.db.QueryContext(execCtx, sql)
	if err != nil {
		errMsg := err.Error()
		if errMsg == DB_ERROR_TIMEOUT{
			errMsg = "timed out after " + strconv.Itoa(timeout)+ " seconds"
		}
		return nil,nil,nil,err
	}

Exception:
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xcbc pc=0x7f8e2d7d5d31]

runtime stack:
runtime.throw(0x101233a, 0x2a)
        /alphawolf/code/linux/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /alphawolf/code/linux/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 16081 [syscall]:
runtime.cgocall(0xd78c80, 0xc0044196b0, 0xc0029beb30)
        /alphawolf/code/linux/go/src/runtime/cgocall.go:128 +0x5e fp=0xc004419680 sp=0xc004419648 pc=0x40ea2e
github.com/go-goracle/goracle._Cfunc_dpiConn_release(0x7f8e34060b40, 0x7f8e00000000)
        _cgo_gotypes.go:3146 +0x49 fp=0xc0044196b0 sp=0xc004419680 pc=0x9d3ec9
github.com/go-goracle/goracle.(*conn).Close.func2(0x7f8e34060b40, 0x103bff0)
        /alphawolf/code/go/src/github.com/go-goracle/goracle/conn.go:150 +0x56 fp=0xc0044196e8 sp=0xc0044196b0 pc=0x9fd7c6
github.com/go-goracle/goracle.(*conn).Close(0xc003c71c20, 0x0, 0x0)
        /alphawolf/code/go/src/github.com/go-goracle/goracle/conn.go:150 +0x133 fp=0xc004419778 sp=0xc0044196e8 pc=0x9d9023
database/sql.(*driverConn).finalClose.func2()
        /alphawolf/code/linux/go/src/database/sql/sql.go:520 +0x49 fp=0xc0044197b0 sp=0xc004419778 pc=0x5101f9
database/sql.withLock(0x111ef60, 0xc004398000, 0xc004419848)
        /alphawolf/code/linux/go/src/database/sql/sql.go:3074 +0x63 fp=0xc0044197d8 sp=0xc0044197b0 pc=0x50fef3
database/sql.(*driverConn).finalClose(0xc004398000, 0x0, 0x18)
        /alphawolf/code/linux/go/src/database/sql/sql.go:518 +0x130 fp=0xc004419870 sp=0xc0044197d8 pc=0x503a10
database/sql.finalCloser.finalClose-fm(0xc002b1bb20, 0x111b3e0)
        /alphawolf/code/linux/go/src/database/sql/sql.go:617 +0x2f fp=0xc004419898 sp=0xc004419870 pc=0x51165f
database/sql.(*driverConn).Close(0xc004398000, 0xc000030220, 0xc000030220)
        /alphawolf/code/linux/go/src/database/sql/sql.go:499 +0x13a fp=0xc0044198e8 sp=0xc004419898 pc=0x5038aa
database/sql.(*DB).putConn(0xc002b1bb00, 0xc004398000, 0x111b5c0, 0xc000030220, 0xc004419901)
        /alphawolf/code/linux/go/src/database/sql/sql.go:1251 +0x2e9 fp=0xc004419958 sp=0xc0044198e8 pc=0x507359
database/sql.(*driverConn).releaseConn(0xc004398000, 0x111b5c0, 0xc000030220)
        /alphawolf/code/linux/go/src/database/sql/sql.go:420 +0x4c fp=0xc004419990 sp=0xc004419958 pc=0x50317c
database/sql.(*driverConn).releaseConn-fm(0x111b5c0, 0xc000030220)
        /alphawolf/code/linux/go/src/database/sql/sql.go:743 +0x3e fp=0xc0044199b8 sp=0xc004419990 pc=0x5116ce
database/sql.(*DB).queryDC(0xc002b1bb00, 0x11258e0, 0xc001764240, 0x0, 0x0, 0xc004398000, 0xc0036736e0, 0xc000e626c0, 0xbc, 0x0, ...)
        /alphawolf/code/linux/go/src/database/sql/sql.go:1572 +0x3ec fp=0xc004419b78 sp=0xc0044199b8 pc=0x5092cc
database/sql.(*DB).query(0xc002b1bb00, 0x11258e0, 0xc001764240, 0xc000e626c0, 0xbc, 0x0, 0x0, 0x0, 0x1125801, 0xc0000340b8, ...)
        /alphawolf/code/linux/go/src/database/sql/sql.go:1517 +0x136 fp=0xc004419c08 sp=0xc004419b78 pc=0x508e46
database/sql.(*DB).QueryContext(0xc002b1bb00, 0x11258e0, 0xc001764240, 0xc000e626c0, 0xbc, 0x0, 0x0, 0x0, 0xc0043ed980, 0xc0043eda08, ...)
        /alphawolf/code/linux/go/src/database/sql/sql.go:1494 +0xd3 fp=0xc004419c98 sp=0xc004419c08 pc=0x508aa3
alphawolf.com/eyeits/impls.(*DbClient).Execute(0xc00087cbc0, 0xc000e626c0, 0xbc, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /alphawolf/code/go/src/alphawolf.com/eyeits/impls/dbclient.go:133 +0x166 fp=0xc004419d50 sp=0xc004419c98 pc=0xd02de6
alphawolf.com/eyeits/impls.(*DbConn).run(0xc003349650, 0x0)
        /alphawolf/code/go/src/alphawolf.com/eyeits/impls/dbconn.go:148 +0x3d0 fp=0xc004419fd0 sp=0xc004419d50 pc=0xd080d0
runtime.goexit()
        /alphawolf/code/linux/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc004419fd8 sp=0xc004419fd0 pc=0x4660c1
created by alphawolf.com/eyeits/impls.(*DbConn).Start
        /alphawolf/code/go/src/alphawolf.com/eyeits/impls/dbconn.go:76 +0x1d0

**Comment by tgulacsi** [comment]
Which goracle version?
What is the OCI client version? What is the server?

**Comment by tgulacsi** [comment]
I don't see big changes on master since v2.8.2, but you can try that.

Pleas elaborate a little bit about the case: from the stack trace it is clear that the example code is NOT the one that produces the panic. 

What kind of query is executing?
What is the timeout?
Does it finishes in time or times out?

What version of Go?
