### ISSUE TITLE
Please keep working, it's the best performance driver than the others

### ISSUE THREAD

**Issue by yourchanges** [go-goracle/goracle#12]
Hi,

I have write a simple code to fetch the **2000000** rows from table use three golang oracle driver:
- gopkg.in/goracle.v1                  **==> about 22 seconds**
- github.com/mattn/go-oci8        **==> about 34 seconds**
- gopkg.in/rana/ora.v3                **==> about 660 seconds**

**My ENV:**
centos 6.6 64bit
golang 1.5.3

**The code:**

`func FetchData(db *sql.DB) []int {

```
var r []int

sqlstr := `SELECT id FROM xxxx.geolocation`

// Prepare statement for reading data
stmtOut, err := db.Prepare(sqlstr)
checkErr(err)
defer stmtOut.Close()

rows, err := stmtOut.Query()
checkErr(err)

for rows.Next() {
    var id int
    err = rows.Scan(&id)
    checkErr(err)
    r = append(r, id)
}
return r
```

}`

**Comment by tgulacsi** [comment]
What kind of table is that? Can you share its CREATE TABLE statement?
Maybe a small (10 record) sample, too?

**Comment by yourchanges** [comment]
CREATE TABLE "xxxx"."GEOLOCATION" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PERSON_ID" NUMBER(*,0), 
	"PERSON_ACCOUNT_ID" NUMBER(*,0), 
	"ORGANIZATION_ID" NUMBER(*,0), 
	"ORGANIZATION_MEMBERSHIP_ID" NVARCHAR2(45), 
	"LOCATION" NVARCHAR2(2000) NOT NULL ENABLE, 
	"DEVICE_ID" NVARCHAR2(45), 
	"DEVICE_REGISTRATION_ID" NVARCHAR2(500), 
	"DEVICE_NAME" NVARCHAR2(45), 
	"DEVICE_TYPE" NVARCHAR2(45), 
	"DEVICE_OS_NAME" NVARCHAR2(45), 
	"DEVICE_TOKEN" NVARCHAR2(45), 
	"DEVICE_OTHER_DETAILS" NVARCHAR2(100), 
	"ADDED_TIME" DATE NOT NULL ENABLE, 
	"ROW_CHANGED_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "GEOLOCATION_PK" PRIMARY KEY ("ID")
   )

   "ID","PERSON_ID","PERSON_ACCOUNT_ID","ORGANIZATION_ID","ORGANIZATION_MEMBERSHIP_ID","LOCATION","DEVICE_ID","DEVICE_REGISTRATION_ID","DEVICE_NAME","DEVICE_TYPE","DEVICE_OS_NAME","DEVICE_TOKEN","DEVICE_OTHER_DETAILS","ADDED_TIME","ROW_CHANGED_TIME","RN"
"1","8.37064876162908E16","8.37064898728264E16","12","6506","POINT(30.5518407 104.0685472)","a71223186cef459b","","Samsung SCH-I545","Mobile","Android 4.4.2","","","2015-09-14 23:42:24","27-APR-16 11.09.53.000000 PM","1"
"2","8.37064876162908E16","8.37064898728264E16","12","6506","POINT(30.5520498 104.0686355)","a71223186cef459b","","Samsung SCH-I545","Mobile","Android 4.4.2","","","2015-09-14 23:44:31","27-APR-16 11.09.53.000000 PM","2"
"3","8.37064876162908E16","8.37064898728264E16","12","6506","POINT(30.5517747 104.0684895)","a71223186cef459b","","Samsung SCH-I545","Mobile","Android 4.4.2","","","2015-09-14 23:45:23","27-APR-16 11.09.53.000000 PM","3"
"4","8.64522675633357E16","8.64522734353613E16","","1220457","POINT(30.55187 104.06856)","3A9D1838-3B2D-4119-9E07-77C6CDAC53C5","noUwBnWojdY:APA91bE8aGLEECS9_Q1EKrp8i2B36H1X8GwIj3v58KUcuXglhf0rXJb8Ez5meQ6D5MgTAQghYEe3s9vOntU3pYPQoc6ASNw3QzhzQevAqlMQC2ukUMNyLD8Rve-IA1-6lttsCXYsYIKh","User3’s iPhone","iPhone","iPhone OS","","DeviceID:3A9D1838-3B2D-4119-9E07-77C6CDAC53C5, SystemVersion:8.4, LocalizedModel:iPhone","2015-09-14 23:45:29","27-APR-16 11.09.53.000000 PM","4"
"5","8.37064876162908E16","8.37064898728264E16","12","6506","POINT(30.5517458 104.0685809)","a71223186cef459b","","Samsung SCH-I545","Mobile","Android 4.4.2","","","2015-09-14 23:46:23","27-APR-16 11.09.53.000000 PM","5"
"6","8.37064876162908E16","8.37064898728264E16","12","6506","POINT(30.551802 104.0685301)","a71223186cef459b","","Samsung SCH-I545","Mobile","Android 4.4.2","","","2015-09-14 23:47:23","27-APR-16 11.09.53.000000 PM","6"
"7","8.64522675633357E16","8.64522734353613E16","","1220457","POINT(30.55187 104.06856)","3A9D1838-3B2D-4119-9E07-77C6CDAC53C5","noUwBnWojdY:APA91bE8aGLEECS9_Q1EKrp8i2B36H1X8GwIj3v58KUcuXglhf0rXJb8Ez5meQ6D5MgTAQghYEe3s9vOntU3pYPQoc6ASNw3QzhzQevAqlMQC2ukUMNyLD8Rve-IA1-6lttsCXYsYIKh","User3’s iPhone","iPhone","iPhone OS","","DeviceID:3A9D1838-3B2D-4119-9E07-77C6CDAC53C5, SystemVersion:8.4, LocalizedModel:iPhone","2015-09-14 23:47:29","27-APR-16 11.09.53.000000 PM","7"
"8","8.37064876162908E16","8.37064898728264E16","12","6506","POINT(30.551952 104.0685893)","a71223186cef459b","","Samsung SCH-I545","Mobile","Android 4.4.2","","","2015-09-14 23:49:18","27-APR-16 11.09.53.000000 PM","8"
"9","8.37064876162908E16","8.37064898728264E16","12","6506","POINT(30.5518439 104.0685473)","a71223186cef459b","","Samsung SCH-I545","Mobile","Android 4.4.2","","","2015-09-14 23:49:48","27-APR-16 11.09.53.000000 PM","9"
"10","8.37064876162908E16","8.37064898728264E16","12","6506","POINT(30.5518439 104.0685473)","a71223186cef459b","","Samsung SCH-I545","Mobile","Android 4.4.2","","","2015-09-14 23:49:51","27-APR-16 11.09.53.000000 PM","10"

**Comment by yourchanges** [comment]
The sql only fetch ID column.

**Comment by yourchanges** [comment]
And the python cx_Oracle only takes 18 seconds to do the same thing

**Comment by hljlgj** [comment]
thanks a lot ,on my windows ,works fine,only a little difference between rana/ora and goracle,
starting test oracle database driver: ora
start get sql.DB: 2017-11-01 11:22:26
starting query: 2017-11-01 11:22:27
query finished: 2017-11-01 11:22:37
read one primary key of type char(20),record count: 424684 用时 10248 ms
starting test oracle database driver: goracle
start get sql.DB: 2017-11-01 11:22:37
starting query: 2017-11-01 11:22:37
query finished: 2017-11-01 11:22:55
read one primary key of type char(20),record count: 424684 用时 17585 ms
