### ISSUE TITLE
Inserting a timestamp value loses the fractional second

### ISSUE THREAD

**Issue by ravikumars** [go-goracle/goracle#121]
I am inserting a timestamp value into an oracle database with Column as TIMESTAMP(6). 
e.g.
`SRB_RECEIVE_DATE := time.Now();  
stmt, err := db.Prepare("INSERT INTO {table}(srb_receive_date) values(:1)");  
stm.Exec(SRB_RECEIVE_DATE)`

The record is inserted but the fractional part is all zeroes
![image](https://user-images.githubusercontent.com/1864888/48370930-8a98a380-e688-11e8-86a0-fe2387f3e8ce.png)

The SRB_RECEIVE_DATE itself has the nanosecond part.

Any idea why?

**Comment by tgulacsi** [comment]
goracle uses DATE inside, which does not have fractional second precision.
The reason is that I couldn't make it work with TIMESTAMP PL/SQL arrays.

**Comment by ravikumars** [comment]
Thanks for the update. I am using the timestamp formatted to string and passing on to be inserted. 
e.g.
`SRB_RECEIVE_DATE = time.Now().Format("2-Jan-06 3:04:05.000000 PM")`

Works as expected.
