### ISSUE TITLE
library not found libclntsh.so

### ISSUE THREAD

**Issue by swizzley** [go-goracle/goracle#123]
I'm running in a container and this is what happens, it runs on a full Linux install and on Mac... the runtime seems dependent on this file 

2018/11/15 19:59:03 ORA-00000: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help

**Comment by tgulacsi** [comment]
Yes, that's what Oracle Instant Client provides - the only way to connect to Oracle ATM.

**Comment by swizzley** [comment]
so I need the OIC installed or just the libs from it?

**Comment by tgulacsi** [comment]
Just the libs (plus libaio for libclntsh)

**Comment by swizzley** [comment]
dropping libclntsh into vendor/gopkg.in/goracle.v2/odpi/include/ results in the same error, does this lib go somewhere specific for goracle to use it?

**Comment by cjbj** [comment]
The Instant Client installation instructions are on https://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html#ic_x64_inst  You need to set the library search path.  I recommend the ldconfig approach.
