### ISSUE TITLE
Unclear relation between setMaxOpenConnections and poolMaxSessions

### ISSUE THREAD

**Issue by rvegas** [go-goracle/goracle#124]
I'm currently getting hit with a lot of `ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit`.  
  
My current `sessions_per_user` is handled by the DBA and can't be changed easily.  
  
I've been playing around with [setMaxOpenConnectios](http://go-database-sql.org/connection-pool.html) provided by GO's native `sql` package and with the [poolMaxSessions](https://godoc.org/gopkg.in/goracle.v2) provided by `goracle` but I'm getting very unexpected behaviour.  
  
If you look at the following example:  
  
* max connections = 1, poolMax sessions = 2 => causes 2 actual tcp connectios to oracle:
![1-2](https://i.imgur.com/kM2bBV5.png)    
  
* max connections = 1, poolMax sessions = 1 => causes 1 actual tcp connectios to oracle:
![1-1](https://i.imgur.com/xI5K6eB.png)  
  
I was expecting for goracle to respect the maximum connections and work with that, but from what I see it seems that `goracle` seems to open as many connections as it needs depending on its inner `maxPoolSessions` param.
  
 Is this behaviour expected? Am I missing some other configuration parameters? In production we're quickly reaching 50 concurrent sessions, even when some clients are not active.

**Comment by tgulacsi** [comment]
1. Go's database/sql does its own pooling - use `SetMaxOpenConns` to limit the maximum concurrently opened connections, and `SetMaxIdleConns` to limit the max idle conn number.
2. goracle's session pooling pools only the connections which are release by Go's pooling.

Every non-commited transaction and every non-closed Query (Rows) occupies a connection (session),
so watch out to call Close on the Rows, and Commit or Rollback on the Tx.

**Comment by rvegas** [comment]
I see, but still, `goracle` in the first example is breaking the maximum concurrently opened connections which I set to **1**.  
  
I'm still debugging a bit more, from what I see `goracle` will open a new connection to the DB for every Tx that is opened, regardless of the limits set by `setMaxOpenConns`. I'm not saying that's a bad thing, it's just confusing when hunting bugs down.

**Comment by tgulacsi** [comment]
The driver (goracle) does not know about the database/sql pool. It just opens a connection/transaction when database/sql asks for one.

database/sql does not know about the driver's implementation of a Tx - whether it occupies a connection or not.

So the result of this is what you see: transactions can occupy more database connection than what you've set in database/sql.

The hard limit is hat you set with goracle's `poolMax`.

**Comment by rvegas** [comment]
Ok @tgulacsi thanks for the feedback, it has helped a lot. Will take all this into account when reviewing our implementation.
