### ISSUE TITLE
Debug message left in C glue

### ISSUE THREAD

**Issue by kurt-google** [go-goracle/goracle#125]
https://github.com/go-goracle/goracle/blob/77a077cfaa56995817b08df589dad386d935aeaf/subscr.c#L7

I don't believe this fprintf is required, seems like it a leftover from when it was being debugged. per
https://github.com/go-goracle/goracle/commit/b29695ebfc46e887e789308fb1acd9c4f7b6f606#diff-ba29052d4ffd9015fdeb77df41fa366a

**Comment by tgulacsi** [comment]
Yes and no.
I've never found an environment (client & server versions, permissions) to be able to test the subscription functionality. If you know the correct formula, please share with me!

`C.CallbackSubscrDebug` should be changed in `subcr.go#L161` to `C.CallbackSubscr`, and `CallbackSubscrDebug` is not needed. But I haven't been able to test it thoroughly yet.

**Comment by kurt-google** [comment]
I only noticed it upon review of the `c` code. Personally I am not planning to leverage this functionality. I do feel if this code is still in an unstable/non-production state an update of the docs to reflect that would be helpful.

Thanks for getting back, feel free to close this issue.
