### ISSUE TITLE
Call dpiConn_release on transaction commit or rollback

### ISSUE THREAD

**Issue by rvegas** [go-goracle/goracle#126]
Hello, I've been further running investigating a bug we currently have in our architecture, according to #124 every time `commit` or `rollback` is called upon a transaction, the connection that hangs from the `TX` should be released.  
  
I ran into this situation:

1. Open a database pool against a `Oracle DB`
2. Run a `BeginTransaction` with goracle
3. Run `netstat` and find **1** connection was establised
4. Run a second `BeginTransaction` in the same pool
5. Run `netstat` and find **2** connections established
6. Commit the first transaction
7. Run `netstat` and find **2** connections established
7.1 In here I was expecting for the pool to eventually shrink back to 1
8. Run another `BeginTransaction` with the same pool
9. Run `netstat` and find **3** connections established
9.1 I was expecting `goracle` to reuse the one that belonged to the commited TX.  
  
Anyways, other permutations of the test end up in a similar result:  
- `netstat` finding an ever increasing number of connections in **ESTABLISHED** 
- committing or rolling back transactions not decreasing this number
- new transactions that are open eventually open up new connections
- hit the ` ORA-02391 exceeded simultaneous SESSIONS_PER_USER limit Errors` error  
  
  
Further digging down I came to this piece of code, which is where `goracle` handles *commits and rollbacks* via **C**:  
```//-----------------------------------------------------------------------------
// dpiConn_commit() [PUBLIC]
//   Commit the transaction associated with the connection.
//-----------------------------------------------------------------------------
int dpiConn_commit(dpiConn *conn)
{
    dpiError error;

    if (dpiConn__check(conn, __func__, &error) < 0)
        return dpiGen__endPublicFn(conn, DPI_FAILURE, &error);
    if (dpiOci__transCommit(conn, conn->commitMode, &error) < 0)
        return dpiGen__endPublicFn(conn, DPI_FAILURE, &error);
    conn->commitMode = DPI_OCI_DEFAULT;
    return dpiGen__endPublicFn(conn, DPI_SUCCESS, &error);
}
```
  
And I also came to this function:  
```
//-----------------------------------------------------------------------------
// dpiConn_release() [PUBLIC]
//   Release a reference to the connection.
//-----------------------------------------------------------------------------
int dpiConn_release(dpiConn *conn)
{
    return dpiGen__release(conn, DPI_HTYPE_CONN, __func__);
}
```  
  
I see that `goracle` only calls for connection release when closing the actual connection object, I guess it's because Go's `sql` should take care of that, just haven't dug that deep.  
  
Anyways, any insight regarding this can be very helpful for me. Thanks in advance.

**Comment by tgulacsi** [comment]
I could release the connection after Commit/Rollback, but how should we inform the database/sql pool that this connection is unusable? We could mark the connection and force it to return ErrBadConn on every succeeding action, but this is gross.

Please, what is your REAL problem? Really 3 TCP connections is too much?
The number of sessions should stabilize, esp. with correctly set poolMax.

What is your use case? How many concurrent transactions, queries?
Can you create a small reproducing test case?

**Comment by rvegas** [comment]
I will send you a more proper example later, but I simply set the max pool sessions to 3 in the connection, and then opened 3 different transactions, committed one and got a timeout when trying to open a fourth one.  
  
Sorry for brevity, will add more details later.

**Comment by rvegas** [comment]
So, @tgulacsi at the end we discovered 2 things:  
  
- A potential flaw in our side interferring with connections of the `sql` pool.  
- Another potential problem in goracle `conn.go` implementation for which I will open a PR shortly.

I apologize for all the noise regarding these issues but at the end they'll hopefully bring improvements for this project. And it was all caused to very strong limitations imposed by our Oracle DBAs.

**Comment by rvegas** [comment]
What was happening in the end was that our ORACLE profile had an `IDLE_TIMEOUT` of 60 minutes, it was a very hard to catch error, so when oracle `sessions` where marked as `killed` the driver was forwarding the "BAD CONNECTION" to our implementation and Go's `sql` was not handling it.  
  
For testing it we limited resources (session count and idle time to 2 and 1 respectively) and started running queries with and without Txs.

**Comment by tgulacsi** [comment]
Congratulations, nice work!

I know that the DBA could loosen a little bit on those strict rules, but that case you couldn't find this error, and make goracle better :)

Of course I respect those long head-scratching debug sessions though...
