### ISSUE TITLE
Does it support Windows?

### ISSUE THREAD

**Issue by kxjhlele** [go-goracle/goracle#13]
Does it support Windows?

**Comment by tgulacsi** [comment]
Haven't tried it yet, but should.
It's absolutely a goal to support Windows.

ODPI-C does, so this too, if you can overcome the C compiler and pkg-config issues.

**Comment by hljlgj** [comment]
when and how to support for windows? thanks a lot

**Comment by tgulacsi** [comment]
Now, with `go get gopkg.in/goracle.v2` - just have a C (GCC, MinGW, TDM-GCC) compiler at hand.
