### ISSUE TITLE
a strange problem about query, can you give me some suggestion

### ISSUE THREAD

**Issue by aiderzcx** [go-goracle/goracle#131]
use this command to query some info.
select 
 SID,
 decode(STATE,'WAITING',EVENT,'ON CPU') ACTUAL_WAIT_EVENT 
from v$session 
where STATUS='ACTIVE' and WAIT_CLASS!='Idle';

1.  new a sql.DB, use db.query(), i can got the value sometimes.
2.  new a sql.DB everytime and defer db.Close(),  i can got the value sometimes.
3.  new a sql.DB everytime and **not defer db.Close(),  i can got the value everytime.** 

 i use the command in the console, can gets the value everytime,  

what the problem about condition 1 and 2

**Comment by aiderzcx** [comment]
everytime i can got the column names, but not values in 1,2 ,  no errors

**Comment by tgulacsi** [comment]
Sorry, but what is the problem?
The ```select SID, decode(STATE,'WAITING',EVENT,'ON CPU') ACTUAL_WAIT_EVENT
from v$session
where STATUS='ACTIVE' and WAIT_CLASS!='Idle';```
query selects only specific rows, maybe there aren't such sessions at that moment.

Print ALL sessions, find the one you think you need, and check its state.

**Comment by aiderzcx** [comment]
ok, thanks
