### ISSUE TITLE
allow lib init without Oracle libraries

### ISSUE THREAD

**Issue by nicgrobler** [go-goracle/goracle#132]
Firstly, thanks a lot for your work on this lib, it is a massive help for me!

I have a use case whereby we want to install an agent on many systems (for monitoring), only some of which run Oracle - and if the software detects no Oracle client libs, log an error and exit, thereby allowing other parts of the agent to run regardless (collecting system stats, for example). currently, Goracle panics during init if the libs are not present, instead of just returning an error (or, like some other libs, returning an error when Open() is called.

This simply allows the caller to check the errors returned and decide what to do.

Is this something we could perhaps contribute (unless you hate the idea / already working on it)?

**Comment by tgulacsi** [comment]
I get "getConnection: ORA-00000: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help" error if no oracle lib is available.

Definitely not a panic.

**Comment by nicgrobler** [comment]
indeed - I just tested the latest version, and your changes have fixed this (last time I tested using your code was pre v2, where the panic still occurred).

thanks a lot ;-)

**Comment by tgulacsi** [comment]
See #65 and c31f43d .
