### ISSUE TITLE
 dpiStmt_execute(mode=32 arrLen=-1): ORA-02179: valid option: ISOLATION LEVEL { SERIALIZABLE | READ COMMITTED }

### ISSUE THREAD

**Issue by hljlgj** [go-goracle/goracle#133]
when i upgrade newer code from gopkg.in/gracle.v2 ,when i run old code,the error founded  thanks a lot
<nil>panic: SET TRANSACTION ISOLATION LEVEL READ COMMITED: dpiStmt_execute(mode=32 arrLen=-1): ORA-02179: valid option: ISOLATION LEVEL { SERIALIZABLE | READ COMMITTED }

**Comment by hljlgj** [comment]
1. txOP := sql.TxOptions{Isolation: sql.LevelReadCommitted , ReadOnly:false}  
2. txOP := sql.TxOptions{Isolation: sql.LevelDefault , ReadOnly:false}
code first line above will trigger error  ,but when i change sql.LevelDefault, no error found when execute

**Comment by tgulacsi** [comment]
READ COMMITED != READ COMMITTED.
