### ISSUE TITLE
Cannot login locally as sysdba

### ISSUE THREAD

**Issue by gle4er** [go-goracle/goracle#140]
Hello everyone.
I can't connect to oracle instance and call query. If this is my stupidity or mistake - correct me, please.

Code:
```golang
log.Infoln("Connect to", dsn)
db, err := sql.Open("goracle", dsn)
if err != nil {
	log.Errorln("Error while connecting to", dsn)
	panic(err)
}
if _, serr := db.Exec("select user from dual"); serr != nil {
    log.Errorln(serr)
}
```
Logs:
```
INFO[0000] Starting oracledb_exporter 0.2.1              source="main.go:327"
INFO[0000] Connect to oracle://?sysdba=1                 source="main.go:74"
ERRO[0000] username="" sid="" params={authMode:2 connectionClass:0x1d73540 connectionClassLength:7 purity:0 newPassword:<nil> newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:1 externalHandle:<nil> pool:<nil> tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-12162: TNS:net service name is incorrectly specified  source="main.go:81"
ERRO[0000] Error pinging oracle: username="" sid="" params={authMode:2 connectionClass:0x1d73540 connectionClassLength:7 purity:0 newPassword:<nil> newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:1 externalHandle:<nil> pool:<nil> tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-12162: TNS:net service name is incorrectly specified  source="main.go:172"
INFO[0000] Listening on :9161                            source="main.go:349"
```

**Comment by tgulacsi** [comment]
What is the dsn? (Replacing the password with ***).




On Tue, Feb 26, 2019 at 11:42 AM +0100, "Grigory Tarasenko" <notifications@github.com> wrote:












Hello everyone.

I can't connect to oracle instance and call query. If this is my stupidity or mistake - correct me, please.


Code:
log.Infoln("Connect to", dsn)
db, err := sql.Open("goracle", dsn)
if err != nil {
	log.Errorln("Error while connecting to", dsn)
	panic(err)
}
if _, serr := db.Exec("select user from dual"); serr != nil {
    log.Errorln(serr)
}


Logs:
INFO[0000] Starting oracledb_exporter 0.2.1              source="main.go:327"
INFO[0000] Connect to oracle://?sysdba=1                 source="main.go:74"
ERRO[0000] username="" sid="" params={authMode:2 connectionClass:0x1d73540 connectionClassLength:7 purity:0 newPassword:<nil> newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:1 externalHandle:<nil> pool:<nil> tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-12162: TNS:net service name is incorrectly specified  source="main.go:81"
ERRO[0000] Error pinging oracle: username="" sid="" params={authMode:2 connectionClass:0x1d73540 connectionClassLength:7 purity:0 newPassword:<nil> newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:1 externalHandle:<nil> pool:<nil> tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-12162: TNS:net service name is incorrectly specified  source="main.go:172"
INFO[0000] Listening on :9161                            source="main.go:349"

**Comment by gle4er** [comment]
Dsn is oracle://?sysdba=1.
Of course, I want connect like in sqlplus: sqlplus / as sysdba. Password is disabled.

**Comment by tgulacsi** [comment]
The error is " ORA-12162: TNS:net service name is incorrectly specified".

Is TWO_TASK or ORACLE_SID set?

It is possible to connect as sysdba. This feature works. But to sort out other issues, try to connect to a regular user with password first.
An please check that other ways (sqlolus, for example) does work from that environment!

**Comment by gle4er** [comment]
Yeah, sorry, my mistake. I didn't set ORACLE_SID by oraenv. Thanks a lot.
