### ISSUE TITLE
Can anybody give an example that using this goracle to access TimesTen database?

### ISSUE THREAD

**Issue by sinylei** [go-goracle/goracle#148]
Can anybody give an example that using this goracle to access TimesTen database?

**Comment by tgulacsi** [comment]
Nope. What is a TimesTen database?

Can OCI connect to it? Can ODPI-C connect to it? If the latter can, then goracle can, too.

**Comment by cjbj** [comment]
@tgulacsi TimesTen is an in-memory database used by high performance applications. OCI (and ODPI-C) can connect to TimesTen (e.g. via [Python cx_Oracle](https://twitter.com/ScalableDBDoug/status/1075238723334230017)), with some limitations since TimesTens has a different DB architecture. Our TimesTen team noted some issues with goracle but has been focussed on Python. They had some email discussion with you last November about a 'set transaction read write' issue.

**Comment by tgulacsi** [comment]
Ok, so it is possible to connect to TimesTen DB.
But I can't give you an example, sorry.
How do yo connect to it with other programs - for example with sqlplus ?

**Comment by sinylei** [comment]
db, err := sql.Open("goracle", "scott/tiger@10.0.1.127:1521/orclpdb1"), this is the normal connect method using goracle to connect a oracle database.
But the connect string for timesten is different, I use as below:
db, err := sql.Open("goracle", "root/xxxxx@localhost:53397/sampledbCS_1122:timesten_client")
when start my test app, it reports:

Error running query
username="root" SID="//localhost:53397/sampledbCS_1122:timesten_client" minSessions=1 maxSessions=1000 poolIncrement=1 extAuth=0 : ORA-29158: Unable to open library.

@cjbj , can you give me an example how your timesten team connect to Timesten database using goracle?

**Comment by sinylei** [comment]
@tgulacsi 
I do not know how to using sqlplus to connect TimesTen, I use a client provide by TimesTen installation package as below:
[root@centos-7 ttrest]# ttisqlcs sampledbCS_1122

Copyright (c) 1996, 2015, Oracle and/or its affiliates. All rights reserved.
Type ? or "help" for help, type "exit" to quit ttIsql.

connect "DSN=sampledbCS_1122";

Connection successful: DSN=sampledbCS_1122;TTC_SERVER=ttLocalHost_tt1122;TTC_SERVER_DSN=sampledb_1122;UID=root;DATASTORE=/var/TimesTen/tt1122/DemoDataStore/sampledb_1122;DATABASECHARACTERSET=US7ASCII;CONNECTIONCHARACTERSET=US7ASCII;PERMSIZE=40;TEMPSIZE=32;TYPEMODE=0;
(Default setting AutoCommit=1)
Command> 
Command>

**Comment by cjbj** [comment]
> so it is possible to connect to TimesTen DB.

My understanding is goracle is not usable with TT.

**Comment by tgulacsi** [comment]
As far as I could test it (downloaded, but couldn't start a TimesTen server),
TimesTen uses its own client library, not Instant Client / libclntsh.so,
and ODPI-C is not prepared for it, so yes, 

goracle is not usable with TT.

**Comment by cjbj** [comment]
TT can use libclntsh.so - I've used TT with PHP OCI8.  The twitter link above shows it being used with cx_Oracle (i.e with ODPI-C).  It is just that goracle uses some functionality that doesn't work/isn't suited for TT.
