### ISSUE TITLE
Need help with using connection pool and goroutines.

### ISSUE THREAD

**Issue by asimondev** [go-goracle/goracle#151]
In my code I open the database connect in this way:

con := fmt.Sprintf("oracle://?sysdba=1& "+
	"poolMinSessions=%d& poolMaxSessions=%d& poolInrement=0", sessions, sessions)
db, err := sql.Open("goracle", con)
if err != nil {
	msg := "connection string: " + con
	return nil, gl.NewMyError(err, msg, debug.Stack())
}

mydb = db <-- mydb is a global package variable

mydb is a global variable in the specific package oradb. Later in the code I start different goroutines in parallel to execute different SELECT statements. In these goroutes I use the mydb global variable and run the Queries like this:

-- Start of the goroutine.
stmt := fmt.Sprintf("SELECT ...")
rows, err := mydb.Query(stmt)
if err != nil {
	msg := fmt.Sprintf("SELECT statement: %s", stmt)
	return
}
defer rows.Close()

var ev systemEvent
for rows.Next() {
	rows.Scan(&ev.event, &ev.waited)
}
-- End of goroutine.

This works fine on some servers. But the code produces the error on some bigger servers with the higher number of CPUs after some seconds of execution.
The error is:
ERROR 11:21:34 myglobals.go:65: error:  username="" sid="" params={authMode:2 connectionClass:0x7fe4ec0308c0 connectionClassLength:7 purity:0 newPassword:<nil> newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:1 externalHandle:<nil> pool:<nil> tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-01017: invalid username/password; logon denied  context:  SELECT statement: SELECT /* amongo */ s.stat_name, s.value FROM v$sys_time_model s

The connect string uses the OS authentication without the password. So the error ORA-01017 is in my opinion wrong. 
Is it possible, that I have got some issues with using *sql.DB global variable in different goroutines at the same time? Are there some recommendations available on this topic?

**Comment by tgulacsi** [comment]
The posted code seems fine (I'm sure you "defer mydb.Close()" after opening it in reality).

The ORA-01017 seems misleading, but that's what the server returns - so please ask your DBA for help!

How many goroutines are running in parallel? What is the "sessions" set to?
Using goroutine-lifelong context (ctx, cancel := context.WithCancel(context.Background()); defer cancel(); rows, err := mydb.QueryContext(ctx, qry)) may help to ensure that all resources are freed as soon as possible.

But I don't see obvious errors, so look around on the DB side, why does it return that error.

(If that's not possible, you can try to localize the error by setting the number of goroutines lower, the sessions lower, and titrate the "tripping poiint").

**Comment by asimondev** [comment]
The main() function looks like this:
```
db, err := oradb.SetupDatabase(gl.PoolMaxSessions)
if err != nil {
	err.Print(ml.ErrorLog)
	os.Exit(1)
}
defer db.Close()

rc, err := displayLoop() <--- The parallel SELECT statements are called here.
if err != nil {
	err.Print(ml.ErrorLog)
}

os.Exit(rc)
```

The SetupDatabase() runs sql.Open() and saves the return value as a package global variable.
The sessions variable in SetupDatabase() is set to 2. Usually 4-8 SELECT statements could run concurrently from the goroutines. The idea is to start them in parallel using buffered channel and so does not block the main goroutine with UI event loop. 

My assumption is, that say 5 SELECT statements will be started from 5 goroutines at the same time. The connection pool should apply "fan in pattern" to run them using only 2 connections concurrently. So the first two SELECT statements would run and 3 other SELECTs will wail in goroutines in the call to mydb.Query() for a free connection. Is my assumption wrong?

I will re-write the code to use QueryContext. Thanks for the explanation.

I am also partly DBA for this database. I can connect to it with "sqlplus / as sysdba" without any problems as a OS user. This is oracle user, which is also the database software owner. Some other OCI programs runs with OS authentication on the same environment without any problems. The code runs locally using the installed RDBMS EE 12.1 or 12.2. Allo required environment variables like ORACLE_SID, ORACLE_HOME, ORACLE_BASE, LD_LIBRARY_PATCH etc are set. So I can not find any error on the DB side. 

Is it possible to get more details about the errors? Can I produce the core dump or something similar for this error?

**Comment by tgulacsi** [comment]
Try tracing (http://dba-oracle.com/t_oracle_sql_trace.htm),
Limit the concurrency (GOMAXPROCS, db.SetMaxOpenConns),
Set debugging for ODPI-C (https://oracle.github.io/odpi/doc/user_guide/debugging.html),
And report here!

**Comment by asimondev** [comment]
Thanks! It will take some days, because I don't have access to this system immediately.

**Comment by tgulacsi** [comment]
Any chance that you have "ALTER SESSION" in your goroutines?

I've just stumbled open spurious "INVALID username/password" errors when using "ALTER SESSION".

Try v2.13.0, and `goracle.NewConnector(dsn, goracle.NewSessionIniter(map[string]string{"NLS_DATE_FORMAT":"YYYY-MM-DD"})); sql.OpenDB(cxr)`

**Comment by tgulacsi** [comment]
OK, that was a red herring - I really have an "invalid username" error (a stored procedure is invalid because of such error in a DB link), sorry for the noise.

**Comment by asimondev** [comment]
Thanks for thinking on my issue! I really appreciate it.
