### ISSUE TITLE
Queries with TIMEZONE_TZ types never return rows

### ISSUE THREAD

**Issue by hguenther** [go-goracle/goracle#153]
The following program returns no rows, even though running the query directly on the database does:

```package main

import (
	"database/sql"
	_ "gopkg.in/goracle.v2"
	"log"
	"time"
)

func main() {
	db, err := sql.Open("goracle", "...")
	if err != nil {
		log.Panic(err)
	}
	rows, err := db.Query("SELECT FROM_TZ(TO_TIMESTAMP('1-May-2019 09:39:12'),'Europe/Berlin') FROM DUAL")
	if err != nil {
		log.Panic(err)
	}
	for rows.Next() {
		var t time.Time
		err = rows.Scan(&t)
		if err != nil {
			log.Panic(err)
		}
		log.Println(t)
	}
}
```

This happens with all queries that contain a TIMESTAMP_TZ column.

Server version: 11.2.0.4.0 
Client library: 18.3

**Comment by tgulacsi** [comment]
As I see (test in `z_test.go`, at the end), FROM_TZ works if the timezone spec is not a name (01:00 works, Europe/Berlin does not).
On my machine, it also spews "SELECT FROM_TZ(TO_TIMESTAMP('2019-05-01 09:39:12', 'YYYY-MM-DD HH24:MI:SS'), 'Europe/Berlin') FROM DUAL: Next: ORA-01805: possible error in date/time operation", so I think it is a timezone info mismatch.
