### ISSUE TITLE
conversion from goracle.Number to bool

### ISSUE THREAD

**Issue by torwig** [go-goracle/goracle#159]
If I have the following code 

```go
type Source struct {
	ID     int
	Status bool
}

func main() {
	dsn := fmt.Sprintf("%s/%s@%s:%d/%s", dbUser, dbPassword, dbHost, dbPort, dbService)
	fmt.Printf("connecting to %s\n", dsn)

	db, err := sql.Open("goracle", dsn)
	if err != nil {
		fmt.Printf("unable to open database connection: %s\n", err)
		return
	}

	rows, err := db.Query("SELECT id, status FROM sources WHERE is_registered=1")
	if err != nil {
		fmt.Printf("failed to execute query: %s\n", err)
		return
	}

	for rows.Next() {
		var id int
		var status bool
		if err := rows.Scan(&id, &status); err != nil {
			fmt.Printf("failed to scan data: %s\n", err)
			return
		}
		fmt.Printf("Source id=%d, status=%t\n", id, status)
	}
}
```
I'll get an error 

> failed to scan data: sql: Scan error on column index 1, name "STATUS": sql/driver: couldn't convert 1 (goracle.Number) into type bool

The type of STATUS column is NUMBER.

If I make some changes in goracle source code (_rows.go, line 355_) and replace

```go
dest[i] = Number(C.GoStringN(b.ptr, C.int(b.length)))
```
with
```go
dest[i] = C.GoStringN(b.ptr, C.int(b.length))
```
the query will be executed and I'll see the result, for example,

> "Source id=181, status=true".

I'm sure there were reasons to introduce alias Number for string. 
I wonder if some logic could be added to goracle code for converting Number to bool in such cases?
Of course I looked at goracle codebase, but didn't find a place where this convertion should be done.
Perhaps there is a place where goracle can check the type of destination (bool in my case) and return bool instead of Number?

**Comment by tgulacsi** [comment]
I don't understand why would you Scan a NUMBER column into a bool, but anyway.
What about using the `goracle.MagicTypeConversion()` option?
If that does not work, you can try v2.16.0 with `goracle.NumberAsString()` option.
See TestNumberBool in `z_test.go`.
