### ISSUE TITLE
Float to int problem 

### ISSUE THREAD

**Issue by omerkirk** [go-goracle/goracle#16]
Hi Tamas,

I am testing goracle.v2 with one of our apps which used goracle.v1 previously. 
I get the following error when mapping a number column to an int field in a go struct. I am using sqlx for mappings. 

`sql: Scan error on column index 3: converting driver.Value type float64 ("2.934433e+06") to a int: invalid syntax`

I remember we worked on this very issue when you were developing goracle.v1 and somehow fixed it. When I tried updating to rana/ora I again had the same issue and you couldn't fix it there. Is it possible to fix this in goracle.v2 and can I be of any help?

**Comment by tgulacsi** [comment]
What is the exact column type? What is the dest value?
https://play.golang.org/p/DeGdqm38wa shows what is used in goracle.v2

**Comment by omerkirk** [comment]
I will prepare a test case and edit this comment tonight.

**Comment by tgulacsi** [comment]
Please see cab4ba5 and TestSelectFloat in z_test.go, and tweak it to your use case!

**Comment by omerkirk** [comment]
Hi,

I tried the commit it outputs the following for the same test case: 

```
newVar(typ=3003, natTyp=0, arraySize=128, bufSize=8454144): ORA-00000: DPI-1021: Oracle type 3003 is invalid
{IntColumn:0 FloatColumn:0 EmptyIntColumn:0}
```

I couldn't make sense of the error message.

**Comment by tgulacsi** [comment]
What is the code? What is the exact column type?
What does `go test -run=Float -v` print?
(set  `GORACLE_DRV_TEST_USERNAME`, `GORACLE_DRV_TEST_PASSWORD` and
`GORACLE_DRV_TEST_DB` env vars beforehand)

omerkirk <notifications@github.com> ezt írta (időpont: 2017. szept. 12., K,
11:14):

**Comment by omerkirk** [comment]
I reinstalled goracle.v2 and tried the test, it passed. Then retried my own test and other than the null column to int (which is the correct behaviour I think. As convenience I would rather have it mapped to a default destination value ie: string "", int 0, float 0.0) both floats and ints were mapped correctly. I think I did something wrong when updating package or maybe forgot to rebuild it. Sorry for that. I am closing the issue.

**Comment by omerkirk** [comment]
Hi Tamas,

One final question related to this issue. I need to fix the following error related to the driver upgrade:
`sql: Scan error on column index 4: unsupported Scan, storing driver.Value type <nil> into type *string]`

There are 2 ways of doing this currently either change the queries and NVL the possible NULL values, or change maps into sql.Nullables. Since I am upgrading the driver on a legacy application both these solutions are very complex. So I want to change the behaviour of the driver locally not to impact everyone. 

Can you lead me as to where in the code of goracle.v2 the mapping of values happen, so that I can tinker a bit with it?

Sorry for reopenning the issue, if you like I can close this and open a new one specific to mapping of null values.

**Comment by tgulacsi** [comment]
I couldn't made it better. See the current master (bbdf12f), z_test.go TestSelectFloat, and rows.go line 312.

The only solution I've found is to use sql.NullInt64 or sql.NullString.

I just cannot find where it decides that the column should be int64, and tries to Scan into it:
If I return Number(""), scanning into sql.NullInt64 fails...
If I return nil, scanning into *string fails...

**Comment by tgulacsi** [comment]
Before you give up: if we cannot find a general solution, we can make a specific one.
If you need a knob, we can add it.
To be specific: we can make a goracle.NullIsEmpty option which may be given as an argument just like goracle.PlSQLArrays Option. Or adding it through context.Context is possible, too.
And this option may dictate that a NULL number should be returned as an empty string (""), not as nil - so Scanning it into a string is possible.

**Comment by omerkirk** [comment]
Hi Tamas, 

I couldn't get your latest commit, I git pulled the origin master, and deleted goracle.v2 and "go get" it again. Both didn't work. 

In the meantime I think I found the code that did the conversion in goracle.v1 variable.go line 1245. I am not sure if it is any help at all. 

```
// check for a NULL value
	if v.typ.isNull != nil {
		isNull = v.typ.isNull(v, arrayPos)
	} else {
		isNull = v.indicator[arrayPos] == C.OCI_IND_NULL
	}
	if isNull {
		debug("getSingleValueInto NULL (dest=%T, pos=%d)", dest, arrayPos)

		var val reflect.Value
		switch v.typ {
		case DateTimeVarType:
			val = reflect.ValueOf(time.Time{})
		case IntervalVarType:
			val = reflect.ValueOf(time.Duration(0))
		case NumberAsStringVarType, LongIntegerVarType, Int64VarType, Int32VarType, FloatVarType, NativeFloatVarType:
			val = reflect.ValueOf(0)
		case BooleanVarType:
			val = reflect.ValueOf(false)
		default:
			val = reflect.ValueOf("")
		}
		//d.Elem().Set(reflect.Zero(d.Type()))
		d.Elem().Set(val.Convert(d.Elem().Type()))
		return nil
	}
```

**Comment by tgulacsi** [comment]
```bash
cd $GOPATH/src/gopkg.in/oracle.v2
git checkout -f master
git pull origin master
```

The problem is that the driver's rows.Next receives nil values, without type info (https://github.com/golang/go/blob/master/src/database/sql/sql.go#L2457), so I don't know how to decide what shall I return: "" or nil.

**Comment by omerkirk** [comment]
Hi Tamas,

After some logging and looking at ODPI code I found the column Native type for the null values in my query is set as DPI_NATIVE_TYPE_BYTES which is not in the isNull case in goracle.v2 code. After I added to the cases everything worked, but I am not really sure what I changed doesn't have any side effects or even if it is the correct behaviour.  The change is in rows.go Next function, looping over the columns to get the value. What do you think about this?

```
for i, col := range r.columns {
		typ := col.OracleType
		d := &r.data[i][r.bufferRowIndex]
		Log("msg", "Next", "i", i, "row", r.bufferRowIndex, "data", fmt.Sprintf("%+v", d), "typ", typ)
		isNull := d.isNull == 1

		switch typ {
		case C.DPI_ORACLE_TYPE_VARCHAR, C.DPI_ORACLE_TYPE_NVARCHAR,
			C.DPI_ORACLE_TYPE_CHAR, C.DPI_ORACLE_TYPE_NCHAR,
			C.DPI_ORACLE_TYPE_LONG_VARCHAR,
			C.DPI_NATIVE_TYPE_BYTES:
			//fmt.Printf("CHAR\n")
			if isNull {
				dest[i] = ""
				continue
			}
			b := C.dpiData_getBytes(d)
			dest[i] = C.GoStringN(b.ptr, C.int(b.length))

		case C.DPI_ORACLE_TYPE_NUMBER:
			if isNull {
				switch col.NativeType {
				case C.DPI_NATIVE_TYPE_INT64, C.DPI_NATIVE_TYPE_UINT64,
					C.DPI_NATIVE_TYPE_FLOAT, C.DPI_NATIVE_TYPE_DOUBLE,
					C.DPI_NATIVE_TYPE_BYTES:
```

**Comment by tgulacsi** [comment]
https://github.com/go-goracle/goracle/blob/master/stmt.go#L964 tweaks the registered column type to DPI_NATIVE_BYTES, to not loose precision.

https://github.com/go-goracle/goracle/blob/master/rows.go#L313 sets the returned data if we have a NUMBER, and BYTES is used to be returned from the database.
Here we have to decide what to give back: nil or "".

My problem is in the driver, we know _nothing_ about what the user wants to Scan into - only what we got from the database.

**Comment by tgulacsi** [comment]
@kardianos, can you chime in and help us?

**Comment by omerkirk** [comment]
The optimal solution would be to override rows.Scan in someway such that if the destination   is not one of the sql.Nullables we could assign sane defaults.

Or a more specific approach might be to define driver types for each value that knows it's type and whether if it is null or not and implement the Scanner interface for each type.

**Comment by kardianos** [comment]
I'm having a little trouble following this conversation. It there is trouble getting the value back from the database (from Scan) into the correct format. If so, is the user able to implement a custom sql.Scanner type? https://godoc.org/database/sql#Scanner

**Comment by tgulacsi** [comment]
The user wants to not change his program, and user *string to retrieve a number from the db.
The problem arises when the db wants to return a NULL: if it returns nil, the user gets `unsupported Scan, storing driver.Value type <nil> into type *string` error message.

I  can change the driver to return an empty string for NULL number, but that fails for sql.NullInt64, which wants nil as Null...

Do you know any possibility of the driver "knowing" what the database/sql layer wants from her?

**Comment by kardianos** [comment]
Nothing right now.

However, care to propose something? We are still at the top of the merge window, so if we get a proposal in now and implement it in the next few weeks, we could get it in go1.10.

There is a way for the driver to work on the values coming into it now. I could imagine it may be nice for a driver to implement a way to work on values going out of it while knowing about the driver values. It might also be justified by not requiring a slice boxing and boxing by the sql package.

Thoughts?

**Comment by tgulacsi** [comment]
Now rowsi.Query gets `make([]driver.Value, len(rowsi.Columns()))`, so empty
(nil) slices.
The args given to Scan would help.

Or if database/sql would use ColumnTypeScanType (and implement some sane
conversion routines), that would help.

Daniel Theophanes <notifications@github.com> ezt írta (időpont: 2017.
szept. 14., Cs, 15:31):
