### ISSUE TITLE
How should I use goracle to receive a strong ref cursor?

### ISSUE THREAD

**Issue by a1324321** [go-goracle/goracle#160]
The pack function is like this, and the type is strong ref cursor:
![image](https://user-images.githubusercontent.com/5265881/58085356-28000180-7bef-11e9-9531-687abab6f845.png)
![image](https://user-images.githubusercontent.com/5265881/58085586-980e8780-7bef-11e9-95a3-8a2c549aedcf.png)

but "database/sql" cant't receive this
![image](https://user-images.githubusercontent.com/5265881/58085454-5978cd00-7bef-11e9-9147-e8396a05b113.png)
How should I use goracle to receive this?

**Comment by tgulacsi** [comment]
You can receive into a database/sql/driver.Rows, and for ease, goracle.WrapRows.

**Comment by a1324321** [comment]
I mean, I have received this in the variable of row, but how can I get the result out ,so that I can use the data

**Comment by tgulacsi** [comment]
You have to experiment a little bit. Either
```
rows, err := db.Query("SELECT PACK1.F2('aa', 'aa') FORM DUAL")
if err...
rows.Next()
var rows2 sql.Rows
if err = rows.Scan(&rows2)...
for rows2.Next() {
  if rows2.Scan(...
```
or 
```
rows, err := db.Query("SELECT PACK1.F2('aa', 'aa') FORM DUAL")
if err...
rows.Next()
var rows2drv driver.Rows
if err = rows.Scan(&rows2drv)...
// convert driver.Rows to sql.Rows
rows2, err := goracle.WrapRows(ctx, db, rows2drv)
// use rows2
for rows2.Next() {
  if rows2.Scan(...
```

**Comment by a1324321** [comment]
seens it works, thank you!
