### ISSUE TITLE
Can goracle receive collections ?

### ISSUE THREAD

**Issue by a1324321** [go-goracle/goracle#162]
the sql is like this:
rows, err := db.Query("SELECT PK1.Get_F1('aaa','bbb') FROM DUAL")
and the package function's return type is use "as table of " :
CREATE OR REPLACE TYPE PK1.TABLE1 AS TABLE OF OBJECT_TYPE1

CREATE OR REPLACE
TYPE OBJECT_TYPE1 AS OBJECT
(
   JG        NUMBER(2), 
   DJMC      NUMBER(13,2),
   BB        NUMBER(13,2),
   CC        varchar2(100)
)

![image](https://user-images.githubusercontent.com/5265881/58296385-0dec3c00-7e06-11e9-8e35-82fcc9d2600c.png)
and I use goracle ,the return struct is like this:
![image](https://user-images.githubusercontent.com/5265881/58296549-b8fcf580-7e06-11e9-9c57-0a646e18f12c.png)
![image](https://user-images.githubusercontent.com/5265881/58296563-c74b1180-7e06-11e9-8dc1-fcd98f637c07.png)
![image](https://user-images.githubusercontent.com/5265881/58296621-fbbecd80-7e06-11e9-9710-19f0b892e02f.png)
How can I get this DJMC's data and convert to string?
I know actually Java can do this, but golang is still can't?

**Comment by tgulacsi** [comment]
In theory yes - you can .Scan the object into an interface{}, convert it into a goracle.Object, and work on that - as the dump says, the info is there, you just have to follow the path.

If you assemble a simple test case here (create the table, populate with data (use PL/SQL), create the stored proc, SELECT the ref cursor, try to get the object...), I'll try to make it work.

**Comment by a1324321** [comment]
like this:
1. the object type
CREATE OR REPLACE
TYPE T_T AS OBJECT
(
   AA        NUMBER(2), 
   BB      NUMBER(13,2),
   CC        NUMBER(13,2),
   DD        NUMBER(13,2), 
   MSG       varchar2(100) 
)
2. the table of type
CREATE OR REPLACE TYPE "HYDB_USER"."T_TAB" AS TABLE of T_T;
3. package head
CREATE OR REPLACE 
PACKAGE "PACK3" AS
function FUNC_1(
    p1  in varchar2,
    p2  in varchar2
)
return T_TAB;
END;
4. package body
CREATE OR REPLACE
PACKAGE BODY "PACK3" AS
function FUNC_1(
    p1  in varchar2,
    p2  in varchar2
)
return T_TAB is
ret T_TAB:=T_TAB();
begin 

ret.extend;
ret(ret.count):= T_T(
  11,
  22,
  33,
  44,
  'success!');
ret.extend;
ret(ret.count):= T_T(
  55,
  66,
  77,
  88,
  'failed!');
return ret;
end FUNC_1;
END;
6. test sql
select PACK3.FUNC_1('aa','bb') from dual;

**Comment by tgulacsi** [comment]
See TestSelectObjectTable at the end of z_test.go
