### ISSUE TITLE
Statement.NumInput interface works different between rana and goracle.v2

### ISSUE THREAD

**Issue by omerkirk** [go-goracle/goracle#17]
Hi Tamas, 

I am trying both the rana/ora.v4 and goracle.v2 for the new driver in an app. There is an inconsistency between them that causes the following database/sql error:

`sql: statement expects 1 inputs; got 6`

goracle.v2 counts the number of inputs as 6 although the query only has 1 bind parameter used in 6 different places.

rana/ora.v4 on the other hand gives me the more expected result of 1. The problem with this inconsistency is the intermediate library sqlx that I use as an lighweight ORM layer, counts the number of params as 6 also disregarding that the param names are duplicates.

I am not really sure which one is the more correct way of counting inputs but currently I changed the NumInput() function in rana/ora.v4 to disregard the duplicates and return the full number and filed a bug report in jmoiron/sqlx. 

Is this a bug in goracle.v2 or simply a choice of the driver. 

EDIT:

I found something that might be of help in the ODPI release notes. The function goracle.v2 uses to count bind variables has different results based on the parsed text being PL/SQL or SQL. Is it possible to use :func:`dpiStmt_getBindNames() instead to get the "correct" number of bound variables? I would be glad to submit a PR if you like.

You can find the related section in the ODPI release notes below: 

`Corrected determination of unique bind variable names. The function :func:`dpiStmt_getBindCount()` returns a count of unique bind variable names for PL/SQL statements only. For SQL statements, this count is the total number of bind variables, including duplicates. The function :func:`dpiStmt_getBindNames()` has been adjusted to return the actual number of unique bind variable names (parameter numBindNames is now a pointer instead of a scalar value).`

**Comment by hionay** [comment]
Hello Tamás,

When do you plan to finish named parameters? We have a project that uses rana/ora.v4 and it has a lot of INSERT statements which has named parameters at all.
