### ISSUE TITLE
goracle go build on windows occur undefined: ConnectionParams

### ISSUE THREAD

**Issue by goheader** [go-goracle/goracle#171]
**Describe the bug**
set GOARCH=amd64
set GOOS=linux
go build

# gopkg.in/goracle.v2
..\..\..\go\src\gopkg.in\goracle.v2\drv_10.go:32:2: undefined: ConnectionParams
..\..\..\go\src\gopkg.in\goracle.v2\drv_10.go:33:2: undefined: drv

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/51585789/59177379-7ec57f00-8b8e-11e9-8944-3414ff27858c.png)
![image](https://user-images.githubusercontent.com/51585789/59177393-900e8b80-8b8e-11e9-9051-de1a938a17e3.png)

**Your oracle client version**
e.g. 12.2.0.1.0

**Your goracle version**
e.g. 2.16.3

**Your go version**
go version is 1.11

**Your gcc version**
e.g. 8.1.0(x86_64-posix-seh-rev0, Built by MinGW-W64 project)

**Machine (please complete the following information):**
 - OS: [e.g. win]
 - Architecture [e.g. x86_64]
 - Version: [e.g. 10]

**Additional context**

**Comment by goheader** [comment]
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\goheader\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\private\goheader\gowork\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\GUIJIN~1\AppData\Local\Temp\go-build513965742=/tmp/go-build -gno-record-gcc-switches

**Comment by mrfoe7** [comment]
@goheader I think it is not correct compile in widows to linux.

**Comment by goheader** [comment]
> @goheader I think it is not correct compile in widows to linux.

yep, maybe I need install cgo to compile

**Comment by mrfoe7** [comment]
@goheader  i recommended use docker and linux container with gcc, oracle client and goracle for compile but not to try build into windows os

**Comment by tgulacsi** [comment]
With Docker, karalabe/xgo can help in cross-compilation.

**Comment by fabulias** [comment]
> With Docker, karalabe/xgo can help in cross-compilation.

can you provide more information about that?

**Comment by mrfoe7** [comment]
@fabulias Hi. I don't understand your question.
What do you want? If you have some exact question about goracle and cross-compilation in docker, please ask again.
Full information about cross-compilation you will can find into [karalabe/xgo](https://github.com/karalabe/xgo) documentation.

**Comment by fabulias** [comment]
> @fabulias Hi. I don't understand your question.
> What do you want? If you have some exact question about goracle and cross-compilation in docker, please ask again.
> Full information about cross-compilation you will can find into [karalabe/xgo](https://github.com/karalabe/xgo) documentation.

okay, thanks! I'll try.
