### ISSUE TITLE
got error ora-24496 when tried to connect oracle database

### ISSUE THREAD

**Issue by sontaya1988** [go-goracle/goracle#178]
func initDB() {
	params := goracle.ConnectionParams{
		Username:      "some_username",
		Password:      "some_password",
		SID:           "host:port/db",
		MinSessions:   10,
		MaxSessions:   10,
		PoolIncrement: 0,
		ConnClass:     "POCGORACLE",
	}

	var err error
	db, err = sql.Open("goracle", params.StringWithPassword())
	if err != nil {
		log.Fatal(err)
	}

	db.SetMaxIdleConns(10)
	db.SetMaxOpenConns(10)
}

**Comment by sontaya1988** [comment]
Go version 1.12.5

Goracle driver 2.16.3

oracle database 12.2.0.1 RAC

**Comment by tgulacsi** [comment]
What if you se PoolIncrement to 1?

**Comment by sontaya1988** [comment]
I tried to edit increment to 1 and delete setmaxconn parameter
some connection i got new error is acquirePoolConnection: ORA-24399: invalid number of connections specified

**Comment by tgulacsi** [comment]
Then don't set them...




On Tue, Jun 18, 2019 at 12:41 PM +0200, "sontaya1988" <notifications@github.com> wrote:












I tried to edit increment to 1 and delete setmaxconn parameter

some connection i got new error is acquirePoolConnection: ORA-24399: invalid number of connections specified

**Comment by sontaya1988** [comment]
currently my config is
minsession 10
maxsession 10
increment 1
maxidleconn 10
maxopencon 10
I still got same error some connection "ORA-24399"

**Comment by tgulacsi** [comment]
What's the matter with 
```
params := goracle.ConnectionParams{
Username: "some_username",
Password: "some_password",
SID: "host:port/db",
ConnClass: "POCGORACLE",
}```

?

**Comment by sontaya1988** [comment]
params := goracle.ConnectionParams{ 
Username: "system", 
Password: "welcome1", 
SID: "nxt-scan:1521/vendor", 
ConnClass: "POCGORACLE",
 }

**Comment by tgulacsi** [comment]
So, has this been solved?

**Comment by ppontryagin** [comment]
Hi, I have the same problem on Mac.
Windows works perfectly. 

acquirePoolConnection: ORA-24496: Message 24496 not found;  product=RDBMS; facility=ORA

goracle: v2.19.0

**Comment by tgulacsi** [comment]
" ORA-24496: OCISessionGet() timed out waiting for a free connection"

What about not messing with the timeouts, and simply providing the login, password, host, port an service name only?

**Comment by ppontryagin** [comment]
Hi, thank you for your answer.
I don't set timeouts. This is how I connect.


> con, err := sql.Open(s.Driver, user + "/" + pass + "@" + host + ":" + port + "/" + db)
con.SetMaxOpenConns(50)
con.SetMaxIdleConns(10)

**Comment by tgulacsi** [comment]
Ok, sorry.

"Message 24496 not found" means your Oracle (Instant Client) installation is incomplete - either it misses the message files, or just cannot find them.

Anyway, ORA-24496 means the connection timed out waiting for a free connection - is it on the first execution? 
If yes, then maybe something occupies all the available sessions; if it is not, then maybe you does not close each Rows and Stmt and Conn, and it eats all the available sessions.

**Comment by ppontryagin** [comment]
Hi, it happens during on first execution.
What is a bit confusing is that it happens only on OSX. Windows 10 works perfectly.
I will check Instant Client Installation.
Thank you very much.
