### ISSUE TITLE
unknown type *time.Time

### ISSUE THREAD

**Issue by leocomelli** [go-goracle/goracle#18]
I'm testing goracle.v2 on a [gorm](https://github.com/jinzhu/gorm) branch to support Oracle. I've gotten the following error when executing a query (insert and update) that uses a pointer argument. For example:

```
t := time.Now()
rows, err := sql.DB.Query("SELECT * FROM animals WHERE updated_at=?", &t)
```
**Error:**   `1. arg: unknown type *time.Time`

The goracle.v2 return this error for all pointer types ...

```
s := "dog"
rows, err := db.DB().Query("SELECT * FROM animals WHERE name=?", &s)
```
**Error:**   `1. arg: unknown type *string`

The [bindVars](https://github.com/go-goracle/goracle/blob/014d29f8bd4c71770e82b99a322e2d2242a70529/stmt.go#L300) method checks only the "concrete" types, right?

**Comment by tgulacsi** [comment]
Yes. It could dereference the pointer types, but it seemed unneeded
complexity for the first round.

Leonardo Comelli <notifications@github.com> ezt írta (időpont: 2017. szept.
8., P, 19:29):

**Comment by rbastic** [comment]
Hi,

Just want to jump in here -- I love the work you've been doing on rana/ora.v4 and this package. I've been trying to get rana/ora.v4 to stop crashing my microservice for my company's products. Also been trying to reliably reproduce and debug the crashes before I waste your time with a full report. 

The next step, however, that we're trying is to switch it to goracle. Thought you should at least know, *int64 and other pointer types are indeed quite useful (we see "unknown type: *int64") and at least for my / my company's purposes, seem to be necessary.

Cheers,

**Comment by tgulacsi** [comment]
Why do you use a pointer as an argument? 
What's the intended outcome?

I'm asking this because though befoure Go 1.9 you could cheat Exec/Query with pointer args to have some output, but with Go 1.9, you have a blessed method for this: use sql.Out.

**Comment by rbastic** [comment]
Well, it is more about having dynamic input type arguments, because potential code paths are not static and values are known ahead of time. It is not clear to me that sql.Out fixes that necessity. It looks like more of a dynamic output mechanism.

Is there a reason why supporting both is not a good idea?
