### ISSUE TITLE
wrap oracle types

### ISSUE THREAD

**Issue by elnando** [go-goracle/goracle#180]
Could be possible to wrap the oracle types as part of the goracle package? so that we do not reference them by their number neither its C.DPI_ORACLE_TYPE_..., but something like:
goracle.DPI_ORACLE_TYPE_...?

Thank you

**Comment by tgulacsi** [comment]
Yes, but what for? The users of goracle does not meet with such constants AFAIK.

**Comment by elnando** [comment]
DescribeQuery returns []QueryColumn which contains Type of int which could be required if you need to play with dynamic queries.

**Comment by tgulacsi** [comment]
DescribeQuery is a hack from before Rows.ColumnTypes.

**Comment by elnando** [comment]
Thanks
