### ISSUE TITLE
go get goracle.v2 error

### ISSUE THREAD

**Issue by vlkalashnikov91** [go-goracle/goracle#181]
**Describe the bug**
..\..\gopkg.in\goracle.v2\drv_10.go:32:2: undefined: ConnectionParams
..\..\gopkg.in\goracle.v2\drv_10.go:33:2: undefined: drv

**Your oracle client version**
12.2.0

**Your go version**
e.g. 1.12.0

**Your gcc version**
gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Machine (please complete the following information):**
Win 10 x64

**Comment by tgulacsi** [comment]
Sorry, that's not enough information - this error usually means the C (header) files are not found.
Did you vendor goracle.v2? If yes, please include the "odpi" directory, too.
If not, please run yout build/install with "-x" and post here the full output!

**Comment by vlkalashnikov91** [comment]
This error occurs when calling the command "go get -u gopkg.in/goracle.v2"

**Comment by tgulacsi** [comment]
What does `go get -x -v -u gopkg.in/goracle.v2` print?

**Comment by andreaneri** [comment]
Describe the bug
Step 5/5 : RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o /main .
 ---> Running in 4a0718230d36
# gopkg.in/goracle.v2
/go/pkg/mod/gopkg.in/goracle.v2@v2.20.1/drv_10.go:32:2: undefined: ConnectionParams
/go/pkg/mod/gopkg.in/goracle.v2@v2.20.1/drv_10.go:33:2: undefined: drv
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o /main .' returned a non-zero code: 2

Your oracle client version
12.2.0

Your go version
go version go1.13.1 linux/amd64

Your gcc version
gcc version 8.3.0 (Debian 8.3.0-6)

Machine (please complete the following information):
Linux 629b888be370 4.14.104-boot2docker #1 SMP Thu Feb 28 20:58:57 UTC 2019 x86_64 GNU/Linux

if i run:
go get -x -v -u gopkg.in/goracle.v2

command complete successfully, and:
ls -lrt pkg/linux_amd64/gopkg.in/
total 5412
-rw-r--r-- 1 root root 5538752 Oct 14 09:00 goracle.v2.a

**Comment by tgulacsi** [comment]
Cgo is required.




On Mon, Oct 14, 2019 at 11:19 AM +0200, "andreaneri" <notifications@github.com> wrote:












Describe the bug

Step 5/5 : RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o /main .

---> Running in 4a0718230d36
gopkg.in/goracle.v2


/go/pkg/mod/gopkg.in/goracle.v2@v2.20.1/drv_10.go:32:2: undefined: ConnectionParams

/go/pkg/mod/gopkg.in/goracle.v2@v2.20.1/drv_10.go:33:2: undefined: drv

The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o /main .' returned a non-zero code: 2


Your oracle client version

12.2.0


Your go version

go version go1.13.1 linux/amd64


Your gcc version

gcc version 8.3.0 (Debian 8.3.0-6)


Machine (please complete the following information):

Linux 629b888be370 4.14.104-boot2docker #1 SMP Thu Feb 28 20:58:57 UTC 2019 x86_64 GNU/Linux


if i run:

go get -x -v -u gopkg.in/goracle.v2


command complete successfully, and:

ls -lrt pkg/linux_amd64/gopkg.in/

total 5412

-rw-r--r-- 1 root root 5538752 Oct 14 09:00 goracle.v2.a

**Comment by andreaneri** [comment]
@tgulacsi thanks

**Comment by andreaneri** [comment]
@tgulacsi sorry sir, what's the smallest image to run a golang oracle client ? thanks

**Comment by tgulacsi** [comment]
Sorry, I don't understand your question.


What kind of image?


Some Oracle libs are required (for example Oracle Instant Client), but besides that, only your binary is needed.




On Mon, Oct 14, 2019 at 3:26 PM +0200, "andreaneri" <notifications@github.com> wrote:












@tgulacsi sorry sir, what's the smallest image to run a golang oracle client ? thanks

**Comment by andreaneri** [comment]
@tgulacsi i'm sorry, i think this question is really off-topic, i mean Docker image, i'm trying to run a golang Oracle client inside a small image (like Alpine), thanks

**Comment by cjbj** [comment]
@andreaneri you don't want Alpine.  I had some comments at https://stackoverflow.com/questions/53263972/oracle-on-alpine-linux/53291026#53291026
