### ISSUE TITLE
[Question] How to receive an out clob parameter from package procedure

### ISSUE THREAD

**Issue by dariocf1** [go-goracle/goracle#182]
My project uses a couple oracle packages to centralize all business logic, but I need to return as an output parameter from a procedure a clob variable, but I receive the error:  dpiStmt_execute(mode=32 arrLen=-1): ORA-22835: Buffer too small for CLOB to CHAR or BLOB to RAW conversion (real: 12931, maximum: 4000)

        var pOut string
         _, err := db.ExecContext(ctx, 'call dbs.get_input_service(:usrToken, :psrvId, :pOut)',
		sql.Named("usrToken",userToken),
		sql.Named("psrvId",srvId),
		sql.Named("pOut", sql.Out{Dest: &pOut}))

How can use clob datatype as output parameter?

Thank you

**Comment by tgulacsi** [comment]
By default, LOBs are read an retreieved as []byte / string for Query statements.
In Exec, you provide the destination - here a string.
Oracle cannot do that for long strings, you have to use a goracle.Lob - see TestLOBAppend in `z_lob_test.go`.
