### ISSUE TITLE
Support remote static listening connection to start database

### ISSUE THREAD

**Issue by travelliu** [go-goracle/goracle#187]
Under the database with static registration configured, remote connection data is not supported for starting the database.

**Comment by tgulacsi** [comment]
I understand the "database" word in that sentence. What do you want? How is it solved with ither languages? OCI, Pro*C, Java?

**Comment by travelliu** [comment]
The remote oracle database is shutdown,I want to use a remote connection to open. I used sqlplus startup database before.

**Comment by tgulacsi** [comment]
See https://godoc.org/gopkg.in/goracle.v2#Conn - if you get a goracle.Conn (for example with goracle.DriverConn(*sql.Conn)), then you can call the Startup method on it.

**Comment by travelliu** [comment]
I use the code below.  The remote database is shutdown 
`func exampleStartup(startupMode goracle.StartupMode) error {
	dsn := "oracle://sys:oracle@//192.168.56.65:1522/orcldg?&sysdba=1&sysoper=0&sysasm=0&standaloneConnection=1&enableEvents=1&heterogeneousPool=0&prelim=0&poolWaitTimeout=0&poolSessionMaxLifetime=0&poolSessionTimeout=0"
	db, err := sql.Open("goracle", dsn)
	if err != nil {
		log.Fatal(errors.Wrap(err, dsn))
	}
	defer db.Close()
	
	oraDB, err := goracle.DriverConn(db)
	if err != nil {
		return err
	}
	log.Println("Starting database")
	if err = oraDB.Startup(startupMode); err != nil {
		return err
	}
	// You cannot alter database on the prelim_auth connection.
	// So open a new connection and complete startup, as Startup starts pmon.
	db2, err := sql.Open("goracle", "oracle://?sysdba=1")
	if err != nil {
		return err
	}
	defer db2.Close()
	
	log.Println("Mounting database")
	if _, err = db2.Exec("alter database mount"); err != nil {
		return err
	}
	log.Println("Opening database")
	if _, err = db2.Exec("alter database open"); err != nil {
		return err
	}
	return nil
}
`

**Comment by travelliu** [comment]
I am using the code below. The remote database is closed
```
func exampleStartup(startupMode goracle.StartupMode) error {
	dsn := "oracle://sys:oracle@//192.168.56.65:1522/orcldg?&sysdba=1&sysoper=0&sysasm=0&standaloneConnection=1&enableEvents=1&heterogeneousPool=0&prelim=0&poolWaitTimeout=0&poolSessionMaxLifetime=0&poolSessionTimeout=0"
	db, err := sql.Open("goracle", dsn)
	if err != nil {
		log.Fatal(errors.Wrap(err, dsn))
	}
	defer db.Close()
	
	oraDB, err := goracle.DriverConn(db)
	if err != nil {
		return err
	}
	log.Println("Starting database")
	if err = oraDB.Startup(startupMode); err != nil {
		return err
	}
	// You cannot alter database on the prelim_auth connection.
	// So open a new connection and complete startup, as Startup starts pmon.
	db2, err := sql.Open("goracle", dsn)
	if err != nil {
		return err
	}
	defer db2.Close()
	
	log.Println("Mounting database")
	if _, err = db2.Exec("alter database mount"); err != nil {
		return err
	}
	log.Println("Opening database")
	if _, err = db2.Exec("alter database open"); err != nil {
		return err
	}
	return nil
}
```

**Comment by tgulacsi** [comment]
And, what is the error? 






On Thu, Aug 15, 2019 at 8:43 AM +0200, "Travel.Liu" <notifications@github.com> wrote:












I am using the code below. The remote database is closed
func exampleStartup(startupMode goracle.StartupMode) error {
	dsn := "oracle://sys:oracle@//192.168.56.65:1522/orcldg?&sysdba=1&sysoper=0&sysasm=0&standaloneConnection=1&enableEvents=1&heterogeneousPool=0&prelim=0&poolWaitTimeout=0&poolSessionMaxLifetime=0&poolSessionTimeout=0"
	db, err := sql.Open("goracle", dsn)
	if err != nil {
		log.Fatal(errors.Wrap(err, dsn))
	}
	defer db.Close()
	
	oraDB, err := goracle.DriverConn(db)
	if err != nil {
		return err
	}
	log.Println("Starting database")
	if err = oraDB.Startup(startupMode); err != nil {
		return err
	}
	// You cannot alter database on the prelim_auth connection.
	// So open a new connection and complete startup, as Startup starts pmon.
	db2, err := sql.Open("goracle", dsn)
	if err != nil {
		return err
	}
	defer db2.Close()
	
	log.Println("Mounting database")
	if _, err = db2.Exec("alter database mount"); err != nil {
		return err
	}
	log.Println("Opening database")
	if _, err = db2.Exec("alter database open"); err != nil {
		return err
	}
	return nil
}

**Comment by travelliu** [comment]
I want to do a check to see if the oracle database on the server is started. If it is not started, connect to the database remotely via goracle and start the database. I refer to the example_shutdown_test.go in the code.
```
func exampleStartup(startupMode goracle.StartupMode) error {
	dsn := "oracle://sys:oracle@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.56.65)(PORT=1522)))(CONNECT_DATA=(SERVER=DEDICATED)(SID=orcl)))?sysdba=1&prelim=1"
	db, err := sql.Open("goracle", dsn)
	if err != nil {
		log.Fatal(errors.Wrap(err, dsn))
	}
	defer db.Close()
	
	oraDB, err := goracle.DriverConn(db)
	if err != nil {
		log.Error(err)
		return err
	}
	log.Println("Starting database")
	if err = oraDB.Startup(startupMode); err != nil {
		return err
	}
	// You cannot alter database on the prelim_auth connection.
	// So open a new connection and complete startup, as Startup starts pmon.
	dsn1 := "oracle://sys:oracle@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.56.65)(PORT=1522)))(CONNECT_DATA=(SERVER=DEDICATED)(SID=orcl)))?sysdba=1"
	db2, err := sql.Open("goracle", dsn1)
	if err != nil {
		return err
	}
	defer db2.Close()
	
	log.Println("Mounting database")
	if _, err = db2.Exec("alter database mount"); err != nil {
		return err
	}
	log.Println("Opening database")
	if _, err = db2.Exec("alter database open"); err != nil {
		return err
	}
	return nil
}
```
Starting the database encountered an error
```
getConnection: getServerVersion: ORA-01034: ORACLE not available
```
The error means the database is not started.

Use the sqlplus tool of the Oracle database to connect to the startup database remotely.
```
oracle@dbaas01a:/home/oracle $tnsping orcltest

TNS Ping Utility for Linux: Version 11.2.0.4.0 - Production on 15-AUG-2019 17:27:34

Copyright (c) 1997, 2013, Oracle.  All rights reserved.

Used parameter files:


Used TNSNAMES adapter to resolve the alias
Attempting to contact (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = dbaas01a)(PORT = 1522)) (CONNECT_DATA = (SERVER = DEDICATED) (SID = orcl))) 
OK (0 msec)
oracle@dbaas01a:/home/oracle $sqlplus sys/oracle@orcltest as sysdba

SQL*Plus: Release 11.2.0.4.0 Production on Thu Aug 15 17:27:48 2019

Copyright (c) 1982, 2013, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> startup
ORACLE instance started.

Total System Global Area 1252663296 bytes
Fixed Size                  2252824 bytes
Variable Size             503320552 bytes
Database Buffers          738197504 bytes
Redo Buffers                8892416 bytes
Database mounted.
Database opened.
SQL> 

```

**Comment by travelliu** [comment]
tks.The problem has been resolved ,But encountered panic in db2.Close()

```
goroutine 1 [syscall]:
runtime.cgocall(0x410a5d0, 0xc0000fdb00, 0xc0000fdb28)
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc0000fdad0 sp=0xc0000fda98 pc=0x40053fb
gitlab.enmotech.com/enmotech/oracmd/vendor/gopkg.in/goracle%2ev2._Cfunc_dpiConn_release(0x4704d20, 0x0)
        _cgo_gotypes.go:2149 +0x49 fp=0xc0000fdb00 sp=0xc0000fdad0 pc=0x40c91e9
gitlab.enmotech.com/enmotech/oracmd/vendor/gopkg.in/goracle%2ev2.(*conn).Close.func2(0x4704d20, 0x41a74e0)
        /Users/travel/Documents/Code/go/src/gitlab.enmotech.com/enmotech/oracmd/vendor/gopkg.in/goracle.v2/conn.go:160 +0x56 fp=0xc0000fdb38 sp=0xc0000fdb00 pc=0x40f1b16
gitlab.enmotech.com/enmotech/oracmd/vendor/gopkg.in/goracle%2ev2.(*conn).Close(0xc000128000, 0x0, 0x0)
        /Users/travel/Documents/Code/go/src/gitlab.enmotech.com/enmotech/oracmd/vendor/gopkg.in/goracle.v2/conn.go:160 +0x148 fp=0xc0000fdbd0 sp=0xc0000fdb38 pc=0x40cce68
database/sql.(*driverConn).finalClose.func2()
        /usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:521 +0x49 fp=0xc0000fdc08 sp=0xc0000fdbd0 pc=0x40b9969
database/sql.withLock(0x41c9ae0, 0xc00013a000, 0xc0000fdca0)
        /usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:3097 +0x63 fp=0xc0000fdc30 sp=0xc0000fdc08 pc=0x40b95e3
database/sql.(*driverConn).finalClose(0xc00013a000, 0xc0000b23a0, 0xc00013a020)
        /usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:519 +0x130 fp=0xc0000fdcc8 sp=0xc0000fdc30 pc=0x40b53f0
database/sql.finalCloser.finalClose-fm(0xc000122020, 0xc00008e240)
        /usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:565 +0x2f fp=0xc0000fdcf0 sp=0xc0000fdcc8 pc=0x40bb11f
database/sql.(*DB).Close(0xc000122000, 0x41ca9e0, 0xc0000a6000)
        /usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:778 +0x267 fp=0xc0000fddf0 sp=0xc0000fdcf0 pc=0x40b61a7
main.exampleStartup(0x0, 0x0, 0x0)
        /Users/travel/Documents/Code/go/src/gitlab.enmotech.com/enmotech/oracmd/test/testshutdown.go:62 +0x474 fp=0xc0000fdee8 sp=0xc0000fddf0 pc=0x4109b84
main.ExampleStartup()
        /Users/travel/Documents/Code/go/src/gitlab.enmotech.com/enmotech/oracmd/test/testshutdown.go:22 +0x29 fp=0xc0000fdf28 sp=0xc0000fdee8 pc=0x4109699
main.main()
        /Users/travel/Documents/Code/go/src/gitlab.enmotech.com/enmotech/oracmd/test/testshutdown.go:18 +0x11d fp=0xc0000fdf98 sp=0xc0000fdf28 pc=0x410964d
runtime.main()
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/proc.go:200 +0x20c fp=0xc0000fdfe0 sp=0xc0000fdf98 pc=0x402e17c
runtime.goexit()
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000fdfe8 sp=0xc0000fdfe0 pc=0x4057b71


```

**Comment by tgulacsi** [comment]
On Thu, Aug 15, 2019 at 10:12:09PM -0700, Travel.Liu wrote:
> tks.The problem has been resolved ,But encountered panic in db2.Close()
>
> ```
> goroutine 1 [syscall]:
> runtime.cgocall(0x410a5d0, 0xc0000fdb00, 0xc0000fdb28)
>         /usr/local/Cellar/go/1.12.7/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc0000fdad0 sp=0xc0000fda98 pc=0x40053fb
> gitlab.enmotech.com/enmotech/oracmd/vendor/gopkg.in/goracle%2ev2._Cfunc_dpiConn_release(0x4704d20, 0x0)
>         _cgo_gotypes.go:2149 +0x49 fp=0xc0000fdb00 sp=0xc0000fdad0 pc=0x40c91e9
> gitlab.enmotech.com/enmotech/oracmd/vendor/gopkg.in/goracle%2ev2.(*conn).Close.func2(0x4704d20, 0x41a74e0)
>         /Users/travel/Documents/Code/go/src/gitlab.enmotech.com/enmotech/oracmd/vendor/gopkg.in/goracle.v2/conn.go:160 +0x56 fp=0xc0000fdb38 sp=0xc0000fdb00 pc=0x40f1b16
> gitlab.enmotech.com/enmotech/oracmd/vendor/gopkg.in/goracle%2ev2.(*conn).Close(0xc000128000, 0x0, 0x0)
>         /Users/travel/Documents/Code/go/src/gitlab.enmotech.com/enmotech/oracmd/vendor/gopkg.in/goracle.v2/conn.go:160 +0x148 fp=0xc0000fdbd0 sp=0xc0000fdb38 pc=0x40cce68
> database/sql.(*driverConn).finalClose.func2()
>         /usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:521 +0x49 fp=0xc0000fdc08 sp=0xc0000fdbd0 pc=0x40b9969
> database/sql.withLock(0x41c9ae0, 0xc00013a000, 0xc0000fdca0)
>         /usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:3097 +0x63 fp=0xc0000fdc30 sp=0xc0000fdc08 pc=0x40b95e3
> database/sql.(*driverConn).finalClose(0xc00013a000, 0xc0000b23a0, 0xc00013a020)
>         /usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:519 +0x130 fp=0xc0000fdcc8 sp=0xc0000fdc30 pc=0x40b53f0
> database/sql.finalCloser.finalClose-fm(0xc000122020, 0xc00008e240)
>         /usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:565 +0x2f fp=0xc0000fdcf0 sp=0xc0000fdcc8 pc=0x40bb11f
> database/sql.(*DB).Close(0xc000122000, 0x41ca9e0, 0xc0000a6000)
>         /usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:778 +0x267 fp=0xc0000fddf0 sp=0xc0000fdcf0 pc=0x40b61a7
> main.exampleStartup(0x0, 0x0, 0x0)
>         /Users/travel/Documents/Code/go/src/gitlab.enmotech.com/enmotech/oracmd/test/testshutdown.go:62 +0x474 fp=0xc0000fdee8 sp=0xc0000fddf0 pc=0x4109b84
> main.ExampleStartup()
>         /Users/travel/Documents/Code/go/src/gitlab.enmotech.com/enmotech/oracmd/test/testshutdown.go:22 +0x29 fp=0xc0000fdf28 sp=0xc0000fdee8 pc=0x4109699
> main.main()
>         /Users/travel/Documents/Code/go/src/gitlab.enmotech.com/enmotech/oracmd/test/testshutdown.go:18 +0x11d fp=0xc0000fdf98 sp=0xc0000fdf28 pc=0x410964d
> runtime.main()
>         /usr/local/Cellar/go/1.12.7/libexec/src/runtime/proc.go:200 +0x20c fp=0xc0000fdfe0 sp=0xc0000fdf98 pc=0x402e17c
> runtime.goexit()
>         /usr/local/Cellar/go/1.12.7/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000fdfe8 sp=0xc0000fdfe0 pc=0x4057b71
>
>
> ```
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/go-goracle/goracle/issues/187#issuecomment-521886071

I don't know why is this panics.
Neither know how to distinguish this connection from any other
connection (to catch the panic selectively).
So, till we figure out what's happening (run your test with setting the
"DPI_DEBUG_LEVEL" environment variable to "28"),
recover from this panic.

Tamás Gulácsi
