### ISSUE TITLE
Just wanna say thanks!

### ISSUE THREAD

**Issue by rbastic** [go-goracle/goracle#19]
Switching from rana/ora.v4 to goracle and changing some of my private microservice's code fixed the crashes I was seeing. This seems great! Thanks again for making this.

**Comment by tgulacsi** [comment]
Great to hear, thanks!
But I have share on the gratitude with @anthony-tuininga, as ODPI-C's simplified interface hides a lot of traps of OCI, simplifying my code, too!

**Comment by rbastic** [comment]
Absolutely, ODPI-C is a huge winner. Still, without you doing the heavy lifting on Go's side, this wouldn't be done! I'm ecstatic to finally see my crash count dwindle to zero. Thanks again.

If I'm ever in the neighborhood, I owe you some pivo or drink of your choice :)
