### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by tim33333** [go-goracle/goracle#191]
**Describe the bug**
When I trying to build my app, I got an error 

# gopkg.in/goracle.v2
..\gopkg.in\goracle.v2\lob.go:196: cannot use typ (type C.uint) as type C.dpiOracleTypeNum in argument to func literal. 

**Screenshots**
196 line is 
![image](https://user-images.githubusercontent.com/54355788/63910137-eb8a4000-ca3e-11e9-9bdd-de6815447fee.png)

**Your oracle client version**
12.1.0

**Your goracle version**
last version

**Your go version**
go version go1.9.2 windows/amd64

**Your gcc version**
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

**Machine (please complete the following information):**
 - OS: Windows Home
 - Architecture x86_64
 - Version: 10

**Comment by tgulacsi** [comment]
As the readme says, Go 1.11 is required at least.




On Thu, Aug 29, 2019 at 6:34 AM +0200, "tim33333" <notifications@github.com> wrote:












Describe the bug

When I trying to build my app, I got an error
gopkg.in/goracle.v2


..\gopkg.in\goracle.v2\lob.go:196: cannot use typ (type C.uint) as type C.dpiOracleTypeNum in argument to func literal.


Screenshots

196 line is




Your oracle client version

12.1.0


Your goracle version

last version


Your go version

go version go1.9.2 windows/amd64


Your gcc version

gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0


Machine (please complete the following information):

OS: Windows Home
Architecture x86_64
Version: 10

**Comment by tim33333** [comment]
After golang update to latest version problem solved. Thank you.
