### ISSUE TITLE
Not able to insert more than 9 columns 

### ISSUE THREAD

**Issue by singhnirmals** [go-goracle/goracle#198]
**Describe the bug**
I am not able to insert more than 9 columns using EXEC, Query or either Prepare statement. It does work for 9 columns, once i add next column it does not insert and does nothing, not even throw any error.

**To Reproduce**
stmt, err := OracleDB.Prepare("INSERT INTO ETECDBA.IVR_COMMANDTABLE (RECORDKEY, AGENCYDESIGNATOR, PAYMENTAMOUNT, CREDITORDEBITCARDTYPE, CREDITORDEBITCARDNUMBER, CREDITORDEBITCARDAUTHNUM, VENDORID, VENDORTRANSACTIONNUMBER, COMMANDNUMBER, CREDITORDEBITCARDEXPIRYDATE) VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10)") 
		if err != nil { 
			fmt.Println(".....Error Inserting data - first statement") 
			fmt.Println(err) 
		}
		res, err := stmt.Query(ivrcommandData[index].RECORDKEY, ivrcommandData[index].AGENCYDESIGNATOR, ivrcommandData[index].PAYMENTAMOUNT, ivrcommandData[index].CREDITORDEBITCARDTYPE, ivrcommandData[index].CREDITORDEBITCARDNUMBER, ivrcommandData[index].CREDITORDEBITCARDAUTHNUM, ivrcommandData[index].VENDORID, vendorId, ivrcommandData[index].COMMANDNUMBER,"0721")  
		if err != nil {
			log.Println("Error occurred while excuting Inserting")
			fmt.Println(err) 
}

**Expected behavior**
It does not throw any error

**Screenshots**

**Your oracle client version**
19.3.0.0

**Your goracle version**
v2.21.4

**Your go version**
1.13

**Your gcc version**

**Machine (please complete the following information):**
 - OS: [e.g. win]: Linux
 - Architecture [e.g. x86_64]: 64
 - Version: [e.g. 10]

**Additional context**

**Comment by tgulacsi** [comment]
Query is only for SELECT statements.
Everything else (including INSERT) needs Exec.

**Comment by singhnirmals** [comment]
I tried with EXEC for 10 columns, it didn't work. Here is code snapshot:
_, err = OracleDB.Exec("INSERT INTO ETECDBA.IVR_COMMANDTABLE (RECORDKEY,
AGENCYDESIGNATOR, PAYMENTAMOUNT, CREDITORDEBITCARDTYPE,
CREDITORDEBITCARDNUMBER, CREDITORDEBITCARDAUTHNUM, VENDORID,
VENDORTRANSACTIONNUMBER, COMMANDNUMBER,CREDITORDEBITCARDEXPIRYDATE) VALUES
(:1, :2, :3, :4, :5, :6, :7, :8, :9,:10)", ivrcommandData[index].RECORDKEY,
ivrcommandData[index].AGENCYDESIGNATOR, ivrcommandData[index].PAYMENTAMOUNT,
ivrcommandData[index].CREDITORDEBITCARDTYPE, ivrcommandData[index].
CREDITORDEBITCARDNUMBER, ivrcommandData[index].CREDITORDEBITCARDAUTHNUM,
ivrcommandData[index].VENDORID, vendorId, ivrcommandData[index].
COMMANDNUMBER,"0823")



It did work if i remove one column from query.

Thanks,
Nirmal

**Comment by tgulacsi** [comment]
Are you sure it's not that CREDITORDEBITCARDEXPIRYDATE should get a time.Time, or a TO_DATE with proper format?




Is it still work if you leave out some other field?




On Tue, Oct 15, 2019 at 1:36 PM +0200, "singhnirmals" <notifications@github.com> wrote:










I tried with EXEC for 10 columns, it didn't work. Here is code snapshot:


_, err = OracleDB.Exec("INSERT INTO ETECDBA.IVR_COMMANDTABLE (RECORDKEY,


AGENCYDESIGNATOR, PAYMENTAMOUNT, CREDITORDEBITCARDTYPE,


CREDITORDEBITCARDNUMBER, CREDITORDEBITCARDAUTHNUM, VENDORID,


VENDORTRANSACTIONNUMBER, COMMANDNUMBER,CREDITORDEBITCARDEXPIRYDATE) VALUES


(:1, :2, :3, :4, :5, :6, :7, :8, :9,:10)", ivrcommandData[index].RECORDKEY,


ivrcommandData[index].AGENCYDESIGNATOR, ivrcommandData[index].PAYMENTAMOUNT,


ivrcommandData[index].CREDITORDEBITCARDTYPE, ivrcommandData[index].


CREDITORDEBITCARDNUMBER, ivrcommandData[index].CREDITORDEBITCARDAUTHNUM,


ivrcommandData[index].VENDORID, vendorId, ivrcommandData[index].


COMMANDNUMBER,"0823")











It did work if i remove one column from query.





Thanks,


Nirmal








On Tue, Oct 15, 2019 at 12:20 AM Tamás Gulácsi <notifications@github.com>


wrote:

**Comment by singhnirmals** [comment]
It’s varchar.

**Comment by singhnirmals** [comment]
Yes, if I leave any other field and as long as columns does not exceed 9 it
works.

**Comment by singhnirmals** [comment]
Did you observe the same issue, when we try to insert 10 columns , record
is not getting inserted and no error or exception as well?

**Comment by singhnirmals** [comment]
Did you find any resolution to the issue with the insertion when columns are more than 9?

**Comment by tgulacsi** [comment]
It's not the number of columns - I have inserts with 15 columns. 




We need a small reproduction:


please copy here the create table and one insert with the concrete values that shows the erroneous behaviour.




(And be sure that you don't have triggers on that table, as those can play tricks with you!)






On Thu, Oct 17, 2019 at 1:39 PM +0200, "singhnirmals" <notifications@github.com> wrote:












Did you find any resolution to the issue with the insertion when columns are more than 9?

**Comment by singhnirmals** [comment]
Trigger is there on that table, is that something causes issue?

**Comment by tgulacsi** [comment]
Not usually, but can, sometimes.




On Thu, Oct 17, 2019 at 2:31 PM +0200, "singhnirmals" <notifications@github.com> wrote:










Trigger is there on that table, is that something causes issue?





On Thu, Oct 17, 2019 at 8:27 AM Tamás Gulácsi <notifications@github.com>


wrote:





> It's not the number of columns - I have inserts with 15 columns.


>


>


>


>


> We need a small reproduction:


>


>


> please copy here the create table and one insert with the concrete values


> that shows the erroneous behaviour.


>


>


>


>


> (And be sure that you don't have triggers on that table, as those can play


> tricks with you!)


>


>


>


>


>


>


> On Thu, Oct 17, 2019 at 1:39 PM +0200, "singhnirmals" <

**Comment by singhnirmals** [comment]
So what is the solution to make it work always if table has trigger?
Does it make sense to execute query using transaction?

**Comment by tgulacsi** [comment]
It can be executed in a transaction, but that won't disable the trigger.
The easiest test is to disable the trigger, run the INSERT, and see what has happened.
If the record has been created, then the trigger was the culprit, it has to be investigated.
If not, then the error is somewhere else.

In the latter case, please post here the CREATE TABLE of the table, an INSERT with concrete data, to be able to reproduce it.
