### ISSUE TITLE
cursor.ExecuteMany error when binding variables

### ISSUE THREAD

**Issue by omerkirk** [go-goracle/goracle#2]
Hi, 

I am trying to use the cursor.ExecuteMany function with an insert into statement. However I am getting a "Variable_SetSingleValue: array size exceeded" error.  
My code is like the following:
```
insertParams := make([]map[string]interface{}, len(imps))
for i, imp := range imps {
	insertParams[i] = map[string]interface{}{
		"impdate":   imp.CreDate,
		"userkey":   imp.UserKey,
		"ip":        imp.IP,
		"zoneid":    imp.ZoneID,
		"planid":    imp.PlanID,
		"bannerid":  imp.BannerID,
		"referrer":  imp.Referrer,
		"country":   imp.Country,
		"region":    imp.Region,
		"server":    bs.serverID,
		"ismerge":   imp.IsMergeExecute,
		"sessionid": imp.SessionID,
	}
}
err := session.ExecuteMany("INSERT INTO TBL_TEMP_IMPRESSION VALUES (:impdate,:userkey,:ip,:zoneid,:planid,:bannerid,:referrer,:country,:region,:server,:ismerge,:sessionid)", insertParams)
```

I tried to follow through the code and found a possible bug. And below is my findings. 

ExecuteMany calls setVariablesByName which in turn calls setBindVariableHelper. While initializing the bind variables NewVariableByValue is called. Up to this point the number of elements the execute many statement contains is passed along correctly.

However inside NewVariableByValue the number of elements is overridden by this piece of code. I am not familiar with cx_oracle myself so I cannot be sure if this is a bug or expected behavior.

```
oracle/variable.go lines 626 - 628
if varType, size, numElements, err = VarTypeByValue(value); err != nil {
		return
}
``` 
The VarTypeByValue function is not aware of numElements and thus returns 0 for types other than *oracle.Variable or oracle.Variable. In this case a new variable is created with allocatedelement count with 0. 

This in turn causes the following piece of code to return the error 
Variable_SetSingleValue: array size exceeded
```
oracle/variable.go lines 1315 - 1317 setSingleValue function

if arrayPos >= v.allocatedElements {
		return errgo.New("Variable_SetSingleValue: array size exceeded")
}
```

It seems to me that VarTypeByValue function has a different meaning for numElements. It treats that variable as the length of the value if it is an array value. However up until that point that variable's meaning is the length of the variables the execute many statement should bind.  It think this function should be somehow made aware of the numElements it is overriding or the returned value shouldn't override the numElements variable since they have completely different meanings. However since I am not familiar with the cx_oracle library I am not sure what kind of consequences that may have.

**Comment by tgulacsi** [comment]
Hi,

I've started looking into this, but stuck with "ORA-01458: invalid length inside variable character string" atm. See the ExecuteMany branch, if you have some free time!

**Comment by omerkirk** [comment]
Hi Tamas,

I will have some time tonight. I will check out the new branch. Where did
you get stuck with the ORA 1458 error, is it related to this issue or
something else.

**Comment by tgulacsi** [comment]
See TestTable in oracle/table_test.go
(In v1 it is skipped)

A big confusion came from the fact that OCI allows arrays only for PL/SQL
blocks, the ExecuteMany must use multiple binds - see
oracle/CX_oracle/Cursor.c
2015. máj. 2. 20:48 ezt írta ("omerkirk" <notifications@github.com>):

> Hi Tamas,
>
> I will have some time tonight. I will check out the new branch. Where did
> you get stuck with the ORA 1458 error, is it related to this issue or
> something else.
>

**Comment by tgulacsi** [comment]
I know too few about OCI, so I'm just printing out everything and turn knobs everywhere...

Even after cpmmenting out the "text" part in table_test.go insertArray, the same error remains - which is strange, as now there's nothing variable length bound here...

        tsthlp.go:52: t=2015-05-02T22:04:12+0200 lvl=dbug msg="CTRACE internalBind.OCIBindByName(cur=0x1c11108, bind=0xc2080d2280, env=0x1bf5c70, name=\"small\", bufferSize=22, oracleType=6, data[:22]=[2 193 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], indicator=[0 0 0], aL=<nil>, rC=<nil>, allElts=3, pActElts=0xc2080d22c0, DEFAULT)" lib=goracle stack="[debug_trace.go:31 variable.go:1016 variable.go:1140 cursor.go:883 cursor.go:1552 table_test.go:77 table_test.go:47]" caller=debug_trace.go:31
        tsthlp.go:52: t=2015-05-02T22:04:12+0200 lvl=dbug msg="CTRACE <goracle.Cursor 0x1c11108 on 0x1bf5b88>.internalExecute(3)" lib=goracle stack="[debug_trace.go:31 cursor.go:372 cursor.go:1559 table_test.go:77 table_test.go:47]" caller=debug_trace.go:31
        tsthlp.go:52: t=2015-05-02T22:04:12+0200 lvl=dbug msg="0xc208094000.StmtExecute(INSERT INTO tst_goracle_oracle (F_int) VALUES (:small), mode=0) in internalExecute" lib=goracle stack="[error.go:85 cursor.go:385 cursor.go:1559 table_test.go:77 table_test.go:47]" caller=error.go:85
        tsthlp.go:52: t=2015-05-02T22:04:12+0200 lvl=dbug msg="CTRACE internalExecute.OCIStmtExecute(conn=0x1bf5b88, cur=0x1c11108, env=0x1bf5c70, iters=3, rowOff=0, mode=0)" lib=goracle stack="[debug_trace.go:31 cursor.go:390 cursor.go:1559 table_test.go:77 table_test.go:47]" caller=debug_trace.go:31
        tsthlp.go:52: t=2015-05-02T22:04:12+0200 lvl=dbug msg="CTRACE getErrorOffset.OCIAttrGet(cur=0x1c11108, HTYPE_STMT, &offset=0xc208117af0, &x=0xc208117b00,ATTR_PARSE_ERROR_OFFSET, errhndl=0x1bf5c70)" lib=goracle stack="[debug_trace.go:31 cursor.go:350 cursor.go:364 cursor.go:399 cursor.go:1559 table_test.go:77 table_test.go:47]" caller=debug_trace.go:31
        table_test.go:78: ExecuteMany(3): @internalExecute 1458: [-1] ORA-01458: invalid length inside variable character string
                ORA-01458: invalid length inside variable character string

**Comment by omerkirk** [comment]
Same here no clue about OCI. I've been doing some reading on it. And looked through the code again. 

This error can be caused by an uninitialized bind variable, be it an integer or string. See here:
https://community.oracle.com/thread/296685
So I think the problem is in the dataBytes array in the variable that is created during ExecuteMany. 

I followed the code after your fix in the new branch. Now the allocatedElements is set correctly, and the code goes on to allocate the elements. Because Int64Type is of type SQLT_VNU (oracle varnum) the dataBytes array is created and allocated in ``` v.allocateData() ``` function. 

The size of VARNUM is 22 bytes see here: http://docs.oracle.com/cd/B14117_01/appdev.101/b10779/oci03typ.htm
And the number of parameters is 3, therefore the size of the databytes array as per the allocateData function, should be 66. However in the trace in your comment it looks like 22. The problem is I couldn't find anywhere the dataBytes array size changes in the code, and it is created correctly in the beginning. 

It may be that somewhere in the code while passing the dataBytes array through C and back using unsafe.Pointer there might be a very small bug, resetting it everytime. This is just a hunch for now, but the trace you posted is definitely alarming. I will try to look into it more tomorrow when I find the time. 

Hope that was helpful.

**Comment by tgulacsi** [comment]
Hi, please check ef4eb57 or 47f402b
