### ISSUE TITLE
Go lang support with Oracle Wallets

### ISSUE THREAD

**Issue by bharathhebbar** [go-goracle/goracle#201]
I am new to GO.

i wanted to know if goracle supports wallet based connection string.
In java, we do something like what is mentioned in the below link.
https://stackoverflow.com/questions/24160428/how-to-use-oracle-wallet

Having few libraries in classpath and connection script is based on a ALIAS.

But i did not get to understand how we can achieve something like that is GO. Help appreciated.

**Comment by tgulacsi** [comment]
Yes, as far as OCI supports it - you have to set TNS_ADMIN environment variable to the path where your tnsnames.ora, sqlnet.ora and wallets are located.

For example, see [contrib/goracle.db](/go-goracle/goracle/tree/master/contrib/goracle.db)
