### ISSUE TITLE
Build errors for Windows 64-bit

### ISSUE THREAD

**Issue by tredoe** [go-goracle/goracle#207]
**Describe the bug**
Can not compile a basic program:

```
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "gopkg.in/goracle.v2"
)

const (
	dbname = "XEPDB1"
	user   = "SYS"
	pass   = "***"
)

func main() {
	db, err := connectDB()
	if err != nil {
		log.Fatal("Connect Error:\n" + err.Error())
	}
	if err = db.Ping(); err != nil {
		log.Fatal("Ping Error:\n" + err.Error())
	}
	defer db.Close()
	fmt.Println("Connected: ok")
}

func connectDB() (*sql.DB, error) {
	driver := "goracle"
	connString := fmt.Sprintf("oracle://%s:%s@%s", user, pass, dbname)
	return sql.Open(driver, connString)
}
```

**To Reproduce**
1. go build test_oracle.go
2. See error:

```
# gopkg.in/goracle.v2
In file included from ..\..\..\go\pkg\mod\gopkg.in\goracle.v2@v2.22.4\odpi\embed/dpi.c:37:0,
                 from ..\..\..\go\pkg\mod\gopkg.in\goracle.v2@v2.22.4\drv.go:57:
..\..\..\go\pkg\mod\gopkg.in\goracle.v2@v2.22.4\odpi\embed/../src/dpiOci.c: In function 'dpiOci__getLoadErrorOnWindows':
..\..\..\go\pkg\mod\gopkg.in\goracle.v2@v2.22.4\odpi\embed/../src/dpiOci.c:1693:38: error: 'ERROR_MUI_FILE_NOT_FOUND' undeclared (first use in this function)
     if (!status && GetLastError() == ERROR_MUI_FILE_NOT_FOUND)
                                      ^
..\..\..\go\pkg\mod\gopkg.in\goracle.v2@v2.22.4\odpi\embed/../src/dpiOci.c:1693:38: note: each undeclared identifier is reported only once for each function it appears in
```

**Your oracle client version**
 Oracle Database 18c Express Edition Release 18.0.0.0.0

**Your goracle version**
v2.22.4

**Your go version**
go version go1.13.4 windows/amd64

**Your gcc version**
gcc --version
gcc (GCC) 4.8.3

**Machine (please complete the following information):**
 - OS: Windows
 - Architecture amd64
 - Version: 10

**Comment by tgulacsi** [comment]
Please report this on goracle/odpi !




On Wed, Nov 13, 2019 at 11:57 AM +0100, "Jonas mg" <notifications@github.com> wrote:












Describe the bug

Can not compile a basic program:
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "gopkg.in/goracle.v2"
)

const (
	dbname = "XEPDB1"
	user   = "SYS"
	pass   = "***"
)

func main() {
	db, err := connectDB()
	if err != nil {
		log.Fatal("Connect Error:
" + err.Error())
	}
	if err = db.Ping(); err != nil {
		log.Fatal("Ping Error:
" + err.Error())
	}
	defer db.Close()
	fmt.Println("Connected: ok")
}

func connectDB() (*sql.DB, error) {
	driver := "goracle"
	connString := fmt.Sprintf("oracle://%s:%s@%s", user, pass, dbname)
	return sql.Open(driver, connString)
}



To Reproduce

Steps to reproduce the behavior:

go build test_oracle.go
See error:

# gopkg.in/goracle.v2
In file included from ..\..\..\go\pkg\mod\gopkg.in\goracle.v2@v2.22.4\odpi\embed/dpi.c:37:0,
                 from ..\..\..\go\pkg\mod\gopkg.in\goracle.v2@v2.22.4\drv.go:57:
..\..\..\go\pkg\mod\gopkg.in\goracle.v2@v2.22.4\odpi\embed/../src/dpiOci.c: In function 'dpiOci__getLoadErrorOnWindows':
..\..\..\go\pkg\mod\gopkg.in\goracle.v2@v2.22.4\odpi\embed/../src/dpiOci.c:1693:38: error: 'ERROR_MUI_FILE_NOT_FOUND' undeclared (first use in this function)
     if (!status && GetLastError() == ERROR_MUI_FILE_NOT_FOUND)
                                      ^
..\..\..\go\pkg\mod\gopkg.in\goracle.v2@v2.22.4\odpi\embed/../src/dpiOci.c:1693:38: note: each undeclared identifier is reported only once for each function it appears in



Your oracle client version

Oracle Database 18c Express Edition Release 18.0.0.0.0


Your goracle version

v2.22.4


Your go version

go version go1.13.4 windows/amd64


Machine (please complete the following information):

OS: Windows
Architecture x86_64
Version: 10

**Comment by tredoe** [comment]
Do you mean 'https://github.com/oracle/odpi'?

**Comment by tredoe** [comment]
https://github.com/oracle/odpi/issues/119

**Comment by tgulacsi** [comment]
See  https://github.com/libuv/libuv/issues/153 use never MinGW

**Comment by tredoe** [comment]
Solved after of install the last version of MinGW-w64
