### ISSUE TITLE
Password included @,  unable to connect

### ISSUE THREAD

**Issue by kxjhlele** [go-goracle/goracle#21]
p, err := ora.ParseConnString("cc/\\\"c@c*1\\\"@//192.168.1.1/cc")
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(p.String())
	db, err := sql.Open("goracle", "cc/\\\"c@c*1\\\"@//192.168.1.1/cc")
	if err != nil {
		log.Fatalln(err)
	}
	defer db.Close()
	if err = db.Ping(); err != nil {
		log.Fatalln(err)
	}
	log.Println("connect ok")

unable to connect

**Comment by tgulacsi** [comment]
Try sql.Open("goracle", "oracle://cc:c@c*1:192.168.1.1%2Fcc/") - as godoc
says.
(I', not sure in 192.168.1.1%2Fcc - try 192.168.1.1/cc too)

kxjhlele <notifications@github.com> ezt írta (időpont: 2017. okt. 31., K,
10:51):

**Comment by kxjhlele** [comment]
not ok, 
May not recognize host，

**Comment by tgulacsi** [comment]
u := url.URL{
        Scheme: "oracle",
        User:   url.UserPassword("cc", "c@c*1"),
        Host:   "192.168.1.1/cc",
    }

use u.String()

kxjhlele <notifications@github.com> ezt írta (időpont: 2017. nov. 1., Sze,
10:00):

**Comment by kxjhlele** [comment]
no ok

u.String()  --  oracle://cc:c%40c%2A1@192.168.1.1%2Fcc

ora.ParseConnString(u.String()) -- oracle://:@/?connectionClass=GORACLE&poolIncrement=1&poolMaxSessions=1000&poolMinSessions=1&sysdba=0&sysoper=0

sql.Open("goracle", u.String())  -- parse oracle://cc:c%40c%2A1@192.168.1.1%2Fcc: invalid URL escape "%2F"

sql.Open("goracle", "oracle://cc:c%40c%2A1@192.168.1.1/cc")  -- ORA-01017: 用户名/口令无效; 登录被拒绝

sql.Open("goracle", "cc/c%40c%2A1@192.168.1.1/cc")  -- ORA-01017: 用户名/口令无效; 登录被拒绝

**Comment by tgulacsi** [comment]
Ok, you're right.
See v2.1.4 - I've exported ConnectionParams, so you can provide password as you wish:

    sql.Open("goracle", goracle.ConnectionParams{User:"cc", Password:"c@c*1", SID:"192.168.1.1/cc"}.String())

**Comment by kiemrong08** [comment]
Can you provide me some example using `ConnectionParams`
When i using 
```
sql.Open("goracle", goracle.ConnectionParams{User:"cc", Password:"c@c*1", SID:"192.168.1.1/cc"}.String())
```
Go say : `undefined: goracle`

**Comment by tgulacsi** [comment]
There's nothing wrong with the password, but you forgot to 'import _ "gopkg.in/goracle.v2"'.




On Sat, Jul 27, 2019 at 11:06 AM +0200, "kiemrong08" <notifications@github.com> wrote:












Can you provide me some example using ConnectionParams

When i using
sql.Open("goracle", goracle.ConnectionParams{User:"cc", Password:"c@c*1", SID:"192.168.1.1/cc"}.String())



Go say : undefined: goracle

**Comment by kiemrong08** [comment]
thank you, i solved this problem
