### ISSUE TITLE
Minimum Oracle DB version

### ISSUE THREAD

**Issue by cmberard10** [go-goracle/goracle#210]
I know this isn't an issue but what is the recommended version of Oracle DB to be able to use goracle? We are using goracle 2.20.0 with Oracle DB 11 and wanted to know if this is compatible and also what the requirements are to use goracle 2.00.0

**Comment by tgulacsi** [comment]
As goracle uses ODPI, see https://oracle.github.io/odpi/doc/installation.html#oracle-client-and-oracle-database-interoperability
