### ISSUE TITLE
IPv6 addresses are stripped of square brackets - causing identifier resolution errors

### ISSUE THREAD

**Issue by eric-google** [go-goracle/goracle#215]
**Describe the bug**
When you try to use an IPv6 address with a port (at least localhost [::1]), goracle appears to strip the brackets from the hostname which makes the connection string look like "::1:12345/dbname". This causes an "ORA-12154: TNS: could not resolve the connect identifier specified" error.

**To Reproduce**
Example code:
// Create oracle instance on local host, listening to port 12345 with a database name dbname
sql.Open("goracle", "[::1]:12345/dbname")

**Expected behavior**
Expect driver to attempt to connect to the host/port

**Additional context**
I believe the issue comes from https://github.com/go-goracle/goracle/blob/master/drv.go#L783 which parses a connection string and extracts the hostname. The golang docs for URL explicitly say that if it is an ipv6 address it will strip out square brackets - but they need to be added back in for the Oracle driver.

**Comment by tgulacsi** [comment]
PTAL 52a7036

**Comment by eric-google** [comment]
Looks good, thanks for the fast response!
