### ISSUE TITLE
sql.DB.Close got error: Close: ORA-00000: DPI-1011: connection was not acquired from a session pool 

### ISSUE THREAD

**Issue by zhuqiuzhi** [go-goracle/goracle#217]
version: v2.23.6

**Comment by tgulacsi** [comment]
Please help me with a minimal reproduction, or at least a code snippet about what you're doing, how do you connect, and when and where is this error is raised?

**Comment by zhuqiuzhi** [comment]
### What did you do?
<code>
package main
import (
	"database/sql"
	"fmt"
	"github.com/goracle"
)

func main() {
	conn := goracle.ConnectionParams{
		Username:             "userName",
		Password:             "password",
		SID: fmt.Sprintf("(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=%s)(PORT=%s))(CONNECT_DATA=(SID=%s)))",
			"10.30.149.33", "1521", "EE"),
		IsSysDBA:true,
	}
	db, err := sql.Open("goracle", conn.StringWithPassword())
	if err != nil {
		fmt.Println(err)
	}

	defer func() {
		fmt.Println(db.Close())
	}()

	tx, err := db.Begin()
	if err != nil {
		fmt.Println(err)
		return
	}
	_, err = tx.Exec(`INSERT INTO "items" ("id", "name") VALUES (2, 'test')`)
	if err != nil {
		tx.Rollback()
		fmt.Println(err)
		return
	}
	err = tx.Commit()
	if err != nil {
	 	fmt.Println(err)
	}
}
</code>

### What did you expect to see?
nothing

### What did you see instead?
Close: ORA-00000: DPI-1011: connection was not acquired from a session pool
