### ISSUE TITLE
Issue downloading package

### ISSUE THREAD

**Issue by amiracam** [go-goracle/goracle#219]
hi, I encounter the following issues downloading the package on Windows 10 on GO 1.14.2

C:\Users\Charles\GolandProjects\DBI_GO>go get gopkg.in/goracle.v2
# gopkg.in/goracle.v2
In file included from src\gopkg.in\goracle.v2\odpi\embed/dpi.c:37:0,
                 from src\gopkg.in\goracle.v2\drv.go:48:
src\gopkg.in\goracle.v2\odpi\embed/../src/dpiOci.c: In function 'dpiOci__getLoadErrorOnWindows':
src\gopkg.in\goracle.v2\odpi\embed/../src/dpiOci.c:1693:38: error: 'ERROR_MUI_FILE_NOT_FOUND' undeclared (first use in this function)
src\gopkg.in\goracle.v2\odpi\embed/../src/dpiOci.c:1693:38: note: each undeclared identifier is reported only once for each function it appears in

thanks

**Comment by tgulacsi** [comment]
This seems to be an old C compiler.

But goracle has moved to github.com/godror/godror.
