### ISSUE TITLE
Can't get the latest master

### ISSUE THREAD

**Issue by omerkirk** [go-goracle/goracle#22]
Hi, 

Cannot get the latest master in go get. Is there any other way to be able to get it, there are some new bug fixes in master.

**Comment by tgulacsi** [comment]
As README says:
```
cd $GOPATH.src/gopkg.in/goracle.v2
git remote add upstream https://github.com/go-goracle/goracle.git
git fetch upstream
git checkout -b master upstream/master
```

But I've tagged the current master as v2.1.3
