### ISSUE TITLE
Sending PLSqlArray with size 1 behaves different

### ISSUE THREAD

**Issue by omerkirk** [go-goracle/goracle#23]
I have a stored procedure that accepts multiple parameters that are all one of the following:

```
TYPE cx_array_date IS TABLE OF DATE
                            INDEX BY BINARY_INTEGER;

TYPE cx_array_string IS TABLE OF VARCHAR2 (1000)
                            INDEX BY BINARY_INTEGER;

TYPE cx_array_num IS TABLE OF NUMBER
                           INDEX BY BINARY_INTEGER;

PROCEDURE P_BULK_INSERT_IMP (VIMP_DATES       cx_array_date,
                                VIMP_KEYS        cx_array_string,
                                VIMP_IP          cx_array_num,
                                VIMP_ZONE        cx_array_num,
                                VIMP_PLAN        cx_array_num,
                                VIMP_BANNER      cx_array_num,
                                VIMP_REFERRER    cx_array_string,
                                VIMP_COUNTRY     cx_array_string,
                                VIMP_REGION      cx_array_string);
```

When I call this procedure with the new driver like below: 
```
db.ExecContext(ctx, procInsertImpressions, goracle.PlSQLArrays, dates, keys, ips, zones, plans, 
                   banners, referrers, countries, regions)
```
if the parameter arrays contains only 1 element they are not regarded as arrays althought the goracle.PlSQLArrays option is set, and I get the following error:

```
PLS-00306: wrong number or types of arguments in call to 'P_BULK_INSERT_IMP' 
ORA-06550: line 1, column 7:
```

I think the following part in the newVar function in conn.go is responsible for deciding what is regarded as an array and what is not, if I change the if statement to account for arrays with size 1 everything works as expected. 

CURRENT:
```
if isPlSQLArray && arraySize > 1 {
     isArray = 1
} else if arraySize < 0 {
     arraySize = 1
}
```

CHANGED:
```
if isPlSQLArray && arraySize > 0 {
     isArray = 1
} else if arraySize < 0 {
     arraySize = 1
}
```
While browsing your commits I saw one named ["force array length to be at least 2"](https://github.com/go-goracle/goracle/commit/66504070349c7edfb75cc849949614e3fd15709c) so I am guessing this is desired behaviour and not a bug by the driver. Can you let me know what is the correct way to deal with this.

**Comment by tgulacsi** [comment]
You're right, I've "fixed" at the wrong spot.

Can you try 86a02e5 ?

**Comment by omerkirk** [comment]
Works great now thanks.
