### ISSUE TITLE
Slice out of bounds error

### ISSUE THREAD

**Issue by omerkirk** [go-goracle/goracle#24]
If I send array parameters that are larger than some internal limit currently the app panics with slice out of bounds error. 
```
goroutine 43 [running]:
gopkg.in/goracle%2ev2.(*conn).newVar(0xc424d1e6c0, 0x7db00000001, 0xbbd, 0x2710, 0x0, 0xc431b74000, 0xf430, 0xc4335c8dc8, 0x3, 0x3, ...)
        /home/kokteyl/go/src/gopkg.in/goracle.v2/conn.go:234 +0x9ef
gopkg.in/goracle%2ev2.(*statement).bindVars(0xc4362792b0, 0xc4202304e0, 0x9, 0xa, 0x957eb8, 0xc4335c9408, 0xc43036d620)
        /home/kokteyl/go/src/gopkg.in/goracle.v2/stmt.go:643 +0x1f33
gopkg.in/goracle%2ev2.(*statement).ExecContext(0xc4362792b0, 0xda12a0, 0xc4200180a8, 0xc4202304e0, 0x9, 0xa, 0x0, 0x0, 0x0, 0x0)
        /home/kokteyl/go/src/gopkg.in/goracle.v2/stmt.go:181 +0x196
database/sql.ctxDriverStmtExec(0xda12a0, 0xc4200180a8, 0xda15a0, 0xc4362792b0, 0xc4202304e0, 0x9, 0xa, 0x9, 0xa, 0x0, ...)
        /usr/local/go/src/database/sql/ctxutil.go:66 +0x22e
database/sql.resultFromStatement(0xda12a0, 0xc4200180a8, 0xda0760, 0xc424d1e6c0, 0xc433443750, 0xc4335c9c50, 0xa, 0xa, 0x0, 0x0, ...)
        /usr/local/go/src/database/sql/sql.go:2109 +0x184
database/sql.(*DB).execDC(0xc4201f4460, 0xda12a0, 0xc4200180a8, 0xc43c3cbd50, 0xc4249ce8a8, 0x9522ce, 0xa6, 0xc4335c9c50, 0xa, 0xa, ...)
        /usr/local/go/src/database/sql/sql.go:1272 +0x2c7
database/sql.(*DB).exec(0xc4201f4460, 0xda12a0, 0xc4200180a8, 0x9522ce, 0xa6, 0xc4249cec50, 0xa, 0xa, 0x1, 0x882480, ...)
        /usr/local/go/src/database/sql/sql.go:1238 +0x13e
database/sql.(*DB).ExecContext(0xc4201f4460, 0xda12a0, 0xc4200180a8, 0x9522ce, 0xa6, 0xc433443c50, 0xa, 0xa, 0x882480, 0x59fc6701, ...)
        /usr/local/go/src/database/sql/sql.go:1216 +0xe1
database/sql.(*DB).Exec(0xc4201f4460, 0x9522ce, 0xa6, 0xc4249cec50, 0xa, 0xa, 0x3b, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1230 +0x85
```

Current limit in my application for array bulk insert is 10000, is the internal limit enforced by oracle or should it be adjustable by the library user. 

If the former than maybe this limit should be handled and returned as an error to the caller. If the latter then a function or per context knob can be given to the caller.  Or maybe simply a higher limit can be set as default and just the panic can be handled.

**Comment by tgulacsi** [comment]
The maxArraySize constant is 1<<10 (=1024) ATM. How big shall it be?
That's a hard question, as for OUT params, that much memory has to be
allocated beforehand.

Try 4f9306b - I've raised the limit to 32k.

omerkirk <notifications@github.com> ezt írta (időpont: 2017. nov. 3., P,
14:26):

**Comment by omerkirk** [comment]
Thanks Tamas,

That works, I only use the arrays as input parameters but as you say if they were out params 32K limit would be too high and would definitely cause memory issues. Is it possible to add two seperate knobs and sane defaults for both. 

Closing the issue, this is just food for thought :)

**Comment by tgulacsi** [comment]
What do you think about 023c531 ?
You can tweak the fetched row count with adding `goracle.FetchRowCount(10000)` as an argument to Query.
