### ISSUE TITLE
Performance issues when using array params compared to goraclev1

### ISSUE THREAD

**Issue by omerkirk** [go-goracle/goracle#25]
Hi Tamas,

I just upgraded one of our services to go 1.9.2 after changing db side from goracle.v1 to goracle.v2. This service bulk inserts into DB in groups of max 10K items. The old service which used go1.5.4 and goracle.v1 completes the insert around 80ms as can be seen from log line below: 

`successfully inserted 6460 impressions generated query in 60.960046ms, inserted in 39.937928ms`

The new service that uses go1.9.2 and goracle.v2 almost takes 300 ms for a similar group. Is it possible this is related to the driver or is this simply the overhead of using sql.Database. 

`successfully inserted 7493 impressions generated query in 1.192113ms, inserted in 272.313709ms`

goracle v1 side used go 1.5.4
goracle v2 code uses 1.9.2

Below are the details of the db function parameters and their usage on the golang side. 

ORACLE:
```
TYPE cx_array_date IS TABLE OF DATE
                            INDEX BY BINARY_INTEGER;

TYPE cx_array_string IS TABLE OF VARCHAR2 (1000)
                            INDEX BY BINARY_INTEGER;

TYPE cx_array_num IS TABLE OF NUMBER
                           INDEX BY BINARY_INTEGER;

PROCEDURE P_BULK_INSERT_IMP (VIMP_DATES       cx_array_date,
                                VIMP_KEYS        cx_array_string,
                                VIMP_IP          cx_array_num,
                                VIMP_ZONE        cx_array_num,
                                VIMP_PLAN        cx_array_num,
                                VIMP_BANNER      cx_array_num,
                                VIMP_REFERRER    cx_array_string,
                                VIMP_COUNTRY     cx_array_string,
                                VIMP_REGION      cx_array_string);
```

GO 1.5.4 Goracle V1:

```
dates := make([]interface{}, len(imps))
	keys := make([]interface{}, len(imps))
	ips := make([]interface{}, len(imps))
	zones := make([]interface{}, len(imps))
	plans := make([]interface{}, len(imps))
	banners := make([]interface{}, len(imps))
	referrers := make([]interface{}, len(imps))
	countries := make([]interface{}, len(imps))
	regions := make([]interface{}, len(imps))
	for i, imp := range imps {
		dates[i] = imp.CreDate
		keys[i] = imp.UserKey
		ips[i] = imp.IP
		zones[i] = imp.ZoneID
		plans[i] = imp.PlanID
		banners[i] = imp.BannerID
		referrers[i] = imp.Referrer
		countries[i] = imp.Country
		regions[i] = imp.Region
	}
	dateType := oracle.DateTimeVarType

	strType := oracle.StringVarType

	numType := oracle.Int64VarType

	oraDates, err := session.cu.NewArrayVar(dateType, dates, 0)
	if err != nil {
		log.Println(err)
		return err, 0, 0
	}
	oraKeys, err := session.cu.NewArrayVar(strType, keys, 23)
	if err != nil {
		log.Println(err)
		return err, 0, 0
	}
	oraIPs, err := session.cu.NewArrayVar(numType, ips, 0)
	if err != nil {
		log.Println(err)
		return err, 0, 0
	}
	oraZones, err := session.cu.NewArrayVar(numType, zones, 0)
	if err != nil {
		log.Println(err)
		return err, 0, 0
	}
	oraPlans, err := session.cu.NewArrayVar(numType, plans, 0)
	if err != nil {
		log.Println(err)
		return err, 0, 0
	}
	oraBanners, err := session.cu.NewArrayVar(numType, banners, 0)
	if err != nil {
		log.Println(err)
		return err, 0, 0
	}
	oraReferrers, err := session.cu.NewArrayVar(strType, referrers, 1000)
	if err != nil {
		log.Println(err)
		return err, 0, 0
	}
	oraCountries, err := session.cu.NewArrayVar(strType, countries, 3)
	if err != nil {
		log.Println(err)
		return err, 0, 0
	}
	oraRegions, err := session.cu.NewArrayVar(strType, regions, 100)
	if err != nil {
		log.Println(err)
		return err, 0, 0
	}

	t2 := time.Now()
	_, err = session.cu.CallProc(procInsertImpressions, []interface{}{oraDates, oraKeys, oraIPs, oraZones, oraPlans, oraBanners, oraReferrers, oraCountries, oraRegions}, nil)
	t3 := time.Now()
```
Where **session.cu** is oracle.Cursor from goracle.v1.

GO 1.9.2 Goracle V2:

```
t1 := time.Now()
	dates := make([]time.Time, len(imps))
	keys := make([]string, len(imps))
	ips := make([]int, len(imps))
	zones := make([]int, len(imps))
	plans := make([]int, len(imps))
	banners := make([]int, len(imps))
	referrers := make([]string, len(imps))
	countries := make([]string, len(imps))
	regions := make([]string, len(imps))
	for i, imp := range imps {
		dates[i] = imp.CreDate
		keys[i] = imp.UserKey
		ips[i] = int(imp.IP)
		zones[i] = imp.ZoneID
		plans[i] = imp.PlanID
		banners[i] = imp.BannerID
		referrers[i] = imp.Referrer
		countries[i] = imp.Country
		regions[i] = imp.Region
	}
	t2 := time.Now()
	_, err := db.Exec(procInsertImpressions, goracle.PlSQLArrays, dates, keys, ips, zones, plans, banners, referrers, countries, regions)
	t3 := time.Now()
```

Where **db** is sql.DB from standart library

**Comment by tgulacsi** [comment]
Can you check 4af824f and tweak BenchmarkPlSQLArrayInsert25 in `z_bench_test.go` to make it realistic?

**Comment by tgulacsi** [comment]
Profiling showed that Sprintfs in Log uses a significant amount of time - commented those out.
ff1b655

**Comment by omerkirk** [comment]
I tried the Benchmark in my DB, it gives near real world results, so I didn't change the query or the benchmark. I've been trying to improve the performance by cleaning up some reflect.Calls and decreasing the number of type switches in bindVars function. Both the profiler and naive time.Now() measurements say that most of the time is spend inside that function. 

I guess the previous version of goracle.v1 had the advantage of knowing the data types of the params before hand. But this time because there is no way to pass type info through sgl.NamedValues, all type info is found by expensive reflect calls. 

**Things I've tried:**
There are a lot of sections in bindVars where an outer type switch is redirected into a smaller function where another type switch is made like a funnel. I replaced general functions with type switches, with more specific functions with type assertions but I couldn't change the benchmark results that much.  

There is an array that has the reflect.Values of the arguments. There are some parts of bindvars where reflect.ValueOf is called although the value is already in rArgs array. Again changing these didn't have much effect. 

Hope these help

**Comment by tgulacsi** [comment]
Btw your benchmark is skewed: you don't count the data copying from "keys" to "oraKeys" & co.

**Comment by omerkirk** [comment]
Actually that is the generated query part of the log line I shared. I gave the total numbers that accounts for the creation of NewArrayVar calls.

**Comment by omerkirk** [comment]
The performance is much better with your latest commit.  

```
stmt exec 81.52511ms stmt bind vars 47.444051ms
successfully inserted 10000 impressions generated query in 1.412375ms, inserted in 129.08813ms
```

I added another measurement inside ExecContext function to see the how time is distributed between actual execution and variable binding.

**Comment by tgulacsi** [comment]
You said old service `6460 impressions generated query in 60.960046ms, inserted in 39.937928ms` ~ `10000 impressions in (61+40) * 10000/6460 = 156ms`
new service `10000 impressions generated query in 1.412375ms, inserted in 129.08813ms`.

So, are we there yet?

**Comment by omerkirk** [comment]
I wanted to wait a bit to be sure. But it definitely looks like we are there. Thank you for the quick fixes and hardwork.

**Comment by omerkirk** [comment]
Can you tag a release with the latest performance upgrade.

**Comment by tgulacsi** [comment]
Done.

omerkirk <notifications@github.com> ezt írta (időpont: 2017. nov. 8., Sze,
10:18):
