### ISSUE TITLE
Unknown type error for uint and int 16

### ISSUE THREAD

**Issue by omerkirk** [go-goracle/goracle#26]

**Comment by tgulacsi** [comment]
Can you provide some details? What kind of query with what kind of params or Scan destinations?

**Comment by omerkirk** [comment]
Sorry for that, it is in the below use case I get this error. But I didn't see int16, uint16 type switch cases in none of the driver code so I am guessing there might be other use cases too. 

```
qps := []interface{}{
		sql.Named("VACTION_STEP", act.Goal), //act.Goal is int16 field
		sql.Named("VTRAN_ID", act.TransactionID)}

	_, err := db.Exec(procInsertAction, qps...)
```

I get the following error: 
`unknown type int16
`
This error response only gets returned by the ConvertValue functions in drv.go. However even if that passes through, I didn't see any handling of int16, int16[], uint16, uint16[] types in dataSetNumber vs kind of functions. 

Hope this helps.

**Comment by tgulacsi** [comment]
I've added int16 in 375c009, but I'm afraid you'll get "PLS-00418: array
bind type must match PL/SQL table row type".

omerkirk <notifications@github.com> ezt írta (időpont: 2017. nov. 9., Cs,
12:05):
