### ISSUE TITLE
How to use sql.Out with a procedure returning an rset with multiple rows?

### ISSUE THREAD

**Issue by veqryn** [go-goracle/goracle#27]
I have a stored procedure that requires an 'out' parameter.
I am attempting to access it like so:
```go
var data []struct {
	RegexpID        goracle.Number
	Regexp          string
	OtherID         goracle.Number
	RegexpMatchType goracle.Number
}
result, err := conn.ExecContext(ctx, `begin myuser.get_regexs(:v1); end;`, goracle.PlSQLArrays, sql.Out{Dest: &data})
```

This gives me the following error: `1. arg: unknown type []struct { RegexpID goracle.Number; Regexp string; OtherID goracle.Number; RegexpMatchType goracle.Number }`

I have also tried making data a `[]interface{}`, with similar results.

I tried reading the examples in your tests, but it looks like all of them are in-out variables, and not rset's.

The stored procedure looks approximately like this:
```sql
PROCEDURE get_regexs( o_csr OUT o_as_cur) IS
BEGIN
  IF (o_csr%ISOPEN) THEN
    CLOSE o_csr;
  END IF;
  OPEN o_csr FOR
    SELECT
      t1.regexp_id,
      t1.regexp,
      t1.other_id,
      t1.regexp_match_type
    FROM
      my_regexp_t t1
    WHERE
     t1.status = 1;;
END;
```

And here is approximately the perl code I am trying to migrate to golang:
```perl
my $regex_sth = $dbh->prepare(
    'begin myuser.get_regexs(:v1); end;'
);
$regex_sth->bind_param_inout(':v1', \$csr, 0, { ora_type => ORA_RSET });
$regex_sth->execute();
while ( my @rx_info = $csr->fetchrow_array() ) {
    # stuff...
}
$regex_sth->finish();
```

How do I get this to work with this oracle driver?

**Comment by tgulacsi** [comment]
```
import "database/sql/driver"

var rset driver.Rows
_, err := conn.ExecContext(ctx, `begin myuser.get_regexs(:1); end;`, sql.Out{Dest: &rset})
// handle error
type rowType struct {
	RegexpID        goracle.Number // or int64, if fits
	Regexp          string
	OtherID         goracle.Number // or int64, if fits
	RegexpMatchType goracle.Number // or int64, if fits
}
var row rowType
rowI := []driver.Value{&row.RegexpID, &row.Regexp, &row.OtherID, &row.RegexpmatchType}
for {
  if err := rows.Next(rowI); err != nil {
    if err == io.EOF {
      break
    }
    return err
  }
  // use row
}
```

**Comment by veqryn** [comment]
Thank you for the quick reply!

That mostly worked.

Very oddly though, `row` is always empty, while `rowI` actually contains the data.

I gave this a try, and it surprisingly also works, which I didn't think was possible (because I'm not telling golang or the driver which type the constant `0` is):
```go
	rows := []driver.Value{0, "", 0, 0}
	for {
		if err := rset.Next(rows); err != nil {
			if err == io.EOF {
				break
			}
			return err
		}
		log.WithField("rows", rows).Info("query row")
	}
```

**Comment by tgulacsi** [comment]
You're right, Next does not care about the contents of its argument, only uses it to store the values.

**Comment by veqryn** [comment]
So,... are there any other types other than `driver.Rows` that can be used?
And if not, what is the best way to scan that into variables?
I was poking around sql and sqlx libraries but haven't seen anything accepting that type...

**Comment by tgulacsi** [comment]
I don't have an easy anwer. Use some converter (like
github.com/tgulacsi/oracall/custom AsXxx functions) or write the type
switches yourself.

Chris Duncan <notifications@github.com> ezt írta (időpont: 2017. nov. 11.,
Szo, 21:47):

**Comment by veqryn** [comment]
I hadn't seen oracall before, it looks neat.
For now I'm getting by with copying `convertAssign` from `database/sql` stdlib package.  (It is unfortunate that it is private.)
thanks for your help and this repo!
