### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by veqryn** [go-goracle/goracle#30]
This is more a question than an issue.

I've been using the mattn oracle driver for some time now, mostly because it compiles a lot faster than the rana driver.
However, it doesn't appear to support stored procedures, which I need to use.
So, I now need to choose between rana and goracle (and since you develop both, you are good person to ask).

Would you say goracle is production ready?

Are there any parts of goracle (or specific kinds of oracle queries or things) that I should avoid for production applications?

Are there any known bugs or major missing features?

thx!

**Comment by tgulacsi** [comment]
I know that rana/ora has some unsolved issues (See github.com/rana/ora/issues/233 for example).
But it is used in production.

goracle.v2 is much younger, I do find new easy errors here and there - but it is used in production, too.
It's waaay simpler than rana/ora.v4 and thus easier to reason about, find & fix errors, and so on.
So I'm sure it *will* be the better in the midterm (say, half year).
But I'm not sure it is better yet.

As goracle.v2 is so young, it's used only for only my use cases: DATE, VARCHAR2, NUMBER, (github.com/tgulacsi/go/dbcsv/csvload), LOB datatypes, PL/SQL associative arrays (see github.com/tgulacsi/oracall).
You should test it for your use case, force us to squeeze out all remaining errors, and then use it in production.

**Comment by veqryn** [comment]
Thanks. We will give it a try.
