### ISSUE TITLE
Goracle.v2 less efficient while getting a connection from DB compared to goracle.v1

### ISSUE THREAD

**Issue by omerkirk** [go-goracle/goracle#31]
Hi Tamas, 

After some testing and with the final performance improvements I deployed our service to production last week. I wanted to report back some issues that I've observed. The previous version of this service was using goracle.v1 as the driver but because it used lots oracle specific features I couldn't use the database/sql compatible driver, and instead used the ora package for calling procedures and passing array variables to db. The problem with that was I had to implement the pooling since I needed to limit max connection and max idle connections from the db. The old service was working without issues but since goracle.v1 didn't support newer go versions I wanted to try goracle.v2 so that I can use the database/sql connection pooling along with calling procedures and out parameters and so on. 

After the upgrade I realized our db server's CPU increased a lot compared to our other service, and the system started crashing after logging the following: 

```
acquireConnection[oracle://db:password@SID))?connectionClass=GORACLE&poolIncrement=1&poolMaxSessions=1000&poolMinSessions=1&sysdba=0&sysoper=0]: ORA-12537: TNS:connection closed
```
After each restart getting the first connection from DB took somewhere between 1 to 30 seconds and couldn't balance itself under load and crashed again after a few minutes. 

After converting to the old service everything went back to normal, and the CPU on the DB server decreased to 10% of what it was while handling much larger load (x5). 

Below there is a sample of how I am using and pooling connections with goracle.v1, I thought it might give some ideas on this issue. Please let me know if you need anything else. 

```
type conn struct {
	db *DB
	cx *oracle.Connection

	id         int
	mu         sync.Mutex
	inUse      bool
	numCursors int
	createdAt  time.Time
}

func (c *conn) sessionLocked() *session {
	if c.cx == nil {
		return nil
	}
	if !c.cx.IsConnected() {
		return nil
	}
	cu := c.cx.NewCursor()
	c.numCursors++
	//log.Printf("conn %d - new session: %d", c.id, c.numCursors)
	if c.numCursors == c.db.maxCursors {
		c.inUse = true
	}
	return &session{c, cu, false}
}
```
In goracle.v1 ora functions were defined on cursors not the connections. So I pooled connections but didn't remove them from the pool until number of open cursors reached a certain limit which is 5 currently. So if I had max open connections of 10 I could perform 50 oracle functions over them before running out of connections. I am not sure if this improves performance or the same in goracle.v2 also but there is definitely a regression in using or getting the connections from db in the new version.

**Comment by tgulacsi** [comment]
Are you sure you close all Stmt, Rows, driver.Rows ?

omerkirk <notifications@github.com> ezt írta (időpont: 2017. nov. 19., V,
21:55):

**Comment by omerkirk** [comment]
I am using sqlx to manage Selects so rows are closed automatically by that library. I've checked prepared statements now used to call procedures and defer statements are all in place. The previous pooling also required closing sessions so I didn't have to change a lot in new upgraded functions.

**Comment by cjbj** [comment]
A couple of notes from the sidelines about the underlying OCI / Oracle stack:
- each connection can only ever execute one statement at a time, so with 10 connections, if you try to execute 50 statements something is going to block somewhere.  The impact of this needs to be examined, in case the blocking is non-optimal or has side effects.
- Oracle's Real-World Performance Group like keeping the pool min & max the same to avoid connection storms.  See their rationale [here](https://docs.oracle.com/database/122/JJUCP/optimizing-real-world-performance.htm#GUID-BC09F045-5D80-4AF5-93F5-FEF0531E0E1D).  Yes, this will mean the pool start up time is longer than when min is 1.
- Check the statement cache size

**Comment by tgulacsi** [comment]
First, I'd limit database/sql pool with db.SetMaxOpenConns(50), db.SetMaxIdleConns(10), db.SetConnMaxLifetime(300*time.Second) and if that blocks somewhere, then that means you don't Close something somewhere.
