### ISSUE TITLE
NullTime

### ISSUE THREAD

**Issue by bayan** [go-goracle/goracle#32]
How do we handle null values returned for timestamp fields?

I could not see a NullTime type defined (e.g. https://godoc.org/github.com/lib/pq#NullTime, https://godoc.org/github.com/go-sql-driver/mysql#NullTime).

Is there an alternative way to handle null values for timestamp columns?

**Comment by tgulacsi** [comment]
Right now the zero time (`var t time.Time; t.IsZero()`) is treated as NULL, and NULL DATE fields are returned as zero time.
Do you really need the "0001-01-01 00:00:00 +0000 UTC" moment (https://play.golang.org/p/Ec-ZOcdfDd)? Do you really wish to distinguish this from NULL?
If yes, then maybe a NullTime should be introduced.

**Comment by bayan** [comment]
Thanks!

For completeness and accuracy, I think it's a good idea to implement NullTime.

But for my own purposes, your solution to use IsZero is all I need. Thanks again! I didn't know about that function until you brought it up.
