### ISSUE TITLE
Closing connection hangs  in Cfunc_dpiConn_release

### ISSUE THREAD

**Issue by mguggi** [go-goracle/goracle#33]
I'm use the last version of the oracle Instant client 12.2.0.1 and go 1.9.2.  

My code look like 

```golang
// close db connection
if err = m.db.Close(); err != nil {
    errors.Wrapf(err, "%s failed close connection", selector)
}
```

When I kill my program I receive this stacktrace: 
```
goroutine 62 [syscall, locked to thread]:
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/goracle%2ev2._Cfunc_dpiConn_release(0x46da9c0, 0x0)
	github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/goracle.v2/_obj/_cgo_gotypes.go:1448 +0x49
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/goracle%2ev2.(*conn).Close.func1(0x46da9c0, 0x2f5d950)
	/home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/goracle.v2/conn.go:112 +0x60
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/goracle%2ev2.(*conn).Close(0xc420230300, 0x0, 0x0)
	/home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/goracle.v2/conn.go:112 +0xa9
database/sql.(*driverConn).finalClose.func2()
	/home/mguggi/public/go-1.9.2/src/database/sql/sql.go:467 +0x49
database/sql.withLock(0x405f9e0, 0xc420011ce0, 0xc42019bd38)
	/home/mguggi/public/go-1.9.2/src/database/sql/sql.go:2867 +0x65
database/sql.(*driverConn).finalClose(0xc420011ce0, 0xc42019be58, 0xc42019be48)
	/home/mguggi/public/go-1.9.2/src/database/sql/sql.go:465 +0x128
database/sql.(finalCloser).(database/sql.finalClose)-fm(0xc42008d108, 0xc420346ea0)
	/home/mguggi/public/go-1.9.2/src/database/sql/sql.go:564 +0x2f
database/sql.(*DB).Close(0xc42008d0e0, 0x0, 0x0)
	/home/mguggi/public/go-1.9.2/src/database/sql/sql.go:678 +0x31b
github.com/mguggi/oraclebeat/module/oracle/sgastats.(*MetricSet).Close(0xc42008d7c0, 0x406ec20, 0xc42008d7c0)
	/home/mguggi/go/src/github.com/mguggi/oraclebeat/module/oracle/sgastats/sgastats.go:110 +0xd7
github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module.(*metricSetWrapper).close(0xc420118d40, 0x0, 0x0)
	/home/mguggi/go/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:257 +0x64
github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module.(*Wrapper).Start.func1(0xc4200193e0, 0xc420020ba0, 0xc4202504e0, 0xc420118d40)
	/home/mguggi/go/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:111 +0xbe
created by github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module.(*Wrapper).Start
	/home/mguggi/go/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:106 +0x146
```

It looks like that the statement hangs in the dpiConn_release function. I've seen this behaviour only on two 12.1.0.2 databases. How can I get additionaly debug inoformation? Is there a debug mode or somthing else?

**Comment by tgulacsi** [comment]
Your program hangs, and SIGQUIT (Ctrl+\) provides that stacktrace?
Is anything in progress? Maybe a c.Break should be called before?

If you look at the code, you see that you can provide a Log function, either globally, or by Context, or just put a deliberate amount of `fmt.Fprintf(os.Stderr, ...)` at interesting places...

**Comment by mguggi** [comment]
The program is running as expected, when I try to stop the program with press `Ctrl+C` the program is calling my Close() method and than the program hangs. 

After a while I open a second terminal and send `kill -ABRT <pid>` and than the stacktrace above will be printed. 

In the meantime I have found that the problem only occurs if the program is running local and the database is running remote and both sides are connected over our VPN tunnel.

For this reason I believe it's a network or connection issue on our side no problem with the database driver. 

That's why I think we can close this request. 

@tgulacsi Thanks for your quick response ... the go driver works as expected and in my opinion it's a great work from your side!

**Comment by mguggi** [comment]
The program is running as expected, when I try to stop the program with press `Ctrl+C` the program is calling my Close() method and than the program hangs.

After a while I open a second terminal and send `kill -ABRT <pid>` and than the stacktrace above will be printed.

In the tcpdump I see that the flag URG is set when I press `Ctrl+C`

The code works when I remove the `db.Close()` stuff from Close() method.

**Comment by tgulacsi** [comment]
Can you try df5c84e ?

**Comment by mguggi** [comment]
Unfortunately this not resolve the issue. 

When I execute the procedure above and create an tcpdump on my interface and port 1521 I receive the following line:

`153	31.614966	192.168.12.12	172.16.1.108	TCP	67	57578 → 1521 [PSH, ACK, URG] Seq=2790 Ack=87582 Win=182272 Urg=1 Len=1 TSval=32936936 TSecr=717866813[Malformed Packet: TNS]`

The `URG` flag is set when I pressing `Ctrl+C` ...

But the curious thing is that this code works when the database is running on the same host. It looks like a vpn tunnel or firewall issue ...

**Comment by tgulacsi** [comment]
Sorry, I can't help here. Ask the ODPI-C Oracle guys - @anthony-tuininga and @cjbj !

**Comment by mguggi** [comment]
Close the issue in this repository and open a new issue in the oracle/odpi [#50](https://github.com/oracle/odpi/issues/50) repository. 

@tgulacsi The driver and your support are really brilliant. Really good job thanks for that.

**Comment by giter** [comment]
@mguggi  Hi guys , does [locked to thread] hangs up some of your program ?

**Comment by cjbj** [comment]
What platform is the hang seen on?

**Comment by mguggi** [comment]
@giter Hi, in my case it wasn't a problem of go, odpi or gooracle. Rather it was a issue that the oracle client set the URG flag when it closes the connection and the most firewalls prohibt this by default. My solution was to set a flag in the configuration file of the Oracle client. You can find further details in [#50](https://github.com/oracle/odpi/issues/50)
