### ISSUE TITLE
good job

### ISSUE THREAD

**Issue by hljlgj** [go-goracle/goracle#34]
when i use the latest code from rana/ora and goracle today, It's better than before in performance
starting test oracle database driver: ora
start get sql.DB: 2017-12-14 14:05:36
starting query: 2017-12-14 14:05:37
query finished: 2017-12-14 14:05:42
read one primary key of type char(20),record count: 424698 用时 5162 ms
starting test oracle database driver: goracle
start get sql.DB: 2017-12-14 14:05:42
starting query: 2017-12-14 14:05:42
query finished: 2017-12-14 14:05:45
read one primary key of type char(20),record count: 424698 用时 2584 ms

**Comment by tgulacsi** [comment]
Just to be nitpicking: have you run both in different order, too? 'Cause
Oracle caches the query result, so the second run may be faster!

David_liu <notifications@github.com> ezt írta (időpont: 2017. dec. 14., Cs,
7:24):

**Comment by hljlgj** [comment]
when i change run order , or run alone one every time, time used no change ,goracle used less time than rana/ora
TestOracleDrv("goracle")
TestOracleDrv("ora")

starting test oracle database driver: goracle
start get sql.DB: 2017-12-14 16:03:05
starting query: 2017-12-14 16:03:05
query finished: 2017-12-14 16:03:08
read one primary key of type char(20),record count: 424698 用时 2566 ms
starting test oracle database driver: ora
start get sql.DB: 2017-12-14 16:03:08
starting query: 2017-12-14 16:03:08
query finished: 2017-12-14 16:03:13
read one primary key of type char(20),record count: 424698 用时 5073 ms

**Comment by tgulacsi** [comment]
Great, thanks!

**Comment by hljlgj** [comment]
same data of 1000 row ,time used diff ,so quickly in parameter array mode
batch insert mode rows Affected: 1000 time used:: 58 ms
per row mode rows Affected: 1000 time used: 2775 ms (transaction mode)
per row mode rows Affected: 1000 time used: 7128 ms (not in transaction mode)
