### ISSUE TITLE
_Cfunc_dpiPool_acquireConnection hangs on [locked to thread]

### ISSUE THREAD

**Issue by giter** [go-goracle/goracle#35]
Hi,  @tgulacsi 

I have a program for IoT platform , 
When we store item into oracle using goracle,   
program sometimes hang up and this may cause one core of cpus up to 100%
therefore when I use a 8-core cpu do benchmark test, cpu is continuous up to 12%

After dump pprof , I found that every thread is locked by goracle , see attachment 

Last function call maybe :  github.com/go-goracle/goracle._Cfunc_dpiPool_acquireConnection
Or:  github.com/go-goracle/goracle._Cfunc_dpiConn_release

[goroutine.txt](https://github.com/go-goracle/goracle/files/1594390/goroutine.txt)

**Comment by tgulacsi** [comment]
First, please try the latest v2.1.12 - it has some modifications, esp. Close first calls Break.
Second, do you Close all Rows, Stmt ?
Third, how many connections do you use?
Lastly, is it possible to have some kind of network glitch / firewall between the Go program and the Oracle DB?

**Comment by giter** [comment]
1.  yes, v2.1.12, latest version
2.  I checked all of my code, every session close 
3.  MaxOpenConns set to be 2500
    db.SetMaxOpenConns(2500)
    db.SetConnMaxLifetime(5 * time.Minute)
4.  There is no network / firewall problem,  because today I use go-oci8 alternatively and program then been good and no more [locked to thread] occurred

**Comment by giter** [comment]
I've debug this program more than 3 weeks,  today I use go-oci8 replace goracle and then program been ok, so ...

**Comment by tgulacsi** [comment]
But your trace says "E:/workspace/Go/src/github.com/go-goracle/goracle/conn.go:113" though v2.1.12 has a comment on that line (https://github.com/go-goracle/goracle/blob/v2.1.12/conn.go#L113).

**Comment by giter** [comment]
Okay, the actual version is 692379d16439bea526754d384981191d0f30a1a9 12/4/2017

![image](https://user-images.githubusercontent.com/1682298/34455141-87033f42-edb3-11e7-9543-f344d21d7d4e.png)

**Comment by giter** [comment]
@tgulacsi  how to tweak the connection params ?  by connection string ?

**Comment by giter** [comment]
@tgulacsi  by the way I found a related topic #33 ， maybe that's the really problem ??

**Comment by tgulacsi** [comment]
Params: yes, connection string. Either by crafting it by hand (add poolMaxSessions=2500), or by filling goracle.ConnectionParams and using its String() method.

Yes, #33 may be related.

**Comment by giter** [comment]
hi, is there any new progress?

**Comment by tgulacsi** [comment]
Could you try tweaking the poolMaxSessions?
