### ISSUE TITLE
Differece between rana/ora?

### ISSUE THREAD

**Issue by cemremengu** [go-goracle/goracle#38]
First of all, thank you for your work!

What are the differences between this driver and `rana/ora` ?

I see that you are working on that together as well so why this package?

For me this package is much easier to setup and work with but would like to hear if there are any other differences.

**Comment by tgulacsi** [comment]
This package needs Go 1.9, as that made it possible to have everything work through database/sql.
And this uses ODPI-C, which makes the C parts easier, too.

So goracle.v2 is a "next-gen" Oracle driver, has nothing in common with rana/ora.v4, only the main contributor, myself :)

**Comment by cemremengu** [comment]
Thank you for your answers and thanks again for your work!
