### ISSUE TITLE
How to set prefetchCount correctly?

### ISSUE THREAD

**Issue by cemremengu** [go-goracle/goracle#39]
The docs mention that prefetch count  `can be changed by adding a goracle.FetchRowCount(1000) argument to the call of Query`

So following this is it enough to just do(?):

`rows, err := db.Query(query.QueryText, goracle.FetchRowCount(1000) )`

Sorry, I am a bit new to the `database/sql` part of Go

**Comment by tgulacsi** [comment]
Yes. Go 1.9 made it possible to "leave out" some params (http://localhost:6060/pkg/database/sql/driver/#NamedValueChecker), and we can use it to inject options to the Query, without piggibacking Context.
