### ISSUE TITLE
DescribeQuery and ArraySize

### ISSUE THREAD

**Issue by or4cle** [go-goracle/goracle#40]
Hi,

I'm trying to use the DescribeQuery function in orahlp.go. However I receive this error:

`slice is bigger (32767) than the maximum (1024)
`

In drv.go, I can work around it by changing this:
`DefaultArraySize = 1 << 10`

To this:
`DefaultArraySize = 1 << 15`

However, I then receive this error:
`dpiStmt_execute(mode=32 arrLen=32767): ORA-06561: given statement is not supported by package DBMS_SQL`

Is there a working example somewhere of using DescribeQuery (e.g. csvdump) that I can reference? Looking at the underlying driver, it seems maybe utilizing `DPI_MODE_EXEC_DESCRIBE_ONLY `would be applicable.

Also, in drv.go, it says:
```
const (
        // DefaultFetchRowCount is the number of prefetched rows by default (if not changed through ContextWithFetchRowCount).
        DefaultFetchRowCount = 1 << 8

        // DefaultArraySize is the length of the maximum PL/SQL array by default (if not changed through ContextWithArraySize).
        DefaultArraySize = 1 << 15
)

```
But I don't see `ContextWithFetchRowCount` nor `ContextWithArraySize` mentioned anywhere else in the source.

**Comment by tgulacsi** [comment]
What kind of query are you analyzing?

**Comment by or4cle** [comment]
Thanks for the quick response! The queries in general are quite elaborate (although the describe works on the old "rana.v4" driver). However, even this simple one fails with the same message:

`select * from foo`

Where foo is described as:
```

 Name              Null?    Type
 ----------------- -------- ------------
 A                          VARCHAR2(32)
 B                          VARCHAR2(32)
 C                          VARCHAR2(32)
 D                          VARCHAR2(32)
 V                          NUMBER
```

It seems if we could integrate with this function from the underlying driver, it would get us what we want: `DPI_MODE_EXEC_DESCRIBE_ONLY`

**Comment by tgulacsi** [comment]
Can you try 903f2d4 ?

or4cle <notifications@github.com> ezt írta (időpont: 2018. febr. 11., V,
2:09):

**Comment by or4cle** [comment]
Yes, it works now, thanks much!

We may want to add to the documentation somewhere, that the Type value in QueryColumn comes from https://github.com/oracle/odpi/blob/e26ede4f7b9239bcc923a72171657dc09272b081/include/dpi.h#L229

(as opposed to the old rana driver where (iirc) the type value was aligned with the OCI type values).

**Comment by or4cle** [comment]
Thanks, good to know!
