### ISSUE TITLE
Use native go types instead of goracle types?

### ISSUE THREAD

**Issue by cemremengu** [go-goracle/goracle#41]
When I map the results to a generic `map[string]interface{}`, if I directly serialize it to `json` I will get all values as strings so I need to do this funky conversion shown below.

Would it be possible for the driver to use native go types so that the result will be interpreted correctly after the query mapping?

I may be doing something wrong or this might be related to the wrapper library (`sqlx`) I am using. Sorry if that is the case.

```go
func ConvertGenericMapping(result map[string]interface{}, dbType string) map[string]interface{} {

	converted := make(map[string]interface{})

	switch dbType {
	case ORACLE:

		for k, v := range result {

			switch v.(type) {
			case goracle.Number:
				value := string(v.(goracle.Number))
				if strings.Contains(value, ".") {
					converted[k], _ = strconv.ParseFloat(value, 64)

				} else {
					converted[k], _ = strconv.ParseInt(value, 10, 64)

				}
			default:
				converted[k] = v
			}
		}
	}

	return converted
}
```

**Comment by cemremengu** [comment]
I noticed that this is only for `goracle.Number` since the exact type is not obvious from `NUMBER` and I guess size matter for some people so you can't just return `float64` or something by default (and I assume this makes my request not really desirable to implement)

Is there at least a better way for what I am doing above?

**Comment by tgulacsi** [comment]
Yes, goracle.Number is a string representation of the number.
Just some small tweaks:
```
switch value := v.(type) {
		case goracle.Number:
			if strings.Contains(value, ".") {
				converted[k], _ = strconv.ParseFloat(value, 64)
			} else {
				converted[k], _ = strconv.ParseInt(value, 10, 64)
			}
		default:
			converted[k] = v
		}
```

But goracle.Number is a fmt.Stringer - does it help if I make it an encoding.TextMarshaler ?

Does 8410610 help?

**Comment by cemremengu** [comment]
Yes, definitely helped thank you! However, there is a small caveat; very large numbers are represented in scientific notation such as 

` "NETWORK_ID": 6.000370006565900000073e+21`

The rest looks fine. Maybe marshaling process should also check for the size of the number?

**Comment by tgulacsi** [comment]
Please see TestNumberMarshal in 56e9d7a and tweak it to reproduce your problem - I can't.
Are you sure you use string as your number field? The scientific notation suggests float64...
Maybe using json.Number could solve it, too.

**Comment by cemremengu** [comment]
Alright, testing the web request directly from chrome, it actually works 😄
 
It looks like `Postman` is not able to represent the number since (Node)JS cannot represent such big numbers. 

Thank you so much for your work and quick responses! This library was the only thing missing for us to use Go in our projects 😄

**Comment by tgulacsi** [comment]
JSON is to blame - or ECMAScript if you want the root problem: if treats
all numbers as float64.

Cemre Mengu <notifications@github.com> ezt írta (időpont: 2018. febr. 14.,
Sze, 8:33):
