### ISSUE TITLE
Question: ODPI-Go

### ISSUE THREAD

**Issue by cemremengu** [go-goracle/goracle#42]
What do you think about creating a pure go version of the ODPI-C library (if possible)? Not sure if Oracle has any plans about it in the near future.

I think it will help improve build times and performance. Although I have limited C experience, I would like to help if there is a plan for such a library.

**Comment by tgulacsi** [comment]
Oracle does not publicate it's Oracle SQL.NET protocol, so it would be very
hard to implement it - for legal reasons, it should be a clean-room
implementation.

So we, mere mortals are restricted to use the OCI C library, libclntsh.so.
With Go that means cgo, the same as with ODPI-C, but the latter exposes a
waaaay nicer API than pure OCI - compare rana/ora.v4 with goracle.v2.

So if we can't get rid of C altogether, I see no reason to use OCI instead
of ODPI-C.
ODPI-C is easier to compile, too - it allows embeding, and needs the Oracle
Client only at runtime, not at compile time!

Cemre Mengu <notifications@github.com> ezt írta (időpont: 2018. febr. 14.,
Sze, 10:17):

**Comment by cemremengu** [comment]
Fair enough, thanks for the explanation. I hope we will see the day that Oracle opensources its protocol!
