### ISSUE TITLE
Go 1.10 database/sql/driver changes

### ISSUE THREAD

**Issue by cemremengu** [go-goracle/goracle#43]
With the release of Go 1.10, there were some changes/improvements in the driver API as follows. Just leaving this here in case there needs to be work done given these changes.

- Drivers that currently hold on to the destination buffer provided by driver.Rows.Next should ensure they no longer write to a buffer assigned to the destination array outside of that call. Drivers must be careful that underlying buffers are not modified when closing driver.Rows.
- Drivers that want to construct a sql.DB for their clients can now implement the Connector interface and call the new sql.OpenDB function, instead of needing to encode all configuration into a string passed to sql.Open.
- Drivers that want to parse the configuration string only once per sql.DB instead of once per sql.Conn, or that want access to each sql.Conn's underlying context, can make their Driver implementations also implement DriverContext's new OpenConnector method.
- Drivers that implement ExecerContext no longer need to implement Execer; similarly, drivers that implement QueryerContext no longer need to implement Queryer. Previously, even if the context-based interfaces were implemented they were ignored unless the non-context-based interfaces were also implemented.
- To allow drivers to better isolate different clients using a cached driver connection in succession, if a Conn implements the new SessionResetter interface, database/sql will now call ResetSession before reusing the Conn for a new client.

**Comment by tgulacsi** [comment]
* driver.Rows.Next: it does not use the value of dest, as it has been always Column number of nils.
If it had been the values provided to rows.Scan, the driver could make better decisions about conversions (for example, Number could be converted to int64, float64 of string based on the type of dest[i]).

  * I haven't seen a value/use case of this for goracle, yet.
  * I haven't seen a value/use case of this for goracle, yet.
  * ATM we implement neither, only PrepareContext.
  * I haven't seen a use case for this yet.

**Comment by cjbj** [comment]
Regarding the SessionResetter, ODPI-C has a 'todo' item to support [OCI session tagging](https://docs.oracle.com/database/121/LNOCI/oci09adv.htm#LNOCI16620). Also see [PL/SQL Callback for Session State Fix Up](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnoci/oci-programming-advanced-topics.html#GUID-B853A020-752F-494A-8D88-D0396EF57177). Our benchmarkers like using this kind of feature to really optimize performance. A related user request is at https://github.com/oracle/node-oracledb/issues/258, so there is user interest in this behavior.

**Comment by tgulacsi** [comment]
Thanks, I'll take a look!
