### ISSUE TITLE
CLOB fetch as string?

### ISSUE THREAD

**Issue by cemremengu** [go-goracle/goracle#46]
Is there a way to configure the client to fetch CLOBs as strings ?

**Comment by tgulacsi** [comment]
Not yet. Are you sure you want that?
What about an option (goracle.CLOBAsString) which you can give as an argument to sql.Query?

**Comment by cemremengu** [comment]
That should work as well (if they will enable mapping to a string type of a struct for example), maybe even better in case one does not want them as strings.

The `fetchAsString` idea is actually from [here](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-327-oracledbfetchasstring)

**Comment by tgulacsi** [comment]
PTAL 55f9d9b

**Comment by cemremengu** [comment]
Works great! Thank you so much!!
