### ISSUE TITLE
DML RETURNING INTO host variable not working

### ISSUE THREAD

**Issue by ayalaio** [go-goracle/goracle#53]
How to reproduce:

```go
	var x int
	_, err := db.Exec(`
		  	INSERT INTO dummy (name) 
			VALUES ('myName') RETURNING ID INTO :1;`
                    , &x)
	fmt.Printf("-- %v --", x)
```

`x` will always print
```
-- 0 --
```

**Comment by ayalaio** [comment]
Have tried with DB and Stmt

**Comment by ayalaio** [comment]
Lol, I wasted my Friday night. I could have code something else.

```
sql.Out{Dest: &x}
```

Its the solution.

**Comment by tgulacsi** [comment]
Yes, for all Out params, sql.Out is required as the argument.
(That's why we require Go 1.9, that introduced this - before that, all
strange specific api was required).

D <notifications@github.com> ezt írta (időpont: 2018. márc. 17., Szo, 5:10):
