### ISSUE TITLE
Possible to access a sys_refcursor from a procedure?

### ISSUE THREAD

**Issue by jazzboME** [go-goracle/goracle#54]
I have some existing code that I would like to use where the procedures return a sys_refcursor.

I've tried using sql.Out() with various variable types, and while it doesn't produce an obvious error if I do something like:
```go
var outRecs driver.Rows

_, err = stmt.ExecContext(ctx, sql.Out{Dest: &outRecs})
if err != nil {
	fmt.Println("Error:", err)
}
```

It doesn't give me an error, and while outRecs has something useful -- I can see my field names if I do `fmt.println(outRecs)` -- there is no obvious way to access the components, and I'm pretty sure accessing sql.driver isn't what I should be doing here anyway.

Any tips?

**Comment by cemremengu** [comment]
See #53 maybe that can help

**Comment by jazzboME** [comment]
Yes I agree, `sql.Rows` makes more sense but when I try to use for the destination variable type, I get `Error: 1. arg: unknown type sql.Rows` from the error block above.

`sql.Rows` doesn't seem to implement `driver.Rows` exactly.

**Comment by tgulacsi** [comment]
See what driver.Rows is capable of (https://golang.org/pkg/database/sql/driver/#Rows)
```
cols := make([]interface{}, len(outRecs.Columns()))
for {
    if err := outRecs.Next(cols); err != nil{
        if err == io.EOF {
            break
        }
    }
    log.Println(cols)
}
```

**Comment by jazzboME** [comment]
Well that helps, I thought I had tried outRecs.Columns() before and it didn't work, but obviously it does.

I did have to change your code so that cols was defined as:

`cols := make([]driver.Value, len(outRecs.Columns()))`

Or else it complained that:
`cannot use cols (type []interface {}) as type []driver.Value in argument to outRecs.Next`

But basically, I think I have what I need to get at the data from the refcursor.  Thanks
