### ISSUE TITLE
Unable to use some sql types in statements

### ISSUE THREAD

**Issue by andygarfield** [go-goracle/goracle#55]
There are some types in the `sql` package that I think should be available. The specific types that don't look like they are working are `sql.NullString`, `[]sql.NullString`, and `[]sql.NullFloat64`.

`[]sql.NullFloat64` seems to be handled in `dataSetNumber` [here](https://github.com/go-goracle/goracle/blob/master/stmt.go#L1171), but isn't handled in the `switch` statement starting [here](https://github.com/go-goracle/goracle/blob/master/stmt.go#L596).

`sql.NullString` and `[]sql.NullString` don't appear in either area.

Code that should work:
```sql
CREATE TABLE CHAR_TEST (
  "CHARS" VARCHAR2(10 BYTE),
  "FLOATS" NUMBER(10, 2)
);
```

```golang
package main

import (
	"database/sql"
	"fmt"

	_ "gopkg.in/goracle.v2"
)

func main() {
	connString := "user/password@//host/service"
	db, _ := sql.Open("goracle", connString)

	tx, _ := db.Begin()
	_, err := tx.Exec(
		"INSERT INTO CHAR_TEST VALUES(:CHARS, :FLOATS)",
		[]sql.NullString{
			sql.NullString{"dog", true},
			sql.NullString{"", false},
			sql.NullString{"cat", true},
		},
		[]sql.NullFloat64{
			sql.NullFloat64{3.14, true},
			sql.NullFloat64{12.36, true},
			sql.NullFloat64{0.0, false},
		},
	)
	fmt.Printf("Error: %v\n", err)

	tx.Commit()
}
```

Expected
```
Error: <nil>
```
Got
```
Error: awaited [][]byte/[]string/[]Number, got []sql.NullString ([]sql.NullString{sql.NullString{String:"dog", Valid:true}, sql.NullString{String:"", Valid:false}, sql.NullString{String:"cat", Valid:true}})
```

**Comment by tgulacsi** [comment]
Thanks for the nice, detailed report!

I've added []sql.NullFloat64 in 2935b8e.
But I don't know what to do about sql.NullString, as NULL is indifferentiable to the empty string ("") in Oracle. So (as Oracle DB sees it) 

    "" == sql.NullString{String:"", Valid:false} == sql.NullString{String:"", Valid:true}

I fear that adding NullString would cause more confision than comfort...

**Comment by andygarfield** [comment]
Great, thank you, that makes sense.
