### ISSUE TITLE
Build problem for Windows platform

### ISSUE THREAD

**Issue by tgezginis** [go-goracle/goracle#59]
I'm having trouble when i'm trying to build application for Windows from MacOS. I use this command;
```
GOOS=windows GOARCH=386 go build -o main.exe main.go
```

then it returns like this;
```
# gopkg.in/goracle.v2
../gopkg.in/goracle.v2/orahlp.go:60:2: undefined: describeOnly
../gopkg.in/goracle.v2/orahlp.go:223:26: undefined: PlSQLArrays
../gopkg.in/goracle.v2/orahlp.go:246:32: undefined: VersionInfo
../gopkg.in/goracle.v2/orahlp.go:249:10: undefined: VersionInfo
../gopkg.in/goracle.v2/orahlp.go:255:32: undefined: VersionInfo
../gopkg.in/goracle.v2/orahlp.go:272:19: undefined: VersionInfo
../gopkg.in/goracle.v2/orahlp.go:273:31: undefined: ObjectType
../gopkg.in/goracle.v2/orahlp.go:274:31: undefined: Event
../gopkg.in/goracle.v2/orahlp.go:274:41: undefined: Subscription
../gopkg.in/goracle.v2/orahlp.go:284:27: undefined: conn
../gopkg.in/goracle.v2/orahlp.go:249:10: too many errors
```

PS: I can build or run application for MacOS or Linux platforms without errors.

Details;
MacOS 10.13.3
go1.9.5 darwin/amd64

**Comment by tgulacsi** [comment]
goracle needs CGO to compile in the Oracle OCI libs. So either a
cross-compiling C toolchain is required (and special env vars set
accordingly), or a native env (that's easier, IMHO).

Tolga Gezginiş <notifications@github.com> ezt írta (időpont: 2018. ápr.
12., Cs, 10:17):

**Comment by tgezginis** [comment]
Thanks @tgulacsi 👍 

I built app in Windows with no issues.

**Comment by NogerbekNurzhan** [comment]
@tgezginis hello! How you finally solve this problem? Can you wrote little working  instruction?
