### ISSUE TITLE
Invalid @numberFromText 22062: [-1] ORA-22062: invalid input string [.5] 		ORA-22062: invalid input string [.5]

### ISSUE THREAD

**Issue by vsdutka** [go-goracle/goracle#6]
Reproduce test

func TestFloat(t _testing.T) {
    username, password, sid := oracle.SplitDSN(_dsn)
    conn, err := oracle.NewConnection(username, password, sid, false)
    if err != nil {
        t.Fatalf("Connect error: \"%s\"", err.Error())
    }

```
defer func() {
    err := conn.Close()

    if err != nil {
        t.Errorf("Close error: \"%s\"", err.Error())
    }
}()

cur := conn.NewCursor()
defer cur.Close()
{
    if oci, client, db, err := conn.NlsSettings(cur); err != nil {
        t.Logf("NlsSettings: %s", err)
    } else {
        t.Logf("NLS oci=%s client=%s database=%s", oci, client, db)
    }
}

var v *oracle.Variable
v, err = cur.NewVariable(0, oracle.FloatVarType, 0)
if err != nil {
    t.Fatalf("Error with NewVariable: %v", err)

}
err = v.SetValue(0, 0.5)
if err != nil {
    t.Fatalf("Error with SetValue: %v", err)
}

vv, err1 := v.GetValue(0)
if err != nil {
    t.Fatalf("Error with GetValue: %v", err1)
}
t.Log(vv)
err = v.SetValue(0, vv)
if err != nil {
    t.Fatalf("Error with SetValue: %v", err)
}
```

}

---

oraex_test.go:60: Error with SetValue: @numberFromText 22062: [-1] ORA-22062: invalid input string [.5]
        ORA-22062: invalid input string [.5]

**Comment by tgulacsi** [comment]
Thanks, fixed!

By the way, there's another Oracle client library for Go, which is way more goish, and can handle such cases by binding a *float64: github.com/rana/ora
