### ISSUE TITLE
Character field lengths are quadruple actual size

### ISSUE THREAD

**Issue by andygarfield** [go-goracle/goracle#62]
I tried this on a number of different databases to make sure I wasn't crazy... But it seems like field lengths from `*ColumnType.Length()` are 4 times what they should be.

Not sure it's related to text encoding but I got it through
```sql
SELECT * FROM nls_database_parameters
WHERE PARAMETER IN ('NLS_NCHAR_CHARACTERSET', 'NLS_CHARACTERSET');
```
| PARAMETER | VALUE |
| --- |:---:|
| NLS_NCHAR_CHARACTERSET | AL16UTF16
| NLS_CHARACTERSET | WE8MSWIN1252

And here's how I tested it
```sql
CREATE TABLE "CSP"."IMPORT_TEST" (
  C1 VARCHAR2(20 BYTE), 
  C2 VARCHAR2(1 BYTE),
  C3 NVARCHAR2(20),
  C4 NVARCHAR2(1)
);
```

```golang
package main

import (
	"database/sql"
	"fmt"

	_ "gopkg.in/goracle.v2"
)

func main() {
	connString := "user/password@//host/service"
	db, _ := sql.Open("goracle", connString)

	r, _ := db.Query("SELECT * FROM IMPORT_TEST")
	rts, _ := r.ColumnTypes()
	for _, col := range rts {
		l, _ := col.Length()
		n := col.Name()
		fmt.Printf("Column %s has length %v\n", n, l)
	}
}
```

Expected
```
Column C1 has length 20
Column C2 has length 1
Column C3 has length 20
Column C4 has length 1
```
Got
```
Column C1 has length 80
Column C2 has length 4
Column C3 has length 80
Column C4 has length 4
```

**Comment by tgulacsi** [comment]
Go uses UTF8, so goracle declares to use AL32UTF8. That means it may use 4 bytes to encode 1 character.
AFAIK col.Length() returns what rows.ColumnTypeLength returns - and that is what clientSizeInBytes returned.

**Comment by andygarfield** [comment]
Hm, I think I'm a bit confused.

I can understand that `NVARCHAR2` needs `*ColumnType.Length() * 4` to fit the maximum length of a UTF-8 string. But shouldn't the length of a `VARCHAR2` field always be the what was provided when creating the field (i.e. `C1 VARCHAR2(20 BYTE)` has length `20`)?

**Comment by andygarfield** [comment]
After re-compiling, I'm unfortunately still having this issue.

**Comment by tgulacsi** [comment]
```
$ go test -run=ColumnSize -v
Server: 11.2.0.4.0 [Oracle Database 11g Release 11.2.0.4.0 - 64bit Production]
Client: 12.1.0.2.0
=== RUN   TestColumnSize
=== PAUSE TestColumnSize
=== CONT  TestColumnSize
0. {Name:VC20B OracleType:2001 NativeType:3004 Size:80 SizeInChars:20 DBSize:20 Precision:0 Scale:0 Nullable:true ObjectType:<nil>}
1. {Name:VC1B OracleType:2001 NativeType:3004 Size:4 SizeInChars:1 DBSize:1 Precision:0 Scale:0 Nullable:true ObjectType:<nil>}
2. {Name:NVC20 OracleType:2002 NativeType:3004 Size:80 SizeInChars:20 DBSize:40 Precision:0 Scale:0 Nullable:true ObjectType:<nil>}
3. {Name:NVC1 OracleType:2002 NativeType:3004 Size:4 SizeInChars:1 DBSize:2 Precision:0 Scale:0 Nullable:true ObjectType:<nil>}
4. {Name:VC20C OracleType:2001 NativeType:3004 Size:80 SizeInChars:20 DBSize:20 Precision:0 Scale:0 Nullable:true ObjectType:<nil>}
5. {Name:VC1C OracleType:2001 NativeType:3004 Size:4 SizeInChars:1 DBSize:1 Precision:0 Scale:0 Nullable:true ObjectType:<nil>}
--- PASS: TestColumnSize (0.26s)
        z_test.go:1447: Column "VC20B" has length 80
        z_test.go:1447: Column "VC1B" has length 4
        z_test.go:1447: Column "NVC20" has length 80
        z_test.go:1447: Column "NVC1" has length 4
        z_test.go:1447: Column "VC20C" has length 80
        z_test.go:1447: Column "VC1C" has length 4
PASS
ok      gopkg.in/goracle.v2     0.641s
```

So yes, the DB (ODPI-C) reports it correctly: for every column, it reports the DB size in bytes, the client size in bytes and the size in char.

# What to report as ColumnSize?
## Size in char
The size in char is tempting, but Oracle's Unicode support is not too strong, and "char" is an unknown idea in Unicode.

## DB size
This would be correct, but misleading for client code.

## client size in bytes
This a safe choice...

Opinion?

**Comment by andygarfield** [comment]
It seems to me that the Go documentation is too ambiguous to make a decision.
[*ColumnType.Length](https://golang.org/pkg/database/sql/#ColumnType.Length)
If I were to venture a guess, I would think the "client size in bytes" option is the correct one, but I can't know for sure. This may need to be cleared up in their docs.

**Comment by tgulacsi** [comment]
Care to open an issue for it?

Till that clears up, you can use the user_tab_cols view.
BTW what doy you need? Why is 4*chars is wrong?

Andy Garfield <notifications@github.com> ezt írta (időpont: 2018. máj. 10.,
Cs, 16:19):

**Comment by andygarfield** [comment]
I'll write up an issue with them.

I'm not very familiar with how Oracle allocates space for data. In this line, I'm assuming `Size:80` represents the client size?
```
0. {Name:VC20B OracleType:2001 NativeType:3004 Size:80 SizeInChars:20 DBSize:20 Precision:0 Scale:0 Nullable:true ObjectType:<nil>}
```

**Comment by tgulacsi** [comment]
Yes, Size is "SizeInBytes".
We could add some logic that says that if the DB uses an 8bit charset,
which is representable by 1 byte UTF8 (i.e. ISO8859-1, ASCII) then DBSize
is just great for Size.
Otherwise, you have to use SizeInChars * 4, which is ClientSizeInBytes.

Andy Garfield <notifications@github.com> ezt írta (időpont: 2018. máj. 10.,
Cs, 17:53):
