### ISSUE TITLE
PingContext with timeout not work

### ISSUE THREAD

**Issue by nh-live** [go-goracle/goracle#63]
oradb,err := sql.Open("goracle", "aa/123456@testdb")
	if err != nil{
		logs.Error(err.Error())
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5 * time.Second)
	defer cancel()
	
	err = oradb.PingContext(ctx)
	if err != nil{
		logs.Error(err.Error())
		return
	}

The above code ping function is not connected to the database timeout and returns to an average of 25 seconds instead of 5 seconds.

**Comment by tgulacsi** [comment]
What version? It should've been fixed in a6d7a74babf5c1af39c8261d0bfb9bbd3c192a74 (v2.1.22)

**Comment by nh-live** [comment]
goracle:v2.4.0
oracle instance:12.2.0.1.0
go:1.10

**Comment by tgulacsi** [comment]
Ok, I can reproduce it, if the server is unavailable: not the Ping, but the Open times out.

The hard thing is that this is the database/sql/driver's Open, and database/sql calls it when needs it, and does not provide a context or a timeout.

We can take a new "connTimeout" param in the connection string to sidestep this, but I'm not sure this would worth it.
