### ISSUE TITLE
are there any  common bulk way

### ISSUE THREAD

**Issue by dfy167** [go-goracle/goracle#64]
we can use  db.Exec("INSERT INTO table (a, b) VALUES (:1, :2)", []int{1, 2}, []string{"a", "b"})
but most time we get []someStruct  and then  to  []int, []string ...
when  []interface{} ,[]interface{},[]interface{} ....  errors get unknown type []interface {}
how to accomplish a common way?

**Comment by tgulacsi** [comment]
See https://github.com/tgulacsi/go/blob/master/dbcsv/csvload/csvload.go#L226 

    a := interface{}{[]int{1,2}}
    b := interface{}{[]string{"a", "b"}}
    db.Exec("INSERT INTO table (a,b) VALUES (:1, :2)", a, b)

The slice given as argument must be "typed" ([]int, []string ...), but you can treat it as an interface{}.

**Comment by dfy167** [comment]
wow... ths.
