### ISSUE TITLE
Building static binaries with libc linked in

### ISSUE THREAD

**Issue by oxplot** [go-goracle/goracle#65]
I'm trying to build a static binary using:

```sh
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o main main.go
```
where `main.go` is:

```go
package main

import (
	"database/sql"

	_ "gopkg.in/goracle.v2"
)

func main() {
	_, err := sql.Open("goracle", "user/pass@host:port:db")
	if err != nil {
		panic(err)
	}
}
```

and I get:
```
# gopkg.in/goracle.v2
../../../gopkg.in/goracle.v2/orahlp.go:60:2: undefined: describeOnly
../../../gopkg.in/goracle.v2/orahlp.go:223:26: undefined: PlSQLArrays
../../../gopkg.in/goracle.v2/orahlp.go:246:32: undefined: VersionInfo
../../../gopkg.in/goracle.v2/orahlp.go:249:10: undefined: VersionInfo
../../../gopkg.in/goracle.v2/orahlp.go:255:32: undefined: VersionInfo
../../../gopkg.in/goracle.v2/orahlp.go:272:19: undefined: VersionInfo
../../../gopkg.in/goracle.v2/orahlp.go:273:30: undefined: ObjectType
../../../gopkg.in/goracle.v2/orahlp.go:274:31: undefined: Event
../../../gopkg.in/goracle.v2/orahlp.go:274:41: undefined: Subscription
../../../gopkg.in/goracle.v2/orahlp.go:284:27: undefined: conn
../../../gopkg.in/goracle.v2/orahlp.go:249:10: too many errors
```

For reference, `go build` builds without any errors.

Any ideas?

**Comment by cemremengu** [comment]
What's your gcc version?

**Comment by oxplot** [comment]
```
[mike@niagara ~]$ gcc --version
gcc (GCC) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by oxplot** [comment]
I actually just came across https://github.com/oracle/docker-images/issues/507 which seems to mean, it's impossible to do this, with go or not.

**Comment by tgulacsi** [comment]
Not too fast.
goracle.v2 uses ODPI-C, a small helper lib under the odpi dir.
It embeds those files - include the #cgo directives at compile, may help.

And ODPI-C does NOT nees libclntsh.so, at least not at compile time: it
dlopens it at runtime only.

Though I haven't tried this static compilation, AFAIK it may be feasible.

Mansour Behabadi <notifications@github.com> ezt írta (időpont: 2018. máj.
31., Cs 9:10):

**Comment by tgulacsi** [comment]
```
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build  -tags netgo -ldflags "-w -extldflags '-static -I$GOPATH/src/gopkg.in/goracle.v2/odpi/include -I$GOPATH/src/gopkg.in/goracle.v2/odpi/src -I$GOPATH/src/gopkg.in/goracle.v2/odpi/embed -ldl' " -o main main.go
```
compiles, but SIGSEGVs at runtime.

**Comment by oxplot** [comment]
hmmm, mine doesn't even compile:

```
# command-line-arguments
/usr/lib/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lclntsh
collect2: error: ld returned 1 exit status
```

**Comment by tgulacsi** [comment]
Where do you have `-lclntsh` ? You don't need that.

**Comment by cjbj** [comment]
@oxplot think of Instant Client as being part of the base OS configuration.  Just like you need various system packages installed for specific application functionality, you need Instant Client installed if you want to connect to Oracle.

**Comment by oxplot** [comment]
@cjbj unfortunately, this analogy breaks down for applications that support multiple databases. For instance in my case, the application supports connecting to MySQL, PostgreSQL, Oracle and SQLite. As it sits right now, the user is required to have Oracle client installed, even if they only want to use the app with PostgreSQL.

**Comment by oxplot** [comment]
Given https://github.com/go-goracle/goracle/issues/65#issuecomment-394240078, I guess providing a way to manually initialize the driver (instead of having it automatically initialize on import) is a way to work around this issue.

**Comment by cjbj** [comment]
cx_Oracle, for one, is the same: you can import the driver but ODPI-C is not initialized until first connection.

**Comment by cjbj** [comment]
@tgulacsi that was fast!

**Comment by oxplot** [comment]
wow, thanks a lot @tgulacsi

**Comment by margem** [comment]
I'm trying compile my project running this command: **CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build  -tags netgo -ldflags "-w -extldflags '-static -I$GOPATH/src/gopkg.in/goracle.v2/odpi/include -I$GOPATH/src/gopkg.in/goracle.v2/odpi/src -I$GOPATH/src/gopkg.in/goracle.v2/odpi/embed -ldl' " -o main main.go**

But, I'm receive

 /usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by theonewolf** [comment]
@cjbj unfortunately there are many environments where you can't install runtimes or dependencies easily (especially if they need special paths---whoever owns the environment may not allow it or may not have the expertise to deploy without misconfiguration).  I would actually assert that runtimes and external environment dependencies are now a hindrance to product development and adoption.

Modern languages like Rust and Go are making static compilation easy to support.

By eliminating friction for deployment, you can run on more devices and platforms.

Rust explains this with (https://doc.rust-lang.org/1.9.0/book/advanced-linking.html#linux):

> This binary can be copied to almost any Linux machine with the same machine architecture and run without issues.

Static compilation lets us to eliminate classes of operational bugs due to environmental misconfigurations of binary dependencies.

**Comment by cjbj** [comment]
@theonewolf I understand the arguments and it is one of many things on my personal wish list.  

I come up against technical and security concerns (+ normal cost/benefit discussions) whenever I raise it, so any change in direction is not straightforward.

**Comment by theonewolf** [comment]
@cjbj yeah, we integrate across the board with Oracle and it's always a pain point (distribution etc.).  Even outside of Go, we hit it with Python (`cx-oracle`).

Well, if I do implement a crazy wrapping method to make things "more" static I'll let the community know.

I think the world's typical solution is to go down the road of containers or virtual machines.  Both camps are basically following the static philosophy: all-in-one giant binary blobs.

Anyways, thanks for the insight you are able to offer to the community.
