### ISSUE TITLE
does support lastinsertid?

### ISSUE THREAD

**Issue by yzwlcc** [go-goracle/goracle#68]
hi, thx for developing this project

does goracle support lastinsertid?

I wirte the code below, but not useful

```
var iid int
db.Exec(`insert into t1 values (t1idseq.nextval, :1, :2, :3) returning id into :4`,  name,  address,  nickname, &iid)
```
Is correcty writing this way?..

thanks

**Comment by tgulacsi** [comment]
No. Oracle does not know autoincrement, and does not know such id.
But your code is almost good, though it needs sql.Out:

    db.Exec(`insert into t1 values (t1idseq.nextval, :1, :2, :3) returning id into :4`, name, address, nickname, sql.Out{Dest:&iid})

**Comment by daniil-konovalenko** [comment]
Hey @tgulacsi, thanks for your answer. I tried your solution, but it does not work for some reason. It works with `[go-oci8](https://github.com/mattn/go-oci8)` though. Do you have any thoughts on why this can happen?

**Comment by daniil-konovalenko** [comment]
It works! Thank you so much!

**Comment by tgulacsi** [comment]
It's in v2.5.1 now.
