### ISSUE TITLE
SIGTRAP on MacOS X

### ISSUE THREAD

**Issue by orichards** [go-goracle/goracle#69]
To reproduce the error create some continuously running goroutine (like http.Server) and access database using something like db.Exec from it and then stop the process using CTRL+C for example. 

Operation system: OSX 10.12.6 

> SIGTRAP: trace trap
> PC=0x4054472 m=0 sigcode=1
> 
> goroutine 0 [idle]:
> runtime.morestack()
> 	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:451 +0x22
> 
> goroutine 1 [IO wait]:
> internal/poll.runtime_pollWait(0x4694f50, 0x72, 0x0)
> 	/usr/local/Cellar/go/1.10/libexec/src/runtime/netpoll.go:173 +0x57
> internal/poll.(*pollDesc).wait(0xc420114018, 0x72, 0x0, 0x0, 0x0)
> 	/usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_poll_runtime.go:85 +0x9b
> internal/poll.(*pollDesc).waitRead(0xc420114018, 0xffffffffffffff00, 0x0, 0x0)
> 	/usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
> internal/poll.(*FD).Accept(0xc420114000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_unix.go:372 +0x1a8
> net.(*netFD).accept(0xc420114000, 0xc420096940, 0xc420057d10, 0x4003ed8)
> 
> goroutine 5 [select]:
> database/sql.(*DB).connectionOpener(0xc420096820, 0x437e660, 0xc420062280)
> 	/usr/local/Cellar/go/1.10/libexec/src/database/sql/sql.go:935 +0x119
> created by database/sql.OpenDB
> 	/usr/local/Cellar/go/1.10/libexec/src/database/sql/sql.go:634 +0x178
> 
> goroutine 6 [select]:
> database/sql.(*DB).connectionResetter(0xc420096820, 0x437e660, 0xc420062280)
> 	/usr/local/Cellar/go/1.10/libexec/src/database/sql/sql.go:948 +0x12a
> created by database/sql.OpenDB
> 	/usr/local/Cellar/go/1.10/libexec/src/database/sql/sql.go:635 +0x1ae
> 
> rax    0x17
> rbx    0x44ec4a0
> rcx    0x4057ee5
> rdx    0x0
> rdi    0x2
> rsi    0x4348325
> rbp    0xc4200099f0
> rsp    0xc420009940
> r8     0x5107258
> r9     0x1320000
> r10    0xc420009798
> r11    0x202
> r12    0x0
> r13    0xf3
> r14    0x33
> r15    0x80
> rip    0x4054472
> rflags 0x202
> cs     0x2b
> fs     0x0
> gs     0x0
> 
> Process finished with exit code 2

**Comment by tgulacsi** [comment]
Sorry, I don't have a Mac, and haven't ever seen a SIGTRAP.

I'd register a syscall.Notify which closes the context.Context given to
ExecContext/QueryContext, which will Break cleanly.

Oleg Richards <notifications@github.com> ezt írta (időpont: 2018. jún. 20.,
Sze, 16:57):

**Comment by orichards** [comment]
Could you please provide a small code snippet on how to do it, especially in relation to DB connection.

**Comment by tgulacsi** [comment]
```
func main() {
  db, err := sql.Open("goracle", "...")
  defer db.Close()
  ctx, cancel := globalContext(context.Background())
  defer cancel()

  db.ExecContext(ctx, "...")
}


func globalContext(ctx context.Context) (context.Context, context.CancelFunc) {
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM, syscall.SIGINT, syscall.SIGHUP)
	var cancel context.CancelFunc
	ctx, cancel = context.WithCancel(ctx)
	go func() {
		<-sigCh
		signal.Stop(sigCh)
		cancel()
	}()
	return ctx, cancel
}
```

But https://unix.stackexchange.com/questions/21892/what-does-trace-trap-mean-when-reported-by-zsh says this is something like SIGSEGV on Linux - the program's fault.

Do you have a data race? What if you compile && run with `go install -race ` ?

**Comment by orichards** [comment]
I've tried and unfortunately it does not help. In my case I'm executing query within http.Handler. If I did it at least once, then when I stop application - it crashes with trace I provided before.

**Comment by tgulacsi** [comment]
Sorry, I haven't mentioned that you can try to include the syscall.SIGTRAP
in the list of signals in Notify's arguments.

Oleg Richards <notifications@github.com> ezt írta (időpont: 2018. jún. 20.,
Sze, 20:41):
