### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by anuragsoni** [go-goracle/goracle#7]
I was following the installation instructions for the package. I installed the oracle instant client and the sdk and then used the env script to verify that I had set the correct environment variables. When i try to go get the package I'm getting an error 
warning: libnnz11.so, needed by /usr/lib/oracle/11.2/client64/lib/libclntsh.so, not found

I'm working on Ubuntu 14.04 and with instant client version 11.2.0.4

**Comment by tgulacsi** [comment]
Hi,

I've added some instructions about LD_LIBRARY_PATH - I think that's the
missing piece.

---
https://onename.com/tgulacsi

2015-08-14 22:59 GMT+02:00 Anurag <notifications@github.com>:

**Comment by anuragsoni** [comment]
Thanks. That helped. I'll close the issue
