### ISSUE TITLE
cursors not closing

### ISSUE THREAD

**Issue by bpsnifer** [go-goracle/goracle#70]
Starting with version 2.5 cursors not closing
Executing query
```
	_, err := db.DB().Exec(
		"BEGIN PO.OUTER_REF.P_DELETE_OUTER_REF(:1, :2); END;",
		sourceSystem, entityType,
	)
```
cursor remains open..

After a while, we get an error: `dpiStmt_execute(mode=32 arrLen=-1): ORA-01000: maximum open cursors exceeded`

In version 2.4 all ok

**Comment by tgulacsi** [comment]
See line 160 in stmt.go - the function *statemnent.close.
Comment out the line with C.dpiStmt_getQueryInfo and try again!

bpsnifer <notifications@github.com> ezt írta (időpont: 2018. jún. 22., P,
10:22):
