### ISSUE TITLE
go get doesn't get the latest package

### ISSUE THREAD

**Issue by nanthinimuniapan** [go-goracle/goracle#72]
Hi, I just want to highlight the command: 
`go get gopkg.in/goracle.v2
`
doesn't get the latest code from the codebase but a subsequent git pull is required in the gopkg.in/goracle.v2 directory.

**Comment by tgulacsi** [comment]
```
export GOPATH=/tmp/go; mkdir $GOPATH; 
go get gopkg.in/goracle.v2
cd $GOPATH/src/gopkg.in/goracle.v2
git log|head
```
gives
```
commit 66d493adc9a2278b0bb1b2138b8020aa821dce0a
Author: Tamás Gulácsi <tgulacsi78@gmail.com>
Date:   Fri Jun 22 11:47:15 2018 +0200

    bump version
```

which is the latest tagged (v2.5.2) version.
The current master differs from this: `git diff master`
```
$ git diff v2.5.2
diff --git a/version.go b/version.go
index 044be52..d160c44 100644
--- a/version.go
+++ b/version.go
@@ -5,4 +5,4 @@ package goracle
 //go:generate mv odpi-2.4.0 odpi

 // Version of this driver
-const Version = "v2.5.2"
+const Version = "v2.5.3"
```

only with the version number, which is incremented to help me avoid the error of tagging the next version with wrong `Version`.

**Comment by nanthinimuniapan** [comment]
Thanks for the reply @tgulacsi. I needed to do insertion with returning id option and realised  only the latest version i.e v2.5.3 supports it. Anyway thanks for the clarification!
