### ISSUE TITLE
can not install in windows 7 and go version go1.10.1 windows/386

### ISSUE THREAD

**Issue by e4x** [go-goracle/goracle#73]
I just install use "go get" 
go get gopkg.in/goracle.v2
it's return : 

> 
>  gopkg.in/goracle.v2                                                                                                                            
> GOPATH\src\gopkg.in\goracle.v2\conn.go:294: type [1073741824]_Ctype_struct_dpiData larger than address space                                     
> GOPATH\src\gopkg.in\goracle.v2\conn.go:294: type [1073741824]_Ctype_struct_dpiData too large                                                     
> GOPATH\src\gopkg.in\goracle.v2\rows.go:297: type [1073741824]_Ctype_struct_dpiData larger than address space                                     
> GOPATH\src\gopkg.in\goracle.v2\rows.go:297: type [1073741824]_Ctype_struct_dpiData too large                                                     
> GOPATH\src\gopkg.in\goracle.v2\stmt.go:338: type [1073741824]_Ctype_struct_dpiData larger than address space                                     
> GOPATH\src\gopkg.in\goracle.v2\stmt.go:338: type [1073741824]_Ctype_struct_dpiData too large                                                     
> GOPATH\src\gopkg.in\goracle.v2\subscr.go:48: type [1073741824]_Ctype_struct_dpiSubscrMessageRow larger than address space                        
> GOPATH\src\gopkg.in\goracle.v2\subscr.go:48: type [1073741824]_Ctype_struct_dpiSubscrMessageRow too large                                        
> GOPATH\src\gopkg.in\goracle.v2\subscr.go:62: type [1073741824]_Ctype_struct_dpiSubscrMessageTable larger than address space                      
> GOPATH\src\gopkg.in\goracle.v2\subscr.go:62: type [1073741824]_Ctype_struct_dpiSubscrMessageTable too large                                      
> GOPATH\src\gopkg.in\goracle.v2\subscr.go:62: too many errors                                                                                     
> exit status 2     

my gcc version =>  gcc version 7.3.0 (Rev2, Built by MSYS2 project)
go version => go version go1.10.1 windows/386

                                                                                                                               

can u help me?

**Comment by tgulacsi** [comment]
Can you try the current master (4a4fae4)? (```cd $GOPATH/src/gopkg.in/goracle.v2 && git remote add origin https://github.com/go-goracle/goracle.git && git fetch origin && git checkout -b master origin/master```)

I don't have a '386 env at hand.

**Comment by e4x** [comment]
I try the current master (4a4fae4)  version, the same error.
$ git branch -v
* master 4a4fae4 limit maxArraySize - helps #73

$ go get
# gopkg.in/goracle.v2
.\conn.go:294: type [134217728]_Ctype_struct_dpiData larger than address space
.\conn.go:294: type [134217728]_Ctype_struct_dpiData too large
.\rows.go:297: type [134217728]_Ctype_struct_dpiData larger than address space
.\rows.go:297: type [134217728]_Ctype_struct_dpiData too large
.\stmt.go:338: type [134217728]_Ctype_struct_dpiData larger than address space
.\stmt.go:338: type [134217728]_Ctype_struct_dpiData too large
.\subscr.go:62: type [134217728]_Ctype_struct_dpiSubscrMessageTable too large
.\subscr.go:77: type [134217728]_Ctype_struct_dpiSubscrMessageQuery too large
exit status 2

**Comment by tgulacsi** [comment]
Ok, another try: 77a077c
If this works, I'll remove the size printouts.

**Comment by e4x** [comment]
I git pull update to 77a077c
$ go get
\# gopkg.in/goracle.v2
.\conn.go:308: type [214748363]_Ctype_struct_dpiData larger than address space
.\conn.go:308: type [214748363]_Ctype_struct_dpiData too large
.\rows.go:297: type [214748363]_Ctype_struct_dpiData larger than address space
.\rows.go:297: type [214748363]_Ctype_struct_dpiData too large
.\stmt.go:338: type [214748363]_Ctype_struct_dpiData larger than address space
.\stmt.go:338: type [214748363]_Ctype_struct_dpiData too large
.\subscr.go:48: type [214748363]_Ctype_struct_dpiSubscrMessageRow too large
.\subscr.go:62: type [214748363]_Ctype_struct_dpiSubscrMessageTable too large
.\subscr.go:77: type [214748363]_Ctype_struct_dpiSubscrMessageQuery larger than address space
.\subscr.go:77: type [214748363]_Ctype_struct_dpiSubscrMessageQuery too large
.\subscr.go:77: too many errors
exit status 2

**Comment by tgulacsi** [comment]
1. use `go install` on the freshly checked out / pulled source
2. please replace maxArraySize in `conn.go` with some constant (start with `1<<27 - 1`, lower the 27) and try `go install` with it.
3. report here the successful constant.

**Comment by e4x** [comment]
replace maxArraySize constant 1<<27 ~ 1<<30, it can install successful, big then 30

> const maxArraySize = (1<<30)/C.sizeof_dpiSubscrMessageTable - 1

be 31 ，it return：

$ go install
\# gopkg.in/goracle.v2
.\conn.go:309: type [107374181]_Ctype_struct_dpiData too large
.\rows.go:297: type [107374181]_Ctype_struct_dpiData too large
.\stmt.go:338: type [107374181]_Ctype_struct_dpiData too large
.\subscr.go:77: type [107374181]_Ctype_struct_dpiSubscrMessageQuery too large
exit status 2

**Comment by tgulacsi** [comment]
So,

    const maxArraySize = (1<<30)/C.sizeof_dpiSubscrMessageTable - 1

works?

What if you 

    const maxArraySize = 1<<26

or 

    const maxArraySize = 1<<25

?

**Comment by e4x** [comment]
> const maxArraySize = 1<<25
works

const maxArraySize = 1<<26
not

**Comment by tgulacsi** [comment]
Ok, I'll stick with `(1<<30)/C.sizeof_dpiSubscrMessageTable - 1`
