### ISSUE TITLE
Support for ReadOnly Transactions

### ISSUE THREAD

**Issue by rvegas** [go-goracle/goracle#74]
https://github.com/go-goracle/goracle/blob/a577a85de5c36ee2ff47330e17895befcdef9232/conn.go#L175-L177

This has been a common limit for a while, is there a specific issue with the C libraries causing this? Is there a possibility to be able to open **RO** in a near future?

Thanks.

**Comment by tgulacsi** [comment]
If someone points me to the right direction, I'll implement it.
@anthony-tuininga, @cjbj ?

**Comment by anthony-tuininga** [comment]
It can be done easily enough by simply issuing the statement "set transaction read only" with a cursor. See this [documentation](https://docs.oracle.com/database/121/SQLRF/statements_10005.htm#SQLRF01705).

**Comment by cemremengu** [comment]
You seriously deserve a maintainer of the year award @tgulacsi 👏
