### ISSUE TITLE
Pointer Types do not work with array insert

### ISSUE THREAD

**Issue by volkmarbuehringer** [go-goracle/goracle#76]
I tried my luck with inserting the pointer types as array insert
and it doesn't work 
only plain arrays work:

		if r, err := tx.Exec(` INSERT INTO gag
				VALUES (:1, :2 )`,
			[]string{"gaga1", "gaga3", "gaga4"},
			[]string{"agaga1", "agaga3", "agaga4"},
		); err != nil {
			panic(err)
		} else {
			if v, err := r.RowsAffected(); err != nil {
				panic(err)
			} else {
				fmt.Println("dat", v)
			}
             }

**Comment by tgulacsi** [comment]
Yes. Work as intended.
