### ISSUE TITLE
performance is so bad ? Am I using goracle.v2 code wrong?

### ISSUE THREAD

**Issue by dingkaich** [go-goracle/goracle#77]
My table define as below:
create table DeviceLicenseTable (
	devID	        	number(12) not null,
	key	            	varchar(256) not null,
	allocValue		number(12) not null,
	usedValue       	number(12) default 0,
	timestamp	    	number(20),
    capValue            number(12) default 0,
    constraint 		PK_DeviceLicenseTable primary key (devID, key) using index
)tablespace MC_DMSMDB;

this is my demo golang code:
func queryDeviceLicense() ([]DeviceLicense, error) {
	var start, end time.Time
	start = time.Now()

	if db == nil {
		log.Println("db is nil")
		return nil, nil
	}

	// sql := fmt.Sprintf("SELECT * FROM DeviceLicenseTable ")
	rows, err := db.Query("SELECT * FROM DeviceLicenseTable", goracle.FetchRowCount(2048))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	licenses := make([]DeviceLicense, 0, 8)

	for rows.Next() {
		var entry DeviceLicense

		err = rows.Scan(&entry.DevID, &entry.Key, &entry.Value, &entry.Used, &entry.Timestamp, &entry.Cap)
		if err != nil {
			return nil, err
		}
		licenses = append(licenses, entry)
		if err := rows.Err(); err != nil {
			return nil, err
		}
	}
	end = time.Now()
	log.Printf("[queryDeviceLicense Total time] len=%d %f", len(licenses), end.Sub(start).Seconds())

	return licenses, nil
}
func updatelicense(licenses []DeviceLicense) error {
	var start, end time.Time
	start = time.Now()

	tx, err := db.Begin()
	if err != nil {
		return err
	}

	i := 0
	sql := fmt.Sprintf("UPDATE DeviceLicenseTable SET allocvalue=:1, timestamp=:2 WHERE devid=:2 and key=:3")
	stmt, err := tx.Prepare(sql)
	if err != nil {
		tx.Rollback()
		return err
	}
	defer stmt.Close()
	for _, devLicense := range licenses {
		_, err = stmt.Exec(devLicense.Value, devLicense.Timestamp, devLicense.DevID, devLicense.Key)
		if err != nil {
			tx.Rollback()
			return err
		}
		i++
	}

	err = tx.Commit()
	if err != nil {
		return err
	}
	end = time.Now()
	log.Printf("[updatelicense Total time] len=%d %f", i, end.Sub(start).Seconds())
	return nil
    
I use cpp lang  sqlapi client to compare with goracle in same enviroment. cpp demo code:
{
    cmd.SetExecBatch(true);
    cmd.SetBatchMaxRowCount(vDeviceLicense.size());
    osm.str("");
    osm.clear();
    osm << "update devicelicensetable set allocvalue=:allocvalue,usedvalue=:usedvalue,Timestamp=:Timestamp,capvalue=:capvalue "
    << "where devid=:devid and key=:key ";
    cmd.setCommandText(osm.str().c_str());  
    cmd.SetBatchMaxRowCount(vDeviceLicense.size());
    for (int i=0; i<vDeviceLicense.size();i++)
    {
        cmd.ParamData(i,"allocvalue").setAsLong() = vDeviceLicense[i].Value;
        cmd.ParamData(i,"usedvalue").setAsLong() = vDeviceLicense[i].Used+1;
        cmd.ParamData(i,"Timestamp").setAsNumeric() = (double)vDeviceLicense[i].Timestamp;
        cmd.ParamData(i,"capvalue").setAsLong() = vDeviceLicense[i].DevID;
        cmd.ParamData(i,"devid").setAsLong() = vDeviceLicense[i].DevID;
        cmd.ParamData(i,"key").setAsString() = (char *)vDeviceLicense[i].Key.c_str();
    } 
    cmd.Execute(vDeviceLicense.size());
    cmd.SetExecBatch(false);
    con.Commit();
}

Result Compare:
gooracle.v2 : using stmt, goracle.v2 use 97 seconds
 DK:oracle:\iptv > ./oracletest
2018/07/11 11:50:31 [queryDeviceLicense Total time] len=9003 0.224609
2018/07/11 11:52:09 [updatelicense Total time] len=9003 97.458228

SQLAPI(http://www.sqlapi.com/): cpp sqlapi use less than 1 seconds
mc@SZX1000367778:~/bin> ./test
test begin
begin 1531276483
query 1531276484   size=9003
update 1531276484
test over
query cost1:1
update cost2:0

Am I using goracle.v2 code wrong  so that perform so bad ????

**Comment by tgulacsi** [comment]
You can put the "if rows.Err() != nil " check outside the loop - rows.Next will return false if sth errored out.

The update is known to take a lot of time if done this one-peace-a-time way.

That's why we have the same as you presented in the cpp code, like Python's cx_Oracle's executeMany: use []interface{} for params, like 

```
stmt, err := tx.Prepare(sql)
if err != nil {
	tx.Rollback()
	return err
}
values := make([]interface{}, len(licenses))
timestamps := make([]interface{}, len(licenses))
devids := make([]interface{}, len(licenses))
keys := make([]interface{}, len(licenses))
for i, license := range licenses {
    values[i] = license.Value
    timestamps[i] = license.Timestamp
    devids[i] = license.DevID
    keys = license.Key
}

const qry = "UPDATE DeviceLicenseTable SET allocvalue=:1, timestamp=:2 WHERE devid=:3 and key=:4"
if _, err := tx.Exec(qry, values, timestamps, devids, keys); err != nil {
   tx.Rollback()
   return errors.Wrap(err, qry)
}
}
```

The general case is a little bit more comples, see https://github.com/tgulacsi/go/blob/master/dbcsv/csvdump/csvdump.go#L308

**Comment by tgulacsi** [comment]
Another example is in #76.

**Comment by dingkaich** [comment]
first , 3ks tgulacsi.

Second,
I find your code did not support interface{} when I use below code:
func updatelicense3(licenses []DeviceLicense) error {
	var start, end time.Time
	start = time.Now()
	tx, err := db.Begin()
	if err != nil {
		return err
	}

	// values := make([]int32, len(licenses))
	// timestamps := make([]int64, len(licenses))
	// devids := make([]int32, len(licenses))
	// keys := make([]string, len(licenses))
	values := make([]interface{}, len(licenses))
	timestamps := make([]interface{}, len(licenses))
	devids := make([]interface{}, len(licenses))
	keys := make([]interface{}, len(licenses))

	for i, license := range licenses {
		values[i] = license.Value + 1
		timestamps[i] = license.Timestamp
		devids[i] = license.DevID
		keys[i] = license.Key
	}
	const sql = "UPDATE DeviceLicenseTable SET allocvalue=:1, timestamp=:2 WHERE devid=:3 and key=:4"
	if _, err := tx.Exec(sql, values, timestamps, devids, keys); err != nil {
		tx.Rollback()
		return err
	}

	err = tx.Commit()
	if err != nil {
		return err
	}
	end = time.Now()
	log.Printf("[updatelicense Total time] len=%d %f", len(licenses), end.Sub(start).Seconds())
	return nil
}

Error Report:
DK:oracle:\iptv > ./oracletest
2018/07/11 14:19:53 [queryDeviceLicense Total time] len=9003 0.211135
2018/07/11 14:19:53 1. arg: unknown type []interface {}

I use int32 string instead of interface{}. it works:
Test Report:
DK:oracle:\iptv > ./oracletest
2018/07/11 14:22:06 [queryDeviceLicense Total time] len=9003 0.212482
2018/07/11 14:22:06 [updatelicense Total time] len=9003 0.246910
DK:oracle:\iptv > go build
DK:oracle:\iptv > ./oracletest
2018/07/11 14:23:40 [queryDeviceLicense Total time] len=9003 0.214389
2018/07/11 14:23:40 [updatelicense Total time] len=9003 0.266285
DK:oracle:\iptv > ./oracletest
2018/07/11 14:24:02 [queryDeviceLicense Total time] len=9003 0.218296
2018/07/11 14:24:02 [updatelicense Total time] len=9003 0.194542

It looks very nice!!

Third, did stmt support this  by send slice in stmt.exec ?

**Comment by dingkaich** [comment]
as I know, you also work in rana/ora before .
My last project use rana/ora.v3 .. Did rana/ora.v3 also support this slice method for more speed ?

**Comment by tgulacsi** [comment]
Yes, I've rewritten rana/ora.v3 to rana/ora.v4.
I remember only vaguely, but I think yes, it does.

Kai ding <notifications@github.com> ezt írta (időpont: 2018. júl. 11., Sze,
9:03):
