### ISSUE TITLE
Can go-oracle support cross compile ?

### ISSUE THREAD

**Issue by xxh2000** [go-goracle/goracle#78]
Can go-oracle support cross compile ? when I compile linux version from windows system, there was some errors as blow:

vendor\github.com\go-goracle\goracle\orahlp.go:60:2: undefined: describeOnly
vendor\github.com\go-goracle\goracle\orahlp.go:223:26: undefined: PlSQLArrays
vendor\github.com\go-goracle\goracle\orahlp.go:246:32: undefined: VersionInfo
vendor\github.com\go-goracle\goracle\orahlp.go:249:10: undefined: VersionInfo
vendor\github.com\go-goracle\goracle\orahlp.go:255:32: undefined: VersionInfo
vendor\github.com\go-goracle\goracle\orahlp.go:272:19: undefined: VersionInfo
vendor\github.com\go-goracle\goracle\orahlp.go:273:30: undefined: ObjectType
vendor\github.com\go-goracle\goracle\orahlp.go:274:31: undefined: Event
vendor\github.com\go-goracle\goracle\orahlp.go:274:41: undefined: Subscription
vendor\github.com\go-goracle\goracle\orahlp.go:284:27: undefined: conn
vendor\github.com\go-goracle\goracle\orahlp.go:249:10: too many errors

**Comment by cemremengu** [comment]
See #61 if that helps

**Comment by tgulacsi** [comment]
Yes and no.
Yes: It does support cross-compilation, if you enable cgo and provide the proper cross-compilation C programs with environment variables.
No: this is hard, it is waaay easier to compile on the target, if possible.

**Comment by tgulacsi** [comment]
I haven't tried, but https://github.com/karalabe/xgo may worth a shot.

**Comment by xxh2000** [comment]
Thank you !  I think it is also hard。I used https://github.com/mitchellh/gox to cross compile and throw me same errors 。But it was successful when I cross compile other golang projects。 So I come to the conclusion that go-oracle is not support cross compile。

**Comment by tgulacsi** [comment]
I've tried and it works with karalabe/xgo:

    go get -u github.com/karalabe/xgo
    xgo --targets=linux/* github.com/tgulacsi/go/dbcsv/csvdump

**Comment by NogerbekNurzhan** [comment]
@xxh2000 hello! How finally you solve this problem? Can you show little working instruction?

**Comment by NogerbekNurzhan** [comment]
@tgulacsi hello! Where I exactly need to use `xgo` library?

**Comment by tgulacsi** [comment]
xgo is a command-line program to compile in Docker containers - for example like in https://github.com/go-goracle/goracle/issues/78#issuecomment-404085737 .

**Comment by NogerbekNurzhan** [comment]
Am I to understand that firstly I need to enter inside docker container: `docker exec -it [container_name] sh`, then make commands which you recommended previously?

**Comment by tgulacsi** [comment]
No. xgo does everything if docker is available: download the required images (with the required C compiler and Go compiler in it), copies the source and compiles it inside the proper Docker image.

So just install xgo (`go get -u github.com/karalabe/xgo`) and use it (`xgo --targets=linux/* your/package/here`)!

**Comment by NogerbekNurzhan** [comment]
@tgulacsi I am confused. Let me try to explain you what I am trying to do. I created `golang` application which use `goracle` library in `windows 10`. In my local machine this application works fine. In the same time I don't have docker in my local machine. I remove source code to production `CentOS` server. Inside this server I have `Docker` (version 17.03.2-ce, build f5ec1e2). In the same time golang don't installed globally in this server cause we use Docker. So as I understand I need to use this command firstly `docker pull karalabe/xgo-latest` to install xgo, right? Then how I can use xgo in this case?

**Comment by tgulacsi** [comment]
As xgo's README says, either you invoke docker with proper parameters and use karalabe/xgo-latest directly, or use the nice `xgo` wrapper.

As I see that is a simple Go program, which can be easily cross-compiled from windows to Linux:

    go get github.com/karalabe/xgo
    GOOS=linux go build -o xgo github.com/karalabe/xgo

then transfer that xgo ELF binary to your Linux server with Docker, and use it there.
