### ISSUE TITLE
Huge performance decrease on Next() in latest versions

### ISSUE THREAD

**Issue by ricsmania** [go-goracle/goracle#8]
I was using aa4eaea22 , and when I updated to 7a9e6c2af I noticed a huge performance hit.

To test I used the database/sql compatible driver, querying and fetching 1 million records. I'm using the same machine and database, just changing the repository between tests.

Old version: 56k rows/second
New version: 30k rows/second

I replaced the [Next() func](https://github.com/go-goracle/goracle/blob/v1/driver.go#L225-L245) with the old one and the performance increased dramatically, but it is still a little slower than the old one, so I suspect something else is also to blame:
New version with old Next(): 48k rows/second

**Comment by tgulacsi** [comment]
Strange. Only 888df3d4 changed Next() between aa4eaea and 7a9e6c2.

If you can create a benchmark/test function for it, that would be the best.
Till that, first I'd comment out all the debug messages in Next, then look
around in fetchOneInto, maybe the reflect changes introduced such
performance degradation.

If you're adventureous enough, you can try out gopkg.in/rana/ora.v2

---
https://onename.com/tgulacsi

2015-08-26 15:47 GMT+02:00 Ricardo Smania <notifications@github.com>:

**Comment by ricsmania** [comment]
@tgulacsi I'm pretty sure 888df3d caused it.

When I have some spare time I'll create a benchmark function and try to investigate it.

I have tried Rana, but the database/sql implementation only reads 11.5k rows/sec. Goracle reads 56k (before 888df3d), and go-oci8 52k.

But Rana's specific Oracle implementation looks very promising. Right now I'm thinking about using Goracle for generic database/sql and Rana for PL/SQL, sys_refcursors and such. Like you said in your readme, it does have a better syntax. How about joining forces and making a single driver with the best of both? =)

**Comment by tgulacsi** [comment]
I've contributed some to rana/ora:
https://github.com/rana/ora/commits/master :)

If you can provide us a good benchmark function, we can try to optimize
reading of rows.

---
https://onename.com/tgulacsi

2015-08-26 17:50 GMT+02:00 Ricardo Smania <notifications@github.com>:

**Comment by tgulacsi** [comment]
@ricsmania I've just commited some performance improvement into gopkg.in/rana/ora.v3.
If you're still interested, take a look! It shaves off some time for selecting strings.
