### ISSUE TITLE
 dpiImpl.h: No such file or directory

### ISSUE THREAD

**Issue by marct83** [go-goracle/goracle#80]
vendor/gopkg.in/goracle.v2/conn.go:20:10: fatal error: dpiImpl.h: No such file or directory
 #include "dpiImpl.h"
          ^~~~~~~~~~~
compilation terminated.

**Comment by tgulacsi** [comment]
Which version is vendored in?
Did the vendor tool copy the C files (*.h, *.c) under `gopkg.in/goracle.v2/odpi` ?

**Comment by tgulacsi** [comment]
Sorry, I don't know dep.
Do you use `prune = non-go` anywhere?
Maybe just adding the `odpi` directory from a freshly checked out `gopkg.in/goracle.v2 to `vendor/gopkg.in/goracle.v2` would help.

**Comment by tgulacsi** [comment]
See https://github.com/golang/dep/issues/1731

**Comment by marct83** [comment]
This seems to have fixed it

[[prune.project]]
  name = "gopkg.in/goracle.v2"
  non-go = false
  unused-packages = false

**Comment by tgulacsi** [comment]
Glad to hear!
