### ISSUE TITLE
Can I ask help for lob insert?

### ISSUE THREAD

**Issue by kevino83** [go-goracle/goracle#83]
Hello,
I'm using goracle to try to replace a little batch in nodejs that cache on db a json format file.
I didn't find out how to insert a lob in a blob or json oracle.
Can I ask for an advice?
thanks

**Comment by tgulacsi** [comment]
use a goracle.Lob{Reader:yourReaderThatReturnsTheBytesToBeInserted}.

kevino83 <notifications@github.com> ezt írta (időpont: 2018. júl. 31., K,
17:50):

**Comment by kevino83** [comment]
hello, really thanks

I was using  a column type
MYJSON CLOB  CHECK (myjson IS JSON)
and testing with a stupid string like "abcd".

changed it to "{\"test\":1 }" or 
**goracle.Lob**{Reader: strings.NewReader("{\"test\":1}"), IsClob: true}
worked like a sharm 👍 

I also needed to re-study a little (it was some time with no golang programming) :-)
