### ISSUE TITLE
Does go-oracle support oracle-9i version?

### ISSUE THREAD

**Issue by xxh2000** [go-goracle/goracle#86]

**Comment by cjbj** [comment]
goracle uses [ODPI-C](https://github.com/oracle/odpi) as the access layer which can use Oracle client libraries 11.2 which can connect to Oracle DB 9.2 or later.  Whether anyone has tested goracle specifically with Oracle DB 9.2, I don't know.  Let us know what you find when you test it - I'd be interested to hear.

**Comment by xxh2000** [comment]
Ok, I will give you some feedback when I finish the test

**Comment by JekRock** [comment]
Hi!
I've tested gooracle with Oracle 9 using oracle client 11.2, and it works fine.

**Comment by cjbj** [comment]
@JekRock thanks for sharing.

**Comment by xxh2000** [comment]
@JekRock ok , thanks for your test
