### ISSUE TITLE
exec: "gcc": executable file not found in %PATH%

### ISSUE THREAD

**Issue by sunkaraamrutha** [go-goracle/goracle#89]
Hello There, 

I am running into the following issue when i run tests against my code that calls # gopkg.in/goracle.v2 package on windows, which was working very well for linux systems. 

 go test
# gopkg.in/goracle.v2
exec: "gcc": executable file not found in %PATH%
FAIL    github.com/nytm/dba-common-go/common [build failed]

Is this package not supported for windows?

**Comment by tgulacsi** [comment]
Absolutely supported, but - just as on Linux - it needs a working C compiler.

**Comment by sunkaraamrutha** [comment]
Do you have recomendations for any specific C compliers that i can install for windows that works great with this package?

**Comment by tgulacsi** [comment]
Nothing special - GCC, MinGW, TDM-GCC, clang - all of them are usable.
https://github.com/robbmcleod/cgo-by-example-windows suggests tdm-gcc-64.

**Comment by sunkaraamrutha** [comment]
Awesome! I installed MinGW and it works great for me. Thanks for the prompt response.
