### ISSUE TITLE
Remove hardcoded references to LDFLAGS -lclntsh

### ISSUE THREAD

**Issue by ricsmania** [go-goracle/goracle#9]
All references -lclntsh are hardcoded. This causes problems on Windows because we need to change them to -loci, as described on the readme, or else it won't work.

Other drivers take different approaches:

Go-oci8 uses pkg-config and needs a oci8.pc file where the library name is specified:
Libs: -L${oralib} -L${gcclib} **-loci**

Rana suggests defining an environment variable with the library name (Goracle only needs -L):
$env:CGO_LDFLAGS="-LC:\Oracle\instantclient_12_1_64\sdk\lib\msvc **-loci**"

I like Rana's way of dealing with this, because it's simpler to implement and use.

@tgulacsi what do you think about removing the hardcoded references from Goracle and instead relying on the environment variable?

**Comment by tgulacsi** [comment]
Done.

---
https://onename.com/tgulacsi

2015-08-26 18:35 GMT+02:00 Ricardo Smania <notifications@github.com>:

**Comment by ricsmania** [comment]
Awesome, seems to be working fine! Thanks!
