### ISSUE TITLE
oracle spatial field rasie exception :newVar(type=2023,natTyp=3009,sliceLen=25,bufferSize=0):ORA-00000:DPI-1025

### ISSUE THREAD

**Issue by nancaibeiwang** [go-goracle/goracle#90]
when oracle db column has a spatial field , it will rasie exception :newVar(type=2023,natTyp=3009,sliceLen=25,bufferSize=0):ORA-00000:DPI-1025, my solution is: 
add vi.ObjectType=ti.objectType in stmt.go ,eg:

func (st *statement) openRows(colCount int) (*rows, error) {
	C.dpiStmt_setFetchArraySize(st.dpiStmt, C.uint32_t(st.FetchRowCount()))

	r := rows{
		statement: st,
		columns:   make([]Column, colCount),
		vars:      make([]*C.dpiVar, colCount),
		data:      make([][]C.dpiData, colCount),
	}
	vi := varInfo{SliceLen: st.FetchRowCount()}

	var info C.dpiQueryInfo
	var ti C.dpiDataTypeInfo
	for i := 0; i < colCount; i++ {
		if C.dpiStmt_getQueryInfo(st.dpiStmt, C.uint32_t(i+1), &info) == C.DPI_FAILURE {
			return nil, errors.Wrapf(st.getError(), "getQueryInfo[%d]", i)
		}
		ti = info.typeInfo
		bufSize := int(ti.clientSizeInBytes)
		/************add  start**********************/
		// add this it will work ok,if fields has object type
		vi.ObjectType=ti.objectType
		/************add end**********************/
		//if Log != nil {Log("msg", "openRows", "col", i, "info", ti) }
		//if Log != nil {Log("dNTN", int(ti.defaultNativeTypeNum), "number", C.DPI_ORACLE_TYPE_NUMBER) }
		switch ti.oracleTypeNum {
		case C.DPI_ORACLE_TYPE_NUMBER:
			switch ti.defaultNativeTypeNum {
			case C.DPI_NATIVE_TYPE_FLOAT, C.DPI_NATIVE_TYPE_DOUBLE:
				ti.defaultNativeTypeNum = C.DPI_NATIVE_TYPE_BYTES
				bufSize = 40
			}
		case C.DPI_ORACLE_TYPE_DATE:
			ti.defaultNativeTypeNum = C.DPI_NATIVE_TYPE_TIMESTAMP
		}
		r.columns[i] = Column{
			Name:        C.GoStringN(info.name, C.int(info.nameLength)),
			OracleType:  ti.oracleTypeNum,
			NativeType:  ti.defaultNativeTypeNum,
			Size:        ti.clientSizeInBytes,
			Precision:   ti.precision,
			Scale:       ti.scale,
			Nullable:    info.nullOk == 1,
			ObjectType:  ti.objectType,
			SizeInChars: ti.sizeInChars,
			DBSize:      ti.dbSizeInBytes,
		}
		var err error
		//fmt.Printf("%d. %+v\n", i, r.columns[i])
		vi.Typ, vi.NatTyp, vi.BufSize = ti.oracleTypeNum, ti.defaultNativeTypeNum, bufSize
		if r.vars[i], r.data[i], err = st.newVar(vi); err != nil {
			return nil, err
		}

		if C.dpiStmt_define(st.dpiStmt, C.uint32_t(i+1), r.vars[i]) == C.DPI_FAILURE {
			return nil, errors.Wrapf(st.getError(), "define[%d]", i)
		}
	}
	if C.dpiStmt_addRef(st.dpiStmt) == C.DPI_FAILURE {
		return &r, errors.Wrap(st.getError(), "dpiStmt_addRef")
	}
	st.columns = r.columns
	return &r, nil
}

**Comment by cjbj** [comment]
@nancaibeiwang what's your CREATE TABLE clause?

**Comment by tgulacsi** [comment]
Thanks! 

Please try 575684a and provide a test case / CREATE TABLE clause !

**Comment by tgulacsi** [comment]
Can you try "go test -v -run=SDO" with 0340d85 ?
It fails spectacularly (breaks the connection) on 
  Server: 11.2.0.4.0 [Oracle Database 11g Release 11.2.0.4.0 - 64bit Production]
  Client: 11.2.0.4.0
