### ISSUE TITLE
Return dataSet

### ISSUE THREAD

**Issue by margem** [go-goracle/goracle#91]
Is it possible to work with dataset using this driver? I have a procedure that returns me a dataset, but I'm not able to do the mapping.

	QUERY := `BEGIN
  		MOBILE.PC_MOBILE.PQ_QT_VISITAS(
  		p_dt_ini => :vParam1,
   		p_dt_fim => :vParam2,
   		p_regional => :vParam3,
   		p_resultset => :vParam4
  		);
  		END;
 	`
	_, err := db.Exec(QUERY, oracle.PlSQLArrays, dataInicial, dataFinal, regiao, sql.Out{Dest: &maior});
	if err != nil {
		log.Println(err)
	}
	log.Println(maior)
	log.Println(media)

**Comment by tgulacsi** [comment]
What is `maior`? Is it a database/sql/driver.Rows ? 
Can you provide a complete example?

**Comment by margem** [comment]
My function, 

func GetMajorMedium(dataInicial string, dataFinal string, regiao string) {
	var maior struct{}

	db := dbConnectionOracle()
	defer db.Close()

	QUERY := `BEGIN
  		MOBILE.PC_MOBILE.PQ_QT_VISITAS(
  		p_dt_ini => :vParam1,
   		p_dt_fim => :vParam2,
   		p_regional => :vParam3,
   		p_resultset => :vParam4
  		);
  		END;
 	`
	_, err := db.Exec(QUERY, oracle.PlSQLArrays, dataInicial, dataFinal, regiao, sql.Out{Dest: &maior});
	if err != nil {
		log.Println(err)
	}
	log.Println(maior)
}

**Comment by margem** [comment]
@tgulacsi here is my procedure

PROCEDURE pr_qt_visitas(p_dt_ini    IN mobile.visita_relacionamento.data_visita%TYPE,
                          p_dt_fim    IN mobile.visita_relacionamento.data_visita%TYPE,
                          p_regional  VARCHAR2,
                          p_resultset OUT resultset)

**Comment by margem** [comment]
@tgulacsi What is driver.Rows?  Is it gopkg.in/goracle.v2? But I don't understand

**Comment by margem** [comment]
ok, but in my terminal the project say that driver.Rows is undefined, look that

![oracle](https://user-images.githubusercontent.com/4268383/44632690-649b1700-a955-11e8-94ef-3c7d50b9d500.png)

**Comment by margem** [comment]
@tgulacsi  ok, but in my terminal the project say that cannot use values (type []interface {}) as type []driver.Value in argument to rset.Next

database/database.go:55:22: cannot use values (type []interface {}) as type []driver.Value in argument to rset.Next

![captura de tela 2018-08-26 17 45 01](https://user-images.githubusercontent.com/4268383/44632831-150a1a80-a958-11e8-88e5-db1f378b5c8b.png)

**Comment by tgulacsi** [comment]
change that `[]interface{}` to `[]driver.Value`.

**Comment by margem** [comment]
Thanks @tgulacsi, now is happening this error:  **ORA-06550: line 1, column 7:
PLS-00306: wrong number or types of arguments in call to 'PR_QT_VISITAS'**

My procedures - `BEGIN MOBILE.PC_MOBILE.PR_QT_VISITAS(:1, :2, :3, :4); END;`

Parameters type 
:1 -  Date
:2 - Date
:3 - Varchar 
:4 - resultSet (in Go passing empty interface)

What could happen?

**Comment by tgulacsi** [comment]
You haven't provided the code, so I'm just guessing: :1, :2 are time.Time, :3 is string, and what is :4 ?

A working example is in https://github.com/tgulacsi/go/blob/master/dbcsv/csvdump/csvdump.go#L241 - the dumpCall calls a stored procedure, which returns a resultset into a driver.Rows, then prepares the needed []driver.Value for the Next calls.

**Comment by margem** [comment]
@tgulacsi That problem is when resultSet is list, the return being first object in list, but I need all object in array.

**Comment by tgulacsi** [comment]
You still haven't provided a runnable code.

The code you posted above prints if and only `if err != nil` - it should `log.Println(values)` outside the condition.

**Comment by margem** [comment]
func GetCitiesByModality(params params.Search) {
	db := dbConnectionOracle()
	defer db.Close()

	ctx := context.Background()

	var resultI driver.Rows
	
	_, err := db.ExecContext(ctx, procedure.PR_CONSULTAR_CIDADE(), params.Modalidade, nil, params.UF, params.Cidade, nil, nil, 1, sql.Out{Dest: &resultI})
	if err != nil {
		log.Println("Error => ", err)
		return
	}
	defer resultI.Close()

	cidades := []structs.City{}
	
	values := make([]driver.Value, len(resultI.Columns()))
	for {
  		if err = resultI.Next(values); err != nil {
  			log.Println(values)
    		if err == io.EOF {
      			break
   			}
  		}	
	}
}

**Comment by tgulacsi** [comment]
```
       ctx := context.Background()

	var resultI driver.Rows
	
	_, err := db.ExecContext(ctx, procedure.PR_CONSULTAR_CIDADE(), params.Modalidade, nil, params.UF, params.Cidade, nil, nil, 1, sql.Out{Dest: &resultI})
	if err != nil {
		log.Println("Error => ", err)
		return
	}
	defer resultI.Close()
	
	values := make([]driver.Value, len(resultI.Columns()))
	for {
  		err = resultI.Next(values)
                if err != nil {
    		        if err == io.EOF {
      			        break
   			}
                        log.Println("error:", err)
  		}	
        	log.Println(values)
	}
```

**Comment by margem** [comment]
Thanks @tgulacsi

**Comment by margem** [comment]
@tgulacsi I'm trying convert a goracle.Number to int64 but return this message: interface conversion: driver.Value is goracle.Number, not int64

values := make([]driver.Value, len(resultI.Columns()))
for {
	err = resultI.Next(values)
            if err != nil {
		        if err == io.EOF {
  			        break
				}
        log.Println("error:", err.Error())
	}

   	log.Println("...")
   	v := values[0].Value()
   	log.Println(v)
}

**Comment by tgulacsi** [comment]
This is type cast, not conversion.
goracle.Number is just the string representation, so use
strconv.ParseInt64.

Or use goracle.WrapRows (experimental) to turn the driver.Rows into an
sql.Rows and have its nise Scan functionality.

Margem <notifications@github.com> ezt írta (időpont: 2018. szept. 26., Sze
21:23):
