### ISSUE TITLE
Database connection working on v2.5.5 but not on >= v2.5.6

### ISSUE THREAD

**Issue by drsect0r** [go-goracle/goracle#92]
My application is unable to connect to an Oracle database 11g by using anything higher than release v2.5.5. I have tested and confirmed that v2.5.8, v2.5.7 and v2.5.6 don't work and return 'ora-01017: invalid username/password; logon denied' as the error message; v2.5.5 works correctly and establishes a working connection that is verified by ping(). 

Relevant code:
```go
params := goracle.ConnectionParams{
	Username:    os.Getenv("ORACLE_USERNAME"),
	Password:    os.Getenv("ORACLE_PASSWORD"),
	SID:         os.Getenv("ORACLE_SID"),
	MinSessions: 1,
	MaxSessions: 5,
}

// opens a database specified by its database driver name and source name
oracle, err := sql.Open("goracle", params.String())
if err != nil {
	return nil, err
}

// verifies if the connection to the database is alive
if err := oracle.Ping(); err != nil {
	return nil, err
}
```

Environment information:
```
LD_LIBRARY_PATH=/usr/lib/oracle/12.2/client64/lib
TNS_ADMIN=/usr/lib/oracle/12.2/client64/network/admin
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/lib/oracle/12.2/client64/bin:/root/bin
ORACLE_HOME=/usr/lib/oracle/12.2/client64
```

**Comment by tgulacsi** [comment]
git diff v2.5.5..v2.5.6
 - do not show password
 - ODPI v2.4.0 -> v2.4.2
nothing suspicious.

Are you sure the problem is the version?
Can you copy here the connection string you use - with the password changed to "SECRET" ?

**Comment by tgulacsi** [comment]
Ok, I've got it: ConnectionParams.String() does NOT print the password, only ConnectionParams.StringWithPassword() does!
