### ISSUE TITLE
Failed to build on windows platform

### ISSUE THREAD

**Issue by xxh2000** [go-goracle/goracle#93]
When I was building a project on Windows system, I encountered the following problem. I have installed minGW, I don’t know what caused it.

![image](https://user-images.githubusercontent.com/10917455/44760500-9ee10000-ab71-11e8-8768-52f1ac285b57.png)

![image](https://user-images.githubusercontent.com/10917455/44760514-aaccc200-ab71-11e8-9272-845c734fb480.png)

**Comment by tgulacsi** [comment]
http://lmgtfy.com/?q=undefined+reference+to+__imp___acrt_iob_func

https://github.com/rust-lang/rust/issues/47048#issuecomment-377711643 says MinGW 7.2.0 has this bug - try 7.1, 7.3 or 8.1 - misses this function from the bundled rt.

**Comment by cjbj** [comment]
> need to install vs2008 or higher when running odpi-c on the windows

For future readers the ODPI-C documentation says that for each Oracle client library version you need the matching VS redistributable version.  There is a one-to-one correspondence.  It cannot be 'or higher'.

**Comment by xxh2000** [comment]
@cjbj  thanks for sharing the info
