### ISSUE TITLE
DPI-1047: Oracle Client library cannot be loaded

### ISSUE THREAD

**Issue by boneq** [go-goracle/goracle#97]
ORA-00000: DPI-1047: 64-bit Oracle Client library cannot be loaded: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help

How do I use this? Do I need a Oracle client?

package main

import (
	"database/sql"
	"fmt"
	"os"
	_ "gopkg.in/goracle.v2"
)

func main() {
	or,err:=sql.Open("goracle","....")
	if err != nil {
		fmt.Println(123)
		fmt.Println(err.Error())
		os.Exit(0)
	}
	e,err:=or.Exec("select t.table_name from user_tables t;")
	if err != nil {
		fmt.Println(444)
		fmt.Println(err.Error())
		os.Exit(0)
	}
	fmt.Println(e)
}

**Comment by tgulacsi** [comment]
To connect to an Oracle DB, you'll need the Oracle provided libraries - either the ones that's installed with the Oracle DB under $ORACLE_HOME, or an Oracle Instant Client (http://www.oracle.com/technetwork/database/database-technologies/instant-client/downloads/index.html).

**Comment by boneq** [comment]
Thank you
