### ISSUE TITLE
why goralce listen :::*

### ISSUE THREAD

**Issue by dingkaich** [go-goracle/goracle#98]
I find goracle will listen random port on any network.
below is 
SZX1000367778:/home/install/license/log # netstat -anp | grep license
tcp        0      0 10.93.79.78:62935       10.162.105.135:1547     ESTABLISHED 115247/licenseserve
tcp        0      0 10.93.79.78:47656       10.93.79.78:2181        ESTABLISHED 115247/licenseserve
tcp        0      0 127.0.0.1:58554         127.0.0.1:65003         ESTABLISHED 115247/licenseserve
tcp        0      0 10.93.79.78:62934       10.162.105.135:1547     ESTABLISHED 115247/licenseserve
tcp        0    350 10.93.79.78:62946       10.162.105.135:1547     ESTABLISHED 115247/licenseserve
tcp        0      0 127.0.0.1:50034         127.0.0.1:65001         ESTABLISHED 115247/licenseserve
tcp        0      0 :::59273                :::*                    LISTEN      115247/licenseserve

how to close the :::59273                :::*  ???
we think this is non-securtiy ? Could we listen in 127.0.0.1 ?

**Comment by dingkaich** [comment]
add my code:
        var err error
        // db, err = sql.Open("ora", dsn)
        dsn = dsn1
        db, err = sql.Open("goracle", dsn)
        if err != nil || db == nil {
                log.Println(err, db)
                return
        }

        //err = db.Ping()
        //if err != nil {
        //      log.Println("db ping error", err)
        //      return
        //}
        //db.SetMaxIdleConns(30)
        //db.SetMaxOpenConns(30)
        // err = testinsertclob()
        // if err != nil {
        //      log.Println(err)
        //      return
        // }
        err = QueryLicenseFileByLicenseNo()
        if err != nil {
                log.Println(err)
        }
        select {}

**Comment by tgulacsi** [comment]
```
$ cat /tmp/x/main.go
package main

import (
        "database/sql"
        "flag"
        "log"

        "github.com/pkg/errors"
        _ "gopkg.in/goracle.v2"
)

func main() {
        dsn := "test/test@oracle.gthomas.eu:49161/xe"
        flag.Parse()
        if flag.Arg(0) != "" {
                dsn = flag.Arg(0)
        }
        db, err := sql.Open("goracle", dsn)
        if err != nil {
                log.Fatal(errors.Wrap(err, dsn))
        }
        defer db.Close()
        var n int64
        if err := db.QueryRow("SELECT COUNT(0) FROM user_tables").Scan(&n); err != nil {
                log.Fatal(err)
        }
        select {}
}
```

Strange: 
```
:gthomas@redpath: ~
$ lsof -i -a -p $(pidof goracle)
COMMAND   PID    USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
goracle 10490 gthomas    4u  IPv4 4145558      0t0  TCP redpath:46386->178-164-165-75.pool.digikabel.hu:49161 (ESTABLISHED)
goracle 10490 gthomas    5u  IPv6 4145560      0t0  TCP *:42667 (LISTEN)
goracle 10490 gthomas    7u  IPv4 4144916      0t0  TCP redpath:46388->178-164-165-75.pool.digikabel.hu:49161 (ESTABLISHED)
```

I've never investigated before, so I don't know. But it's definitely strange that it listens on IPv6, all interfaces, on a random port.
Maybe @cjbj or @anthony_tuininga can help, as I'm (almost) sure thate the Go part of goracle
does no such thing. Either ODPI-C, or (more possibly) OCI (libclntsh.so) does this.

**Comment by tgulacsi** [comment]
```
$ strace ./goracle 2>&1|fgrep -B50 bind
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220M\4\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=8348633, ...}) = 0
mmap(NULL, 6166216, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fdecc074000
mprotect(0x7fdecc431000, 2093056, PROT_NONE) = 0
mmap(0x7fdecc630000, 90112, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3bc000) = 0x7fdecc630000
mmap(0x7fdecc646000, 63176, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fdecc646000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\3402\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=100712, ...}) = 0
mmap(NULL, 103472, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fdecc05a000
mprotect(0x7fdecc05d000, 86016, PROT_NONE) = 0
mmap(0x7fdecc05d000, 69632, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7fdecc05d000
mmap(0x7fdecc06e000, 12288, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x14000) = 0x7fdecc06e000
mmap(0x7fdecc072000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7fdecc072000
close(3)                                = 0
mprotect(0x7fdecc072000, 4096, PROT_READ) = 0
mprotect(0x7fdecca1d000, 4096, PROT_READ) = 0
mprotect(0x7fdecc887000, 4096, PROT_READ) = 0
mprotect(0x7fded274a000, 4096, PROT_READ) = 0
mprotect(0x7fdecc870000, 4096, PROT_READ) = 0
mprotect(0x7fdecc66b000, 4096, PROT_READ) = 0
munmap(0x7fdecda93000, 122437)          = 0
mmap(NULL, 143360, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fdecc037000
openat(AT_FDCWD, "/usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@C<\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=77879517, ...}) = 0
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/oracle/18.3/client64/lib/libociei.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/oracle/18.3/client64/lib/libociicus.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\210\10\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=6508420, ...}) = 0
mmap(NULL, 8597000, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fdeb385c000
mprotect(0x7fdeb3e8f000, 2093056, PROT_NONE) = 0
mmap(0x7fdeb408e000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x632000) = 0x7fdeb408e000
close(3)                                = 0
openat(AT_FDCWD, "/home/gthomas/.config/oracle/oraaccess.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
access("/home/gthomas/.config/oracle/oraaccess.xml", F_OK) = -1 ENOENT (No such file or directory)
lstat("/etc/orabasetab", 0x7fff43eafca0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/orabasetab", O_RDONLY) = -1 ENOENT (No such file or directory)
lstat("/usr/lib/oracle/18.3/client64/lib/install/orabasetab", 0x7fff43eafca0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/oracle/18.3/client64/lib/install/orabasetab", O_RDONLY) = -1 ENOENT (No such file or directory)
access("/usr/lib/oracle/18.3/client64/lib/network/admin/oraaccess.xml", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/oracle/18.3/client64/lib/network/admin/oraaccess.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
getcwd("/tmp/x", 256)                   = 7
lstat("/usr/lib/oracle/18.3/client64/lib/env.ora", 0x7fff43eb3470) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/oracle/18.3/client64/lib/env.ora", O_RDONLY) = -1 ENOENT (No such file or directory)
brk(0xb8f000)                           = 0xb8f000
socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 3
bind(3, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = 0
```

**Comment by dingkaich** [comment]
Did you know which OCI inteface will start a listen in client ?

**Comment by dingkaich** [comment]
socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 3
bind(3, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = 0

From strace , it looks bind in localhost , but actually it bind in 0.0.0.0 ?
So starnge！

**Comment by dingkaich** [comment]
Dear tgulacsi
when I do below change in drv.go, the ::: listen will be disappeared.

func (d *drv) openConn(P ConnectionParams) (*conn, error) {
++ commonCreateParams.createMode = C.DPI_MODE_CREATE_DEFAULT | C.DPI_MODE_CREATE_THREADED 
-- commonCreateParams.createMode = C.DPI_MODE_CREATE_DEFAULT | C.DPI_MODE_CREATE_THREADED | C.DPI_MODE_CREATE_EVENTS
}

It seams that DPI_MODE_CREATE_EVENTS will start a ::: listen.
Did u know why ?

**Comment by tgulacsi** [comment]
You're right. That's where I've presumed the reason: for events, the DB server must be able to send events, somehow. Seems that Oracle does not use the already established TNS connection for it, but allocates a separate one.

The CREATE_EVENTS mode is required by subscriptions.
As I don't use it yet, and haven't tested it thoroughly, but nobody filed an issue with the subscriptions, I assume nobody using it.

So I change the default to be without EVENTS, put it behind an opt-in flag (enableEvents=1), so the default will be "no listening".

See v2.8.0  - b93a23e265618cf8fd7feeb7bac1c95a242ffaff !

**Comment by dingkaich** [comment]
okay. thank you for your update !
