### ISSUE TITLE
Add support for OCI_ATTR_CALL_TIMEOUT

### ISSUE THREAD

**Issue by rvegas** [go-goracle/goracle#99]
Hello, the recent release of oracle instant client announced that C clients would get support for call timeout parameters, this would be a great addition.

https://docs.oracle.com/en/database/oracle/oracle-database/18/lnoci/handle-and-descriptor-attributes.html#GUID-D8EE68EB-7E38-4068-B06E-DF5686379E5E

You guys see this getting implemented anytime soon for goracle?

**Comment by anthony-tuininga** [comment]
This has been wrapped in ODPI-C (which goracle uses) as can be seen [here](https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_setCallTimeout).

**Comment by tgulacsi** [comment]
It's been implemented in e0af5022b0c4ee6056d0dadc67d20783b3d3286a , 10 days ago.

**Comment by cjbj** [comment]
The rule of thumb is that it needs to be user settable.  There are too many variables, from user requirements to network speeds, that make a generic default infeasible.

**Comment by tgulacsi** [comment]
Thanks, I've added a CallTimeout option to be able to set the timeout for each statement.

**Comment by rvegas** [comment]
Wow, thanks for the swift action, this is indeed very helpful.

**Comment by cjbj** [comment]
@rvegas let us know how it works out for you.

**Comment by tgulacsi** [comment]
It's in v2.8.1
